### ISSUE TITLE
Admin API: Posting new peers should return failed peers

### ISSUE THREAD

**Issue by jm-clius** [waku-org/nwaku#1032]
Currently the JSON-RPC API `post_waku_v2_admin_v1_peers` method times out after 30 seconds with a simple failure. It also tries to connect to each peer in the request in sequence and `await`s those connections individually, rather than concurrently spawning connection attempts.

## Acceptance Criteria

- [ ] align the request timeout with the underlying libp2p connection timeout
- [ ] return the exact peer connections that failed/timed out in response
- [ ] where possible, spawn concurrent connection attempts and indicate failed futures in response

## Where should this be fixed?

Although this method is currently only available in the JSON-RPC API, the move to an HTTP REST API means that it should be implemented correctly for the equivalent REST resource there. 

cc @LNSD @jakubgs

**Comment by jm-clius** [comment]
Part of consideration for API work, which moves to next release.

**Comment by Ivansete-status** [comment]
I close this as we are planning to deprecate JSON-RPC
