### ISSUE TITLE
Produce raw RLN contract RFC

### ISSUE THREAD

**Issue by kgrgpg** [waku-org/nwaku#1040]
Produce raw RLN contract RFC

**Comment by kgrgpg** [comment]
The associated pull request is https://github.com/vacp2p/rfc/pull/522

**Comment by Ivansete-status** [comment]
Hey @rymnc ! Is this still needed?

**Comment by rymnc** [comment]
Hey, this should be moved to the rln-contract repo, I'll do it soon
