### ISSUE TITLE
Exception handling for MountRlnRelay proc after persistent rln credentials were introduced

### ISSUE THREAD

**Issue by kgrgpg** [waku-org/nwaku#1045]
Refer to https://github.com/status-im/nwaku/pull/1037#discussion_r926609731

**Comment by kgrgpg** [comment]
Initial lead is as follows: https://github.com/status-im/nwaku/pull/1037#discussion_r930540457

**Comment by rymnc** [comment]
No, this issue can be closed. Addressed in https://github.com/waku-org/nwaku/pull/1285
