### ISSUE TITLE
Enable Zerokit by default

### ISSUE THREAD

**Issue by oskarth** [waku-org/nwaku#1061]
# Problem

We want to use Zerokit by default to have one code base to worry about and pave the way to cross-client testnet.

## Notes

Before this can happen, we need the following:

- [x] https://github.com/status-im/nwaku/pull/1030 or eqv merged. 
EDIT: merged https://github.com/status-im/nwaku/pull/1060
- [ ] Testnet1 complete https://github.com/vacp2p/research/issues/126
- [x] Implementation tested to ensure no major regressions found
- [x] https://github.com/status-im/nwaku/issues/1227

## Acceptance criteria

- Zerokit enabled by default

We can either remove flag in PR that addresses this, or do this at a later stage (depends on confidence around perf etc)

---

cc @s1fr0 @staheri14 just to capture this future work and its dependencies.

**Comment by staheri14** [comment]
@s1fr0 it would be very helpful to have an issue in  https://github.com/vacp2p/rln-contract  covering updates that are needed to be done on the contract, and with pointers to the relevant repos and files. Thanks!

**Comment by staheri14** [comment]
What is the state of this issue? I guess it needs some updates

**Comment by staheri14** [comment]
If zero-kit gets enabled by default, it will help resolving this issue as well https://github.com/status-im/nwaku/issues/1213
