### ISSUE TITLE
Noise: add support to payload v1 cryptographic primitives

### ISSUE THREAD

**Issue by s1fr0** [waku-org/nwaku#1063]
# Problem

Noise [specifications](https://rfc.vac.dev/spec/35/#backward-support-for-symmetricasymmetric-encryption) describe how to backward support payload [v1 cryptographic primitives](https://rfc.vac.dev/spec/26/) in Noise payload v2. However, support to v1 primitives in Noise module need to be implemented.

# Acceptance criteria
- Add support to AES-256-GCM symmetric encryption (`protocol-id = 254`)
- Add support to ECIES asymmetric encryption (`protocol-id = 255`)

**Comment by Ivansete-status** [comment]
Is this still needed @jm-clius ?

**Comment by jm-clius** [comment]
No resources currently assigned to Noise, but effort/open issues still relevant. May move to a team separate from nwaku

**Comment by jm-clius** [comment]
Closing this issue, as Waku is deprioritising any v1-interoperation work.
