### ISSUE TITLE
Handling print statements in chat2 using EDD pattern (specific to waku-rln-relay)

### ISSUE THREAD

**Issue by staheri14** [waku-org/nwaku#1083]
# Problem
Print statements should ideally happen inside the main program, but not from inside other procedures in an ad-hoc manner. 
Right now in chat2, this pattern is violated  in the publish `proc` where a warning message is printed on the console when a published message is found spam. 
This issue is to address this anti-pattern. Possibly by updating a few function interfaces to accept a callback function to be invoked at the time that a spam message is about to be published.

**Comment by jm-clius** [comment]
Unlikely to be implemented with the new approach to RLN integration.
