### ISSUE TITLE
Review nwaku's resume store on boot mechanism

### ISSUE THREAD

**Issue by LNSD** [waku-org/nwaku#1129]
### Problem
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

TBD
### Suggested solution
> A clear and concise description of what you want to happen.

TBD

### Alternatives considered
> A clear and concise description of any alternative solutions or features you've considered.

TBD

### Additional context
Nwaku's _resume store on boot_ mechanism is implemented using the timeframe query mechanism specified by the [21/WAKU2-FTSTORE RFC](https://rfc.vac.dev/spec/21/).

### Acceptance criteria
> A list of tasks that need to be done for the issue to be considered resolved.

TBD

**Comment by LNSD** [comment]
In _#nwaku_ channel at VAC's discord server @fryorcraken has asked the following questions:

> 1. It is currently not enabled in any fleet, right?
> 2. It only synchronize in-memory messages, right?
> 3. In what instance would a message be in the sqlite DB but not in memory?
> 4. I assume that for now, we would prefer to investigate missing message (ie, issue with relay?) before turning on FT-Store that may hide defect, right?
> 5. Anything else I need to know?

> One more question: when enabled, what triggers a sync?

> Also, would it make sense at a later stage to enable ft-store so that a node that is being reboot for upgrade/config change can catch up on messages?

**Comment by LNSD** [comment]
My answer @fryorcraken to your questions:

> It is currently not enabled in any fleet, right?

As far as I have seen, it is not. It requires the nodes to have a "store peer" configured, and at the moment, it is not the case. In Kibana, I observe warnings saying there's no peer to retrieve messages.

> It only synchronize in-memory messages, right?

In the current implementation, we only "resume" (the verb used in the code) the messages other nodes have stored during the time node was offline. And then it inserts them in the in-memory store. So if the node store protocol is working in "sqlite-only" mode, it won't insert the retrieved messages in the persistent store.

This is the remaining work from unifying the in-memory (aka message queue) and the persistent (aka message store) interface. After that, we'll be able to use the in-memory and the persistent store interchangeability.

> In what instance would a message be in the sqlite DB but not in memory?

If the node store protocol runs in "sqlite-only" mode. Everything interacts with the SQLite DB. The messages are inserted in the DB, and the history queries are performed to the DB too.

> I assume that for now, we would prefer to investigate missing message (ie, issue with relay?) before turning on FT-Store that may hide defect, right?

I am not aware of the "missing messages" issue. Is there any GH issue? 

I have observed several errors that fail to be persisted with the `message insert failed: constraint failed`, which I think that it is related to the message "uniqueness" rules that we have at this moment in the message store. I am investigating this issue at the moment.

If the issue is related to what I described in the previous section, then enabling the DB's "resume store on boot" mode (aka FT-STORE) should not mask the it. The messages considered duplicates won't be inserted in the DB the same way it is now.

> when enabled, what triggers a sync?

The FT-STORE RFC is implemented in a "rudimentary" way. It can be understood as: **resume message store on boot** mechanism. This is:

_At boot, if a waku store peer is configured, it queries it for all the messages that happened when the node was offline. This time corresponds to the timestamp of the most recent message stored in the database. If there is no last message (empty store), it queries all messages from the origin of times (aka UNIX epoch)._

> Also, would it make sense at a later stage to enable ft-store so that a node that is being reboot for upgrade/config change can catch up on messages?

That's exactly the point of the current implementation, as explained above.

**Comment by fryorcraken** [comment]
> I am not aware of the "missing messages" issue. Is there any GH issue?

It was rethorical

**Comment by fryorcraken** [comment]
Thanks for that. No issue for missing messages opened so far.

**Comment by felicio** [comment]
> Thanks for that. No issue for missing messages opened so far.

@fryorcraken, please see https://github.com/status-im/nwaku/issues/1146#issue-1371117865.

**Comment by felicio** [comment]
> At boot, if a waku store peer is configured, it queries it for all the messages that happened when the node was offline. This time corresponds to the timestamp of the most recent message stored in the database. If there is no last message (empty store), it queries all messages from the origin of times (aka UNIX epoch).

@LNSD if I got this right, then it also means that this protocol is not for background processes/crons backfilling undelivered or unsuccessfully stored messages _due to any other reasons then being offline_ (e.g. failed writes, corrupted db). Correct?

**Comment by LNSD** [comment]
Yes, that's correct. There is no background job synchronizing the stores.

There are plans to extend the current waku store resilience and recovery capabilities, but this is something that will be driven by @staheri14 after the RLN relay is wrapped up.
