### ISSUE TITLE
feat: cli flag for selecting log format

### ISSUE THREAD

**Issue by jakubgs** [waku-org/nwaku#1195]
### Problem
It would be nice to be able to select log format without having to recompile the binary like `nimbus-eth2` does with `--log-format`:
```nim
    logStdout* {.
      hidden
      desc: "Specifies what kind of logs should be written to stdout (auto, colors, nocolors, json)"
      defaultValueDesc: "auto"
      defaultValue: StdoutLogKind.Auto
      name: "log-format" .}: StdoutLogKind
```
https://github.com/status-im/nimbus-eth2/blob/f7db50522b299ceb558e81342f894ed8f0ac11c7/beacon_chain/conf.nim#L125-L130

### Acceptance criteria
It does what I said.

**Comment by LNSD** [comment]
Enabling the `json` format in the logs is not trivial. Some dependencies (current version of `nim-eth`) have types that cannot be serialized (e.g. nim-eth's `PublicKey` is not serializable).

We might want to upgrade the `nim-eth` version before start working on this issue (a PR is already opened: #1276)

**Comment by jm-clius** [comment]
Won't be ready for next week's release, so moved to `0.14.0`.
