### ISSUE TITLE
feat(networking): new metric showing if node is reachable

### ISSUE THREAD

**Issue by alrevuelta** [waku-org/nwaku#1206]
### Problem

As discussed with @jm-clius, currently there is no way for the node itself to be aware if it's reachable from the outside by other peers. #754 allows for an external party to check if it is reachable, but the node itself isn't aware of it.

### Suggested solution

The libp2p feature [autonat](https://docs.libp2p.io/concepts/nat/#autonat) allows us to request other peers to dial us, and if the response is ok, the node itself can be sure that it is reachable. Luckily, looks like [nim-libp2p](https://github.com/status-im/nim-libp2p/blob/master/libp2p/protocols/autonat.nim) support its. More info:

> While the [identify protocol](https://github.com/libp2p/specs/tree/master/identify) described above lets peers inform each other about their observed network addresses, not all networks will allow incoming connections on the same port used for dialing out.

> Once again, other peers can help us observe our situation, this time by attempting to dial us at our observed addresses. If this succeeds, we can rely on other peers being able to dial us as well and we can start advertising our listen address.

> A libp2p protocol called AutoNAT lets peers request dial-backs from peers providing the AutoNAT service.

Once we have the value `isNodeReachable` updated periodically, we can use it:
* in logs, warning if `false`.
* in prometheus, to feed a dashboard like Grafana.
* in RPC health checks. [related](https://github.com/status-im/nwaku/issues/754#issuecomment-1262248341)

### Alternatives considered

A less engineered approach would be to just check the number of `inbound` peers and if `!=0` consider that the node is reachable. However one can argue that no inbound peers won't strictly mean that were are not reachable. In other words:
* `n_inbound_peers!=0` means that the node is reachable
* `n_inbound_peers=0` doesn't necessarily mean that the node is not reachable. Perhaps in practice yes, but still.

### Acceptance criteria

- [ ] `dialMe` is used and returns `Reachable`, `NotReachable`, `Unknown`. Edit: Reuse [AutonatService](https://github.com/status-im/nim-libp2p/pull/806/files#diff-5013bc869e9361f5cbc8a3de1f82b356a0788764ff4103490003a59568c60af8)
- [x] number of inbound/outbound peers are displayed in metrics: https://github.com/waku-org/nwaku/pull/1424
- [ ] number of inbound/outbound peers are accessed via RPC? Imply spec change?
- [ ] The feature is documented for node operators.

**Comment by jm-clius** [comment]
Thanks. Very helpful and goes a long way towards addressing a common concern from node operators.

**Comment by jm-clius** [comment]
@alrevuelta any concerns if we remove this from `0.13.0` scope? We're more or less freezing risky features until the release Tuesday, so I'm going ahead and kicking this down the road. Feel free to object. :)

**Comment by alrevuelta** [comment]
The proposed feature in the *alternatives considered* above would be easy to add once the peer store refactor is finished https://github.com/status-im/nwaku/issues/622. Add a new metric (prometheus + rpc) showing the amount of inbound/outbound peers the node has.

This would add a requirement to store the `Direction` `Inbound|Outbound` of the connection in the `PeerStore` and add a simple `getPeersByDirection(Inbound|Outbound)` proc. Refer to https://github.com/status-im/nwaku/issues/622 for tracking this feature dependancies.

**Comment by alrevuelta** [comment]
As raised by @Menduist, a node can have multiple connections, some being incoming and others outgoing, so perhaps I need to modify this metric. But first I would like to understand this from a practical point of view in waku side. Do we currently support multiple connections with a given peer? If not do we plan to support this in the future?

Plan b would be to:
* Store the amount of incoming and outgoing connections.

The idea here is to know how well-connected a node is in terms of in/out connections.

**Comment by alrevuelta** [comment]
> Do we currently support multiple connections with a given peer?

Answering myself. I would say no, and this example should prove why. Let's say we have `peer0` and `peer1` and two different protocols `relay` and `lightpush`. `->` denotes succesful dial.
* `peer0`->`peer1` using `relay`. This will create one `outbound` connection in `peer0` and one `inbound` connection in `peer1`.
* `peer1`->`peer0` using `lightpush`. This does not creates any connections, since the connection is reused. I can confirm this by seeing `Reusing existing connection` in the nim-libp2p logs.

The same applies to WebSockets. Tried connecting `peer0`->`peer1` with `tcp` and then with `ws` and can also see `Reusing existing connection` for the second connection. So looks like its reused.

So would say that as it is a peer can't have multiple connections, since existing ones are reused for i) different protocols and ii) different transports.

**Comment by alrevuelta** [comment]
As explained by @Menduist [max connections](https://github.com/status-im/nim-libp2p/blob/unstable/libp2p/builders.nim#L170) per peer is currently set to [one](https://github.com/status-im/nim-libp2p/blob/fa5d102370cff4e68b47ac633153b22609b8aa41/libp2p/connmanager.nim#L31), but this might change in the future. I will make the default to 1 in our side. If at some point we want to allow multiple connections, we can revisit.

**Comment by alrevuelta** [comment]
@diegomrsantos is working in an [AutonatService](https://github.com/status-im/nim-libp2p/blob/e7bb48dd0b97ba1c65f5b268e093576edffec630/libp2p/services/autonatservice.nim) that tells us the `NetworkReachability` state of our node (if we are reachable or not). So instead of using the `dialMe` function we could use that service, which should be easier and more complete. Since the AutonatService is under development, hopefully our input/requirements can help in shaping it.

Some requirements on our side, with some implications on the service:
* We would like to have a metric that indicates: if the node is reachable, if the node is not reachable or if we simply can't know. Something like `Reachable`, `Notreachable`, `Unknown`.
* This metric should be updated over time, with a given frequency.
* The metric is to be used by node operators, to know if their node is properly set up. So something easy to look at, with just the 3 mentioned states.
* If we use AutonatService, we would need to:
  * Know when the `NetworkReachability` state changed. Which is already addressed with a handler. Then update our metric accordingly.
  * Configure how frequently it should be checked. We don't want to be constantly checking this, every few minutes should be fine. Perhaps with an `interval` field.
  * We don't have strict requirements on what `Reachable` means. If a few peers confirm it, we're good. No need to define a fancy strategy. Perhaps instead of `maxConfidence` we could have a `maxPeersToCheck` and a `minOkThreshold` so that every `interval` we randomly select `maxPeersToCheck` and if `minOkThreshold` flag our node as `Reachable`, then we are. Perhaps I would use 2/10, since some peers might not support it and other may not be reachable.
  * Its important that `Notreachable` means that we are indeed not reachable. Otherwise node operators will be confused. If in doubt, it should fallback to `Unknown`.

**Comment by alrevuelta** [comment]
https://github.com/status-im/nim-libp2p/pull/814 is getting close to be ready, but this feature is fixed until it is merged.
