### ISSUE TITLE
feat (rln-relay):  allow higher messaging rate using multiple valid registrations

### ISSUE THREAD

**Issue by staheri14** [waku-org/nwaku#1264]
### Problem
Waku-rln-relay protocol only accepts one valid rln credential for messaging in a given group. However, it is perceivable that a node wants to increase its messaging quota by using multiple valid credentials. This issue is to enable such a feature in the waku-rln-relay protocol. 

### Suggested solution
At a high level, the waku node should be able to accept multiple valid rln credentials and use them in a cyclic fashion so that the user benefits from his maximum messaging quota. 

### Additional context
Was raised in https://github.com/status-im/nwaku/issues/1238#issuecomment-1277936460

### Acceptance criteria
- [ ] A proper solution is devised and implemented in nim-waku
- [ ] the RFC gets updated as fits

**Comment by rymnc** [comment]
https://github.com/Rate-Limiting-Nullifier/rln-circuits-v2 allows this. This issue is blocked by -
- contract implementation required
- zerokit implementation required
