### ISSUE TITLE
feat(rln): How to securely store RLN credentials cross-client

### ISSUE THREAD

**Issue by s1fr0** [waku-org/nwaku#1278]
### Background
In 
- https://github.com/status-im/nwaku/issues/1021
- https://github.com/status-im/nwaku/issues/1238
- https://github.com/vacp2p/rfc/issues/543

is raised multiple times the question of standardizing the RLN credential format and securely persist it.

### Details
`nwaku`, `js-waku` and `go-waku` generates RLN credentials through `zerokit` FFI/WASM APIs.

While standardization of a format for RLN credentials can be pursued in https://github.com/vacp2p/rfc/issues/543 (a tentative solution was proposed [here](https://github.com/status-im/nwaku/issues/1238#issuecomment-1278114079)), their secure persistence and cross-client usage (e.g. decryption) is non-trivial.

As suggested [here](https://github.com/status-im/nwaku/issues/1021#issuecomment-1222081649), `nwaku` comes with a `nimbus` keystore implementation that allows to securely encrypt messages (in fact, *keys*) using a password/mnemonic sentence. However, to allow cross-client usage of encrypted credentials, the underlying employed primitives (`scrypt, pbkdf, sha256, aes-128-ctr`) should be ported/implemented in `js-waku` and `go-waku` too. 

On top of this, nimbus keystores don't seem to allow enough flexibility on fields structure to reach something similar to what  proposed [here](https://github.com/status-im/nwaku/issues/1238#issuecomment-1278114079) and come with primitives that should probably be replaced at least to provide 256 bits of security (I would personally use Argon2 + ChaChaPoly).

Given this, a possible solution could be to implement a WASM-friendly rust module that we can interface, similarly as zerokit, with FFI/WASM implementing all the logic on our custom standardized RLN credential format (most probably JSON with fields content encrypted), so that we avoid multiple implementations of the same crypto primitives.

Nevertheless, if implementation/usage of a browser extension is envisioned for js-rln in order to safely store credentials (e.g., [crypt-keeper](https://github.com/Rate-Limiting-Nullifier/crypt-keeper)), then we might opt for separate implementations in `nwaku` and `go-waku` of RLN credentials' field encryption, since both already support Noise primitives. In any case, import/export of credentials should be supported too by the browser extension and crypt-keeper doesn't seem to have such feature yet.

### Pro and cons
- **nimubs keystores**: ready in nwaku. Require implementations in go/js-waku, but primitives should be ready in libs. Credentials may not be compatible with all clients. Requires some refactor to add custom fields/metadata to credentials.
- **single rust module**: more effort for implementation. Reduces implementation mistakes. Credentials compatible with all implementations.  Possibility to add custom fields/metadata to credentials.
- **different implementations**: more effort, but in parallel. Credentials might not be compatible with all clients. Support for custom fields/metadata to credentials, but may be client-specific.

### Acceptance criteria
- [ ] Once RLN credential format is standardized, agree on the best solution for their secure storage, i.e. one among: - use nimbus keystore; - implement a single rust library; - have different implementations in each client.

@staheri14 @rymnc @fryorcraken @richard-ramos @oskarth

**Comment by richard-ramos** [comment]
I don't see an impediment in using an external module for writing/reading external credentials, but IMO the effort of implementing this idea should be compared against the effort of using existing libraries in each language that can be used for this (like it does in go, and nim after extracting it from nimbus)

In Prysm (an eth2 client), they are using https://github.com/wealdtech/go-eth2-wallet-encryptor-keystorev4 https://github.com/prysmaticlabs/prysm/blob/d077483577bc8fdc658940adf71d8d11dfa5949b/tools/keystores/main.go . 

For JS, Chainsafe implemented https://www.npmjs.com/package/@chainsafe/bls-keystore which is compatible with EIP2335 and used in Lodestar, and according to its description, it can be used on the browser.

--

in go-waku, while the chat2 example stores the credentials in plaintext (for compatibility across implementations), the wakunode is using go-ethereum keystore to write the credentials https://github.com/status-im/go-waku/blob/master/waku/rln-credentials.go#L50, encrypted with a password that can be passed via the `--key-password` flag. For reference, this is the go-ethereum implementation: https://github.com/ethereum/go-ethereum/tree/master/accounts/keystore

**Comment by richard-ramos** [comment]
Ah! this is because go-waku is not using at the moment EIP2335, but https://github.com/ethereum/wiki/wiki/Web3-Secret-Storage-Definition.  This should be implemented in nim by:
- https://github.com/status-im/nim-eth/blob/master/doc/keyfile.md
- https://github.com/status-im/nim-eth/tree/master/eth/keyfile

**Comment by richard-ramos** [comment]
In https://github.com/ethereum/go-ethereum/blob/master/accounts/keystore/testdata/v3_test_vector.json there are a couple of test vectors with their `password`. The expected result from decryption can be seen in the attribute`priv` of each test,

**Comment by richard-ramos** [comment]
> what really could make a difference is what libraries are available for js-waku and the output format of keyfiles' JSONs.

For JS, the following libraries are available, but would probably require some minor work for them to allow encrypting arbitrary data
- https://github.com/ethers-io/ethers.js/tree/master/packages/json-wallets
- https://github.com/web3/web3.js/tree/1.x/packages/web3-eth-accounts
- https://github.com/ethereumjs/ethereumjs-wallet

**Comment by richard-ramos** [comment]
> It seems that encrypted credentials returned by go-waku based on encryptDataV3 don't embed the `version` and `id` fields in the final JSON and this choice doesn't follow the standard https://github.com/ethereum/wiki/wiki/Web3-Secret-Storage-Definition.

The reason why go-waku does not add `version` and `id` is because I'm not using the function [`EncryptKey`](https://github.com/ethereum/go-ethereum/blob/b196ad1c165ecd6c9edaca520e7161a58e50eb06/accounts/keystore/passphrase.go#L184-L197) which adds these attributes and the `address`. It should be trivial to do the change in go-waku so the encrypted file matches the standard.

**Comment by fryorcraken** [comment]
I agree with @richard-ramos's comments above. Considering what we are trying to achieve, I am not convinced it is worth using a common library (imported in wasm) across implementations. If we can find an existing standard (e.g. EIP-2335) that fits the purpose then it would make sense.

I see EIP-2335 is BLS specific. Would it makes sense to propose an EIP extension to use it for zk credentials usage too?
Has crypt-keeper defined an interface to export/import credentials?

**Comment by fryorcraken** [comment]
Also note that for the browser, https://github.com/vacp2p/zerokit/pull/56#event-7496507160 enables deterministic generation of credentials from an ethereum wallet signature. AFAIK, this strategy is used by several zk projects (e.g. aztec network, zksync).

This enables delegation of the storing of credentials to the Ethereum Wallet. The only missing part being the membership id: I assume this can be retrieve by finding the transaction that inserted the member?

**Comment by fryorcraken** [comment]
> Finding commitments among leaves...

Wouldn't it be easier to just find the matching Ethereum transaction sent to the contract from the loaded wallet and look at the receipt of said transaction?
