### ISSUE TITLE
store: limit the max number of content topics per history query

### ISSUE THREAD

**Issue by LNSD** [waku-org/nwaku#1292]
## Context/background
There are currently history queries with an arbitrarily high number of `contentFilters` (multiple content topic filters). Some of those queries are around 150 content topics per query.

This has a significant impact on the query processing time. Not limiting the number of content topics is also a weak point (even though we are limiting the query buffer).

## Acceptance criteria
- [x] Limit the maximum number of content filters to 5 (or 10).
- [x] Return a _bad request_ error code if the number of topics exceeds the limit.

**Comment by jm-clius** [comment]
Removed from 0.13.0 scope and added to 0.14.0

**Comment by jm-clius** [comment]
Some work in https://github.com/waku-org/nwaku/issues/1159 required before this can be done.

**Comment by LNSD** [comment]
> Some work in #1159 required before this can be done.

Specifying and implementing the new Waku store protocol will take some time. 

We have implemented an intermediate limit to mitigate DoS caused by queries with a content topics list greater than 10. This will be perceived by the Waku store v2 client as an `INVALID_CURSOR` error.
