### ISSUE TITLE
chore(RLN): decouple WakuConf (chat2 or Wakunode) from RLN `mount` procedure

### ISSUE THREAD

**Issue by s1fr0** [waku-org/nwaku#1294]
### Problem
To ease code refactoring in https://github.com/status-im/nwaku/pull/1285#discussion_r1002546366 is proposed to decouple Waku configuration files from the RLN `mount` procedure and pass the relevant fields as function parameters instead.

In the same or a related PR, it can be implemented the move of all RLN-relay specific fields of WakuConf (either chat2 or Wakunode2) under the RLN compilation flag(s), so that those fields are enabled only when RLN is enabled (see comment in https://github.com/status-im/nwaku/pull/1285#discussion_r1002546823).

### Acceptance criteria
- [ ] Implement the above changes

**Comment by LNSD** [comment]
This work unit is related to #1222 (if not overlapping)
