### ISSUE TITLE
chore(peer-exchange): connection establishment

### ISSUE THREAD

**Issue by kaiserd** [waku-org/nwaku#1301]
### Background

Currently, Waku peer exchange connection establishment is handled as follows,
assuming Peer A sends a request to Peer B.

* Peer A  dials Peer B
* Peer B processes Peer A's request
* Peer B retrieves px-peers (could be on-demand)
* Peer B dials Peer A
* Peer A processes Peer B's response

This, was modeled after filter, where Peer B has time to retrieve px-peers when getting a request.
However, the current peer exchange implementation retrieves px-peers asynchronously via discv5 (there is no on-demand option),
and should have cached px-peers available to respond immediately.

### Solution

Establish connections as follow:

* Peer A  dials Peer B
* Peer B processes Peer A's request
* Peer B retrieves px-peers from its local cache, and immediately responds on the same connection

This is especially helpful for `js-waku` clients, where establishing a connection from B to A might be a problem.

### Acceptance criteria

* [ ] updated Waku peer exchange to the above described connection establishment

Note: The cache and asynchronous px-peer retrieval are already implemented,
and the responding peer already retrieved px-peers from its local cache.
This issue is only about the connection establishment.

cc @jm-clius 
Thanks to @richard-ramos for pointing this out!

**Comment by jm-clius** [comment]
@kaiserd afaict neither party explicitly disconnects after the initial request? In that case (as with filter) the step where `Peer B dials Peer A` to respond would in practice just re-use the existing connection, even if it's a separate call to `dial`. We can double check that this works as expected, but I think it's the most reasonable way to do things.

**Comment by jm-clius** [comment]
@kaiserd I think we can close this issue then, or would you like to setup a test of some kind first to ensure connections are re-used when responding immediately?

**Comment by chair28980** [comment]
Closing issue per suggestion and issue has lived in icebox for significant time.
