### ISSUE TITLE
chore: use npx to run ganache

### ISSUE THREAD

**Issue by s1fr0** [waku-org/nwaku#1356]
### Background
At the moment ganache node package is installed and executed using `node` (this is to avoid to deal with retrieving child processes ID), then is uninstalled. It should be possible to use directly `npx ganache` to run the daemon without installing/uninstalling the package and without leaving cache in build.

This issue is to track the switch from current implementation to usage of the cleaner npx.

### Acceptance criteria
- [x] Use npx and avoid node package installation

**Comment by rymnc** [comment]
Addressed in #1465. Will close this upon its merge
