### ISSUE TITLE
feat: DappNode ENS subdomain setup

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/nwaku#1360]
### Context

A community contributor is preparing a nwaku package for DappNode.

To publish nwaku on DappNode and get a green tick in their UI, we need to ask DappNode for an ENS subdomain.
Then, when deploying a new version of nwaku, a mainnet transaction needs to be done.

We need to understand the security assumptions of this setup so we can decide whether a multi-sig is needed to control the account that does the update transaction.

I was not able to find relevant information in https://docs.dappnode.io/ so we have to go with the information below:

Quoted is information that @alrevuelta got from Eduardo (DappNode).

>  this dappnode ens domain is to sign nwaku docker packages that are published to their store. 

> -They control the domain dnp.dappnode.eth

> -The domain they mint nwaku.dnp.dappnode.eth still belongs to them, but allows a given EOA to publish updates (signing onchain tx updating the reference to the docker package).
> -Eduardo highlighted EOA account, since its not possible to integrate it with a smart contract. There is a standard working with gnosis safe, but they don't have it integrated nor plan to do it.

I did some investigation from looking at [ipfs.dnp.dappnode.eth](https://app.ens.domains/name/ipfs.dnp.dappnode.eth/details):

The subdomains points to a smart contract, e.g [0x9dc9dc601f8f177ab558bcabde71786f1ea84091](https://etherscan.io/address/0x9dc9dc601f8f177ab558bcabde71786f1ea84091#code)

Transaction to the smart contract needs to happen to publish a new version, e.g. [0x16e614413f76eb100cd33c4c7e84f1f8e0fcde3e0466d7b45163d5f78c16d9e4](https://etherscan.io/tx/0x16e614413f76eb100cd33c4c7e84f1f8e0fcde3e0466d7b45163d5f78c16d9e4)

Which updates an ipfs address (e..g `/ipfs/QmavkPwW69bT8bMUpurTyEGPXG5vTggqWbd62AQiDJqd8a` ) I guess location of the new binary.

My guess is that the account that is allowed to update the ipfs link is the only account we need to care about. This is the one that needs to be an EOA.

Remaining questions:
1. Does the EOA to update IPFS link to latest version has any other permission?
2. What happens if the EOA's keys are lost or compromised? Or owner goes rogue? Can we can ask DappNode to setup a new EOA? I am guessing that worst case scenario, a new dappnode contract can be deployed and have the subdomain point to it.

### Suggested solution

If:
a. The EOA only has the right to update the dappnode _contract_ to which `nwaku.public.dappnode.eth` points to
b. DappNode can reset/update/change the EOA if it is compromised/lost/etc

Then I recommend we do a simple setup where the EOA can be handled by @jm-clius or someone he delegates it to without having to worry about setting up a multisig as loss of EOA control would involve a social recovery by reaching out to DappNode.

We also need to setup an offiical channel to DappNode that involves several Waku/Status CC for redundancy (e.g @oskarth @corpetty @jm-clius and myself @fryorcraken).

Another alternative would be to let the package maintainer own the EOA. Having a Waku team member own the EOA would also make it easier for expensing the transaction fee.

## Note

I chatted with the package maintainer and he can output the transaction to sign as part of the release CI so there is no additional cost/setup whether he or we control the EOA.

**Comment by alrevuelta** [comment]
Quick update on this:
* nwaku team now holds an ethereum address that has been granted permissions to sign `nwaku` package upgrades (see [tx](https://etherscan.io/tx/0x46b731d122ab75ab3616941bace1c01cea19971030fb6f37a0781ccc651103f4) giving us the rights, thanks to dappnode team).
* this ethereum address was also assigned to [nwaku dappnode package](https://github.com/rndlabs/dappnodepackage-nwaku/pull/8), meaning that every time something merges to master, we get in CI a link to sign a tx with the new release ([example](https://dappnode.github.io/sdk-publish/?r=nwaku.dnp.dappnode.eth&v=0.1.1&h=%2Fipfs%2FQmQ6BExsGRP97UVQ4zJsVXCVaJonKTH8Z9D1nZkefUysb8) do not sign this!)
* note that nwaku is already verified ✅ and published in dappnode. note also that this first release had to be done by dappnode team, but from now on we are good to go for next releases.

Release process nwaku->dappnode should be easy as everything is automated (and if we dont introduce backward incompatible changes like cli flags etc). Process:
* Bump nwaku release (i.e. v0.14.0 to v0.15.0) in [this repo](https://github.com/rndlabs/dappnodepackage-nwaku) and dappnode-version. Just few lines.
* Merge to master and using the link (explained above) sign that tx (from our ethereum account)
* Now the new nwaku release is published in dappnode!

Closing this as this was related to "ens" domain which is already done.

**Comment by mfw78** [comment]
> Release process nwaku->dappnode should be easy as everything is automated (and if we dont introduce backward incompatible changes like cli flags etc). Process:
> 
>     * Bump nwaku release (i.e. v0.14.0 to v0.15.0) in [this repo](https://github.com/rndlabs/dappnodepackage-nwaku) and dappnode-version. Just few lines.
> 
>     * Merge to master and using the link (explained above) sign that tx (from our ethereum account). This is the only step where nwaku team is needed.
> 
>     * Now the new nwaku release is published in dappnode!

FYI, things are even a little more automated than this. In the repo's GitHub actions (see [here](https://raw.githubusercontent.com/rndlabs/dappnodepackage-nwaku/9b426a77cc9148bc79939d43e0d2ce94c18c8413/.github/workflows/auto_check.yml0) this is a cron job that polls every 4 hours to see if there is a new upstream (v0.14.0 -> v0.15.0). When it detects a change upstream, it will automatically create a PR that will do the version bumping to the relevant files.

It should just be a matter then of a sanity check, then merge the PR, at which time then the aforementioned transaction details are generated for publishing to the Dappstore!

**Comment by alrevuelta** [comment]
@mfw78 ow thanks great stuff. Then in the upcoming v0.15.0 we will see if that happens!
