### ISSUE TITLE
chore(rln-relay): Separation of group registration from rln-relay mounting process

### ISSUE THREAD

**Issue by staheri14** [waku-org/nwaku#1369]
### Background
In line with https://github.com/status-im/nwaku/issues/1370

RLN membership group registration is an act to yield rln credentials. This input is then required to activate rln-relay protocol. 
Rln-relay mounting process should not be aware or tied to the registration process, and these two logics are best to be separated.

### Details
The mountDynamicRlnRelay proc signature should be updated to only accept rln credentials, and no further inputs related to the on-chain rln registration.

**Comment by rymnc** [comment]
Addressed in #1496
