### ISSUE TITLE
feat(RLN): load zerokit RLN as static library

### ISSUE THREAD

**Issue by s1fr0** [waku-org/nwaku#1380]
### Problem
At the moment zerokit RLN is loaded by the waku-rln-relay module as dynamic library. 
This creates path issues similar to https://github.com/status-im/nwaku/issues/1372 (i.e. wakunode has to be loaded from root folder). Furthermore, from a Waku product perspective, [it is required](https://github.com/status-im/nwaku/issues/1372#issuecomment-1313921001) that zerokit RLN is loaded as static library instead.

### Acceptance criteria

- [x] Support compiling Zerokit RLN in nwaku as a static library
- [x] Add the required compilation flags to the nwaku build scripts (e.g., Makefile)
- [x] Update the Jenkins CI and GH Actions pipelines accordingly
- [x] Update the Dockerfile accordingly (cc @jakubgs)

**Comment by LNSD** [comment]
Added the issue tentatively to the next release, v0.14.0.
