### ISSUE TITLE
bug: wakunode2 does not exit cleanly (0) with SIGINT

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/nwaku#1392]
### Problem

In js-waku CI, we start `wakunode2` and stop them using `SIGINT`.

In normal process, we expect the return code to be `0`.

I have noticed the return code being `1` or `1` since nwaku `v0.13.0`

### Impact

Low impact but time wasting as it's a red herring when investigate js-waku CI failures.

### To reproduce

Using NodeJS 16

```
// git clone js-waku
git checkout chore/libp2p-0.40.0
npm i
npm run build # Run again if there is an error
cd packages/tests
mocha tests/wait_for_remote_peer.node.spec.ts --grep ^Wait for remote peer Store - dialed first$
```

### Expected behavior

If the nwaku node does not encounter any error then exit code should be `0`.

### Screenshots/logs

[nwaku_Wait_for_remote_peer_Store_-_dialed_first.log](https://github.com/status-im/nwaku/files/10027152/nwaku_Wait_for_remote_peer_Store_-_dialed_first.log)

js-waku test harness logs:

```
  waku:nwaku nwaku 674029 getting SIGINT at 1:09:14 pm +1s
  waku:nwaku nwaku 674029 interrupted: true +0ms
  waku:nwaku nwaku args: --listen-address=127.0.0.1 --nat=none --relay=false --rpc=true --rpc-admin=true --websocket-support=true --store-message-db-url=sqlite://:memory: --log-level=TRACE --tcp-port=8023 --rpc-port=8022 --websocket-port=8024 --store=true --lightpush=false --filter=false +10ms
  waku:nwaku nwaku 674033 started at 1:09:14 pm +13ms
  waku:nwaku Waiting to see 'Node setup complete' in nwaku logs +0ms
  waku:nwaku nwaku node has been started +12ms
  waku:nwaku RPC Query:  get_waku_v2_debug_v1_info [] +0ms
  waku:nwaku RPC Response:  {"jsonrpc":"2.0","id":1,"result":{"listenAddresses":["/ip4/127.0.0.1/tcp/8023/p2p/16Uiu2HAmP9WtnQdTjuYMVbHVvhbmB6JgaUbkLy2HbQ7L5VQxnQoT","/ip4/127.0.0.1/tcp/8024/ws/p2p/16Uiu2HAmP9WtnQdTjuYMVbHVvhbmB6JgaUbkLy2HbQ7L5VQxnQoT"],"enrUri":"enr:-KO4QIZLJzOwlF8FVZRf6m_flp-iU-Uy3OltR4pb6tX7F5AoC2uOf5puUX2QcuX-s4PoEAdForvFa67Iz6RtRAy59cgBgmlkgnY0gmlwhH8AAAGKbXVsdGlhZGRyc4wACgR_AAABBh9Y3QOJc2VjcDI1NmsxoQOb46rAJctIKHd3Ze20VM6sy82fn0xJv4SRXTS17rAFmoN0Y3CCH1eFd2FrdTIC"}} +1ms
  waku:waku Waku node created 12D3KooWRWviBGYEps2MoAau827JkfhTWuPveWkr5ecizLaXfC8v relay: false, store: true, light push: true, filter: true +1s
  waku:nwaku nwaku 674029 process exited with 1 at 1:09:14 pm +33ms #<--- THIS
```

### nwaku version/commit hash

`v0.13.0`

**Comment by fryorcraken** [comment]
Note that in CI, the exit code is `2`:

```
    [31m  20) Passing an array[0m
2022-11-17T02:02:15.707Z waku:nwaku nwaku 3092 getting SIGINT at 2:02:15 AM
2022-11-17T02:02:15.707Z waku:nwaku nwaku 3092 interrupted: false
2022-11-17T02:02:15.708Z waku:nwaku nwaku args: --listen-address=127.0.0.1 --nat=none --relay=true --rpc=true --rpc-admin=true --websocket-support=true --store-message-db-url=sqlite://:memory: --log-level=TRACE --tcp-port=8001 --rpc-port=8000 --websocket-port=8002  =0
2022-11-17T02:02:15.716Z waku:nwaku nwaku 3102 started at 2:02:15 AM
2022-11-17T02:02:15.716Z waku:nwaku Waiting to see 'Node setup complete' in nwaku logs
2022-11-17T02:02:15.763Z waku:nwaku nwaku 3102 process exited with 2 at 2:02:15 AM
```
[nwaku_Waku_Dial_[node_only]_Bootstrap_Passing_an_array.log](https://github.com/status-im/nwaku/files/10027192/nwaku_Waku_Dial_.node_only._Bootstrap_Passing_an_array.log)

**Comment by alrevuelta** [comment]
Thanks for reporting it. Not sure I understand how to reproduce it. I guess you mean something like the following?

```console
make wakunode2
./build/wakunode2
```

Then `control-C`
```
INF 2022-11-17 15:34:22.842+01:00 Shutting down after receiving SIGINT       topics="wakunode" tid=5082081 file=wakunode2.nim:696
WRN 2022-11-17 15:34:22.844+01:00 Stopping gossipsub without starting it     topics="libp2p gossipsub" tid=5082081 file=gossipsub.nim:616
/Users/xxx/Github/nwaku/vendor/nimbus-build-system/vendor/Nim/lib/pure/collections/deques.nim(98) popFirst
Error: unhandled exception: Empty deque. [IndexDefect]
```

And you are expecting `$?` to be `0` instead of `1`?
```console
$ echo $?
1
```

**Comment by fryorcraken** [comment]
Note that I was able to resolve the `exit 2` in the CI by switching from in memory sqlite to the no-db(?) memory for Waku store.
So I am guessing exit 2 was due to lack of memory space on the GitHub Action CI machines.

**Comment by fryorcraken** [comment]
> And you are expecting $? to be 0 instead of 1?

Yes, your reproduction is correct.

some info https://www.man7.org/linux/man-pages/man3/exit.3.html

In case of "normal" (no error) running of a program, `0` is expected.

If the program terminates due to an error, then `1` or sometimes any non-zero value is expected.

In this case, `wakunode2` successfully started and run. I then send `SIGINT` which is an appropriate way to terminate a program.
The exit code should then be `0`.

My use case: I track exit code of nwaku to understand if test failure is due to an issue with nwaku or an issue with the functional test. If nwaku returns `1` when it's actually fine it's a waste of time because I first need to check nwaku logs to realize everything is fine there.

Do note that for any kind of devops, it is also important because you don't want monitoring tools reporting an error because nwaku returns `1` when you do a normal node stop or restart.

**Comment by rymnc** [comment]
Can confirm that #1416 fixes this. js-waku can use v0.14.0 for the fixed nwaku binary (Jan 16). Can we close this, @fryorcraken?

**Comment by jm-clius** [comment]
Fixed in https://github.com/waku-org/nwaku/releases/tag/v0.14.0
