### ISSUE TITLE
chore: logging for Waku e2e message traceability

### ISSUE THREAD

**Issue by jm-clius** [waku-org/nwaku#1394]
### Background

This forms part of a series of issues raised as output of the recent Status client offsite.

Message delivery reliability is a core concern for all Waku applications. One of the main debugging challenges identified during the client offsite, is the difficulty of finding _where_ in the Waku network a message has gone missing.

## Suggestion

A simple way of easing this debugging process, is to log the message IDs (and perhaps peer ID of routing origin) at various points in the processing and routing chains. This would result in a flood of logs, so should only be enabled in controlled, dogfooding/debug environments. Work has already started within the Status client apps and go-waku client.

This issue tracks work related to adding similar logging in nwaku.

**Comment by Daimakaimura** [comment]
This is becoming a blocker for us (DS/Testing Team) as we have no way to retrieve arrival times, hence no way to calculate latencies, etc. Do you have an ETA for this?

**Comment by jm-clius** [comment]
Thanks, @Daimakaimura. So far this has not been prioritised, but should not be a difficult add and is important to do if a blocker for DS. Could you confirm your requirements here: would logging
- a hash of the message
- timestamp of arrival
cover your use case? Or what metadata fields would you require?

Quick investigation shows that logging message ID and peer ID of origin will be a bit more involved.

**Comment by Daimakaimura** [comment]
Thanks @jm-clius, yes that would be the minimum requirements: hash of the message and arrival TS. With that we could already calculate latencies per message, per topic, and per node. The ID of the sender would allow us to reconstruct the full paths of every message on the network but this is not included on our first milestone.

**Comment by Daimakaimura** [comment]
Regarding on recovering it from the store or the logs, it appears that it would be better to recover it from the logs so we could also test the overhead of the Store (if needed in the future).

**Comment by jm-clius** [comment]
Proposed trace logs added in https://github.com/waku-org/nwaku/pull/1526 @Daimakaimura would appreciate feedback if that will cover your needs.

**Comment by Daimakaimura** [comment]
> Proposed trace logs added in #1526 @Daimakaimura would appreciate feedback if that will cover your needs.

Thank you so much @jm-clius I ll have a look today or tomorrow and get back to you.

**Comment by Daimakaimura** [comment]
@jm-clius I checked the PR Draft and adding those 2 messages to the logs should be okay for us to calculate delays. Regarding the volume in the logs, indeed that could be also another issue and probably the best option would likely to have a flag to enable only these messages (independently of the log level).

**Comment by jm-clius** [comment]
Closing as logging has been added.
