### ISSUE TITLE
peer-exchange: js-waku <> nwaku interop

### ISSUE THREAD

**Issue by danisharora099** [waku-org/nwaku#1408]
### Problem
When a js-waku node tries to connect to an nwaku node with peer-exchange, it receives an empty array for available peers.
The nwaku node here is already connected with another nwaku node using discv5Discovery which was confirmed by logs. 

Another thing noted was: the nwaku node tries to open a new connection with the js-waku node, where it should just be reusing the already opened duplex connection. (attached logs)

Possible interop bug

### Impact
Unsure.

### To reproduce
1. Go to the js-waku repo
2. Check out to branch `danisharora/feat-peer-exchange`
3. Run `yarn test`
4. Check `packages/tests/logs/` for the `peer-exchange` logs for the nwaku node

You can also spin the nwaku nodes manually with CLI and then feed the multiaddr to the JS test code when dialing

### Expected behavior
When a js-waku node connects to an nwaku node (which is connected to other nodes with discv5), it should return the ENR[] for the connected available nodes.

#### Nwaku logs
[nwaku_Peer_Exchange_Node_Queries_successfully.log](https://github.com/status-im/nwaku/files/10072687/nwaku_Peer_Exchange_Node_Queries_successfully.log)

#### js-waku & libp2p logs: 
[jswaku-libp2p-peer-exchange.log](https://github.com/status-im/nwaku/files/10072693/jswaku-libp2p-peer-exchange.log)

### nwaku version/commit hash
State the version of `nwaku` where you've encountered the bug or, if built off a specific commit, the relevant commit hash. You can check the version by running `./wakunode2 --version`.
- v0.13.0

### Additional context
- the nwaku node here tries to dial back with `waku-relay` everytime even when relay isn't requested (also confirmed for other protocols like filter)
- the nwaku node here tries to open a new connection for `peer-exchange` with the js-waku node (which it rejects) while it should reuse the existing already opened connection 
- nwaku nodes when spun individually and made to connect with discv5 and peer-exchange work as expected
   - logs: 
```INF 2022-11-22 21:19:35.158+05:30 Successfully discovered nodes              topics="waku discv5" tid=210726 file=waku_discv5.nim:99 count=1
INF 2022-11-22 21:19:35.158+05:30 Discovered px peers via discv5             topics="waku peer_exchange" tid=210726 file=protocol.nim:130 count=1
INF 2022-11-22 21:19:35.452+05:30 Successfully discovered nodes              topics="waku discv5" tid=210726 file=waku_discv5.nim:99 count=1
INF 2022-11-22 21:19:40.454+05:30 Successfully discovered nodes              topics="waku discv5" tid=210726 file=waku_discv5.nim:99 count=1
INF 2022-11-22 21:19:45.456+05:30 Successfully discovered nodes              topics="waku discv5" tid=210726 file=waku_discv5.nim:99 count=1
INF 2022-11-22 21:19:50.459+05:30 Successfully discovered nodes              topics="waku discv5" tid=210726 file=waku_discv5.nim:99 count=1
DBG 2022-11-22 21:19:55.051+05:30 Accepted an incoming connection            topics="libp2p switch" tid=210726 file=switch.nim:249 conn=:637cefa3f1e970958f79d234
DBG 2022-11-22 21:19:55.052+05:30 About to accept incoming connection        topics="libp2p switch" tid=210726 file=switch.nim:219
DBG 2022-11-22 21:19:55.101+05:30 created new pubsub peer                    topics="libp2p pubsub" tid=210726 file=pubsub.nim:300 peerId=12D*XmPbUc
DBG 2022-11-22 21:19:55.114+05:30 decodeMsg: decoded identify                topics="libp2p identify" tid=210726 file=identify.nim:150 pubkey=some(e...0439)) addresses= protocols=/ipfs/id/1.0.0,/ipfs/id/push/1.0.0,/ipfs/ping/1.0.0,/libp2p/circuit/relay/0.1.0,/libp2p/fetch/0.0.1,/vac/waku/filter/2.0.0-beta1 observable_address=/ip4/127.0.0.1/tcp/8005/ws/p2p/16Uiu2HAm3y3VExKYgJXcWGdGey1q96ta4BCLNxAgKN7xKNWS7VQ1 proto_version=ipfs/0.1.0 agent_version=js-waku signedPeerRecord=None
INF 2022-11-22 21:19:55.128+05:30 Dialing peer from manager                  topics="waku node peer_manager" tid=210726 file=peer_manager.nim:61 wireAddr=@[] peerId=12D*XmPbUc
DBG 2022-11-22 21:19:55.130+05:30 Could not establish send connection        topics="libp2p pubsubpeer" tid=210726 file=pubsubpeer.nim:208 msg="Unable to select sub-protocol @[\"/vac/waku/relay/2.0.0\", \"/meshsub/1.1.0\", \"/meshsub/1.0.0\"]"
DBG 2022-11-22 21:19:55.138+05:30 Error dialing                              topics="libp2p dialer" tid=210726 file=dialer.nim:313 conn=12D*XmPbUc:637cefa3f1e970958f79d235 msg="Unable to select sub-protocol @[\"/vac/waku/peer-exchange/2.0.0-alpha1\"]"
DBG 2022-11-22 21:19:55.140+05:30 unsubscribing pubsub peer                  topics="libp2p pubsub" tid=210726 file=pubsub.nim:137 peerId=12D*XmPbUc
DBG 2022-11-22 21:19:55.140+05:30 Error while reading message from secure connection, closing. topics="libp2p secure" tid=210726 file=secure.nim:167 error=AsyncStreamReadError message="Read stream failed, originated from [TransportUseClosedError] Attempt to read data from closed stream" connection=12D*XmPbUc:637cefa3f1e970958f79d235
DBG 2022-11-22 21:19:55.140+05:30 Unexpected exception in mplex read loop    topics="libp2p mplex" tid=210726 file=mplex.nim:193 m=12D*XmPbUc:637cefa3f1e970958f79d235 msg="Read stream failed, originated from [TransportUseClosedError] Attempt to read data from closed stream"
DBG 2022-11-22 21:19:55.140+05:30 Dialing remote peer failed                 topics="waku node peer_manager" tid=210726 file=peer_manager.nim:83 msg="Unable to select sub-protocol @[\"/vac/waku/peer-exchange/2.0.0-alpha1\"]"
INF 2022-11-22 21:19:55.462+05:30 Successfully discovered nodes              topics="waku discv5" tid=210726 file=waku_discv5.nim:99 count=1
INF 2022-11-22 21:20:00.464+05:30 Successfully discovered nodes              topics="waku discv5" tid=210726 file=waku_discv5.nim:99 count=1
INF 2022-11-22 21:20:05.139+05:30 Total connections initiated                topics="waku node metrics" tid=210726 file=waku_metrics.nim:61 count=0.0
```

**Comment by danisharora099** [comment]
>   await waku.dial(ma, [Protocols.Filter, Protocols.LightPush]);

One thing that I can notice is that you're dialing with `FIlter` and `LightPush` and not `PeerExchange`.
Can you try this instead:
`  await waku.dial(ma, [Protocols.PeerExchange]);`

**Comment by danisharora099** [comment]
Great news! 

After a discussion with @kaiserd, it was deduced that the current implementation of Peer Exchange requires dialing back to the client, and js-waku needed a request handler to be able to support that. 

This also is in some form inconsistent with our description of referring to Peer Exchange as a "request-response" protocol. This also is more similar to the Filter protocol (which is subscribing in nature) versus LightPush (which is a request-response protocol).

@kaiserd please feel free to add if you think there's anything else to mention :)

**Comment by danisharora099** [comment]
Upon checking locally, this unfortunately still does not work for me.
 
I can now receive a response correctly but still receiving an empty response (`Uint8ArrayList { bufs: [], length: 0 }`) with an `ENR cache empty` in the nwaku logs attached below: 
  
[nwaku_node1.log](https://github.com/waku-org/js-waku/files/10091777/nwaku_node1.log)
[nwaku_node2.log](https://github.com/waku-org/js-waku/files/10091781/nwaku_node2.log)
[nwaku_node3.log](https://github.com/waku-org/js-waku/files/10091784/nwaku_node3.log)

Node 1 here is run with `peer-exchange=true` while Node 2 and Node 3 are connected to it using `discv5Discovery` (as can be seen in code for the setup I'm running: https://github.com/waku-org/js-waku/pull/1038)

**Comment by danisharora099** [comment]
Upon the upgrade of nwaku to 0.14, this has now been fixed and works as expected! 🎉

**Comment by fryorcraken** [comment]
> Note:
> 
>     1. Nwaku's `--ports-shift` does not work in `nwaku.ts`. For instane, It is not taken into consideration when retrieving a node's mutltiaddress via rpc.
> 
>     2. The `udp` port is not automatically shifted when starting two nwaku instances from within js-waku tests. This makes discv5 fail to start on one of then nodes.
> 
> 
> Afaict, both 1) and 2) make it necessary to use `--discv5-udp-port:` as a manual arg.
> 
> Still, discv5 does not work between nodes started from within js-waku tests. I'll continue investigating.

This is how we handle nwaku's port allocation in js-waku test harness:

https://github.com/waku-org/js-waku/blob/a8ab53a6c5213e43c63e3ef284aef3eb3cb2d983/packages/tests/src/nwaku.ts

The correct way forward is to also do that for the discv5 udp port.

Ref: https://github.com/waku-org/js-waku/pull/1027#discussion_r1033032518

**Comment by fryorcraken** [comment]
> Confirmed! I added a `onRequest` handler to js-waku peer-exchagne, which fixed the issue. With this `nwaku` can dial peer-exchange and send the response to `js-waku`.
> 
> ~(I tried to push a draft PR to js-waku for illustration, but I do not have push rights @D4nte )~ done: [waku-org/js-waku#1037](https://github.com/waku-org/js-waku/pull/1037)

js-waku's light push implementation does not have a request handler either but the handling of the response works fine with nwaku, do we know why?

**Comment by fryorcraken** [comment]
> This also is in some form inconsistent with our description of referring to `PeerExchange` as a "request-response" protocol. This also is more similar to the `Filter` protocol (which is subscription/event-based in nature) versus `LightPush` (which is a request-response protocol).

Is Peer Exchange more like Filter because it may send a response _later_ if no discv5 peers are cached at request time?

**Comment by fryorcraken** [comment]
@kaiserd more thoughts on the matter.

By having a handler on the requestor side, I believe we are potentially opening to attacks where anyone could send a response to a remote node to inject them with peers (ie sybil attack).

From an implementation POV, it means that most likely the requestor needs to track to what nodes did it send requests and only accept response from said nodes. Maybe something worth mentioning in the RFC.

Another strategy, maybe better, would be to have a request id on the message and same id in the response.
The requestor should expect only one response per request so that it can also prevent a peer that the requestor previously used to send many response and attempt again, to inject peers.
