### ISSUE TITLE
chore(networking): too many failed dials, improve strategy

### ISSUE THREAD

**Issue by alrevuelta** [waku-org/nwaku#1414]
### Background
We can observe both in the [logs](https://kibana.infra.status.im/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-7d,to:now))&_a=(columns:!(message,severity),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:ffcc22b0-0116-11ed-9719-cdd3b483481c,key:fleet,negate:!f,params:!(status.prod),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(fleet:status.prod)))))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:ffcc22b0-0116-11ed-9719-cdd3b483481c,key:severity,negate:!f,params:(query:6),type:phrase),query:(match_phrase:(severity:6))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:ffcc22b0-0116-11ed-9719-cdd3b483481c,key:logsource,negate:!f,params:(query:node-01.do-ams3.status.prod),type:phrase),query:(match_phrase:(logsource:node-01.do-ams3.status.prod)))),index:ffcc22b0-0116-11ed-9719-cdd3b483481c,interval:auto,query:(language:kuery,query:'%22Dialing%20failed%22'),sort:!(!('@timestamp',desc)))) and in [grafana](https://grafana.infra.status.im/d/qrp_ZCTGz/nim-waku-v2?orgId=1&var-host=.%2A&var-fleet=status.prod&var-dc=ac-cn-hongkong-c&from=now-6h&to=now&viewPanel=7&refresh=30s) that we have tons of failed dials. Looking into the logs, we can see that some peers like [this one](https://kibana.infra.status.im/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-11-23T14:00:00.000Z',to:'2022-11-23T17:00:00.000Z'))&_a=(columns:!(message,severity),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:ffcc22b0-0116-11ed-9719-cdd3b483481c,key:fleet,negate:!f,params:!(status.prod),type:phrases),query:(bool:(minimum_should_match:1,should:!((match_phrase:(fleet:status.prod)))))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:ffcc22b0-0116-11ed-9719-cdd3b483481c,key:severity,negate:!f,params:(query:6),type:phrase),query:(match_phrase:(severity:6))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:ffcc22b0-0116-11ed-9719-cdd3b483481c,key:logsource,negate:!f,params:(query:node-01.do-ams3.status.prod),type:phrase),query:(match_phrase:(logsource:node-01.do-ams3.status.prod)))),index:ffcc22b0-0116-11ed-9719-cdd3b483481c,interval:auto,query:(language:kuery,query:'%2216Uiu2HAkwBp8T6G77kQXSNMnxgaMky1JeyML5yqoTHRM8dbeCBNb%22%20AND%20%22Dialing%20failed%22'),sort:!(!('@timestamp',desc)))) are clearly not reachable, and we are constantly dialing it. In some cases up to twice per minute.

<img width="825" alt="image" src="https://user-images.githubusercontent.com/8811422/203795474-22b9840e-fcd4-49cd-9159-310170481a72.png">

As seen [here](https://github.com/waku-org/nwaku/blob/master/waku/v2/node/waku_node.nim#L873-L889), we just skip dialing peers that are already connected (for obvious reasons) but there is no logic to avoid constantly dialing unreachable peers. Since we just wait `sleepAsync(5.seconds)` this is a waste of resources, because we are dialing all the time to these peers.

One option could be to use similar logic to the one in [reconnectPeers](https://github.com/waku-org/nwaku/blob/43fd11b4dc0e4ea108ae8303c9befdbe70a7d1df/waku/v2/node/peer_manager/peer_manager.nim#L198) so that we avoid trying to dial a peer if it `CannotConnect`. Since this implies semi-blacklisting a peer, we should reset this at some point so that we attempt to dial them in the future, but not that often.

### Acceptance criteria
* In discv5 loop, check if the peer errored in the past and avoid dialing it if it couldn't be reached.
* Add a mechanism to reset this, so that we don't end up blacklisting the peer forever.

**Comment by rymnc** [comment]
Maybe an exponential back off strategy would be good here?

**Comment by alrevuelta** [comment]
Moved to release 0.14.0

**Comment by alrevuelta** [comment]
Nimbus has an interesting feature to solve this. They use a seenTable where they add "seen peers" to avoid:
* don't instantly reconnect after a reconnection [see](https://github.com/status-im/nimbus-eth2/blob/v22.11.0/beacon_chain/networking/eth2_network.nim#L1737-L1738)
* and don't spam connections to a peer that failed [see](https://github.com/status-im/nimbus-eth2/blob/v22.11.0/beacon_chain/networking/eth2_network.nim#L1284)
