### ISSUE TITLE
idea: separate filter into two protocols

### ISSUE THREAD

**Issue by richard-ramos** [waku-org/nwaku#1423]
### Problem
`/vac/waku/filter/2.0.0-beta1` is being used for both full nodes and lightnodes. A lightnode could be potentially misidentified as a full node since both types of nodes are indistinguishable due to using the same protocol. This could be specially noticeable if using identify protocol to populate the peer store with information about the protocols supported by the node, and then later, randomly selecting nodes from the peerstore that support filter protocol. A lightnode could be chosen by mistake to subscribe messages from it.

### Possible Solutions
Instead of having a single protocol `/vac/waku/filter/2.0.0-beta1` what if we instead use two different protocols:
- `/vac/waku/filter/2.0.0-beta1`: would be used only by full nodes.
- `/vac/waku/filter-subscriber/2.0.0-beta1`. used by light nodes.

When a light node requests a subscription from a full node, the full node would push messages back to the subscriber using the `filter-subscriber` protocol.

**Comment by LNSD** [comment]
@richard-ramos I think this issue belongs to either [waku-org/pm](https://github.com/waku-org/pm) or [vacp2p/rfc](https://github.com/vacp2p/rfc) repo.

----

I can't entirely agree with splitting it into two parts: subscription management and message push. There is a dependency between the two parts and cannot be separated.

But I agree that the Waku filter protocol deserves a "productivization" revisit. And we need to modify the Waku filter wire formats so they are not coupled.

**Comment by jm-clius** [comment]
Although I agree that the there is a strong dependency/linking between the two parts, I think from a libp2p perspective it makes sense to use two protocol IDs (still part of the same Waku protocol). This is especially necessary for a capability discovery based on `identify` to differentiate filter service nodes from client nodes and directionality of filter messages. I tried to incorporate this idea in https://github.com/vacp2p/rfc/pull/562 and am of course very open to any comments/alternative suggestions. Let's continue the conversation there! :)

**Comment by richard-ramos** [comment]
Closing the issue as I agree that it should not belong to this repository.
Thank you!
