### ISSUE TITLE
idea(rln-relay): use rln-relay as a sub-protocol of waku-relay

### ISSUE THREAD

**Issue by rymnc** [waku-org/nwaku#1460]
### Background
1. [Waku Relay](https://rfc.vac.dev/spec/11/)
2. [Waku RLN Relay](https://rfc.vac.dev/spec/17/)
3. [Pubsub topic message validation](https://github.com/waku-org/nwaku/blob/a69301f39292c6bd012427e3a172a7687222fa89/libp2p/protocols/pubsub/pubsub.nim#L496)
4. [RLN Group Sync Layer](https://rfc.vac.dev/spec/17/#group-synchronization)

### Details
In it's current state, waku rln relay is perceived as a *protocol*, whereas, it is a thin layer over waku-relay. It does not have a protocol id, as it uses waku-relay to send and receive messages. waku-relay provides message validation for a given pubsub topic, and we use the rln validation logic there. Therefore, all waku-rln-relay does, is message validation on a given pubsub topic.

There are misconfigurations possible with waku-rln-relay, when operators would like to run spam prevention, but do not realize they need to enable the waku-relay protocol for it to mount correctly. 

This proposal aims to feature flag rln/rate-limiting *within* waku-relay, where it is mounted in tandem with waku-relay, and each form of message validation in rln (which is directly related to the group synchronization) is a different pubsub validator that is applied depending on the configuration passed to waku-relay.

Semantically, this aligns more with the rln/rlnp2p vision and also clears confusion re: the real function of waku-rln-relay.

### Acceptance criteria
- TBD: will be fleshed out if proposal passes

**Comment by fryorcraken** [comment]
@alrevuelta @jm-clius should this be part of [Epic 3.2?](https://github.com/waku-org/pm/issues/70) ?

**Comment by rymnc** [comment]
not planned since this will be replaced with pluggable validators.
