### ISSUE TITLE
bug(rpc): connecting to a peer via RPC returns true even when failed

### ISSUE THREAD

**Issue by alrevuelta** [waku-org/nwaku#1469]
### Problem

Connecting to a peer via RPC returns true even when failed

### Impact
In the RPC and difficults kurtosis testing, since its how peers are currently being added.

### To reproduce

Run `nwaku`
```
./build/wakunode2 --relay=true --filter=true --lightpush=true --store=true --rpc-admin=true --keep-alive=true --max-connections=150 --dns-discovery=true --dns-discovery-url=enrtree://AOGECG2SPND25EEFMAJ5WF3KSGJNSGV356DSTL2YVLLZWIV6SAYBM@prod.nodes.status.im --discv5-discovery=true --discv5-udp-port=9005 --discv5-enr-auto-update=True --log-level=INFO --rpc-port=8545 --rpc-address=0.0.0.0 --tcp-port=30304 --metrics-server=True --metrics-server-port=8003 --metrics-server-address=0.0.0.0
```

When trying to connect to a peer via the RPC. Note `fake-peerid` is not a valid peerId:
```
curl -d '{"jsonrpc":"2.0","method":"post_waku_v2_admin_v1_peers","params":[["/ip4/43.74.128.5/tcp/60000/p2p/fake-peerid"]],"id":1}' -H 'Content-Type: application/json' 127.0.0.1:8545
```

Returns, but it didn't connect.
```
{"jsonrpc":"2.0","id":1,"result":true}
```

### Expected behavior
It returns the following when fails: `false`.
```
{"jsonrpc":"2.0","id":1,"result":false}
```

### nwaku version/commit hash
3347f8030c74d12c50204155012558238d293614

cc @AlbertoSoutullo

**Comment by alrevuelta** [comment]
@AlbertoSoutullo Fix already merged. This is scheduled to go in the `0.14.0` release planned next week Jan 16th. Hope it helps!

**Comment by AlbertoSoutullo** [comment]
Thanks!

> @AlbertoSoutullo Fix already merged. This is scheduled to go in the `0.14.0` release planned next week Jan 16th. Hope it helps!
