### ISSUE TITLE
feat: ability to manually specify additional multiaddrs

### ISSUE THREAD

**Issue by mfw78** [waku-org/nwaku#1475]
### Problem
As a node operator, if I have followed the ['listening on websocket to enable connections with waku v2 browser peers ](https://github.com/waku-org/nwaku/blob/019f357dc948da11ec2eae7f6403adfb347e4dce/docs/tutorial/websocket.md) tutorial, my node will not advertise `wss` on disc.

This is a problem in all cases where SSL termination is handled upstream of the `nwaku` / `websockify` node combination, such as:

* Kubernetes deployments using ingress proxies.
* Dappnodes (my case) that use an NGINX HTTPS proxy that abstracts away SSL termination / letsencrypt / DNS config.

### Suggested solution
Provide a configuration option (CLI and environment variable) that allows for manually specifying additional `multiaddrs` that are to be advertised on disc protocols.

### Alternatives considered
It was also considered to use the `--websocket-support:true` flag for normal `ws` (albeit on port `8000`), though in this configuration, using the `light-js` client to attempt to dial the node (being behind a dappnode's HTTPS NGINX proxy, forwarded to the websocket port of `8000`), the `light-js` client failed to dial. It was determined that only with `websockify` forwarding to port `60000` on `nwaku` was I able to dial using `light-js`.

Nonetheless, this alternative would still not solve the issue of correctly advertising `wss` and `ws` on the correct IANA-specified ports.

### Acceptance criteria
For this feature to be deemed accepted, a node operator should be able to:

- [ ] Specify additional `multiaddrs` on which their node is dialable (`ws`, and `wss`).

**Comment by jm-clius** [comment]
Thanks for this issue!

**Comment by alrevuelta** [comment]
Not sure if we can close this? [see comment](https://github.com/waku-org/nwaku/pull/1509#pullrequestreview-1270720353)

**Comment by jm-clius** [comment]
Indeed. Re-opening.

**Comment by rymnc** [comment]
The PR autoclosed it :/
