### ISSUE TITLE
bug: undialable & inconsistent peer ids between response from peer exchange & fleets.status.im

### ISSUE THREAD

**Issue by danisharora099** [waku-org/nwaku#1484]
### Problem
The multiaddresses received from peer exchange are undialiable. The peer IDs are seemingly inconsistent with the ones from https://fleets.status.im).

### Impact
js-waku can't dial nodes found using peer exchange

### To reproduce
If you can reproduce the behavior, steps to reproduce:
1. Go to 'js-waku' 's Github
2. Checkout to `danisharora/px-refactor`
3. `cd packages/tests && DEBUG=waku* npm run test:node`
4. See console for found peers, dial attempts and feel free to add `libp2p*` in DEBUG to also see libp2p's dial attempts & errors
(attaching logs below anyway)

### Expected behavior
The peers found via peer exchange should be dialable

### Screenshots/logs
Peer IDs and their multiaddresses received from peer exchange:
```
  {
    id: '16Uiu2HAmSV1t6ph8qZ3nXrbzMpq6JXpkK25BvAvTUdE1ipnHQ5jL',
    ma: [ '/dns4/node-02.do-ams3.status.prod.statusim.net/tcp/443/wss' ]
  },
  {
    id: '16Uiu2HAmE7h7rTVD2vJeGbrt75Bu3ytJWjPcAULUmk1jZaR7VsDd',
    ma: [
      '/dns4/node-01.gc-us-central1-a.wakuv2.test.statusim.net/tcp/8000/wss'
    ]
  },
  {
    id: '16Uiu2HAkyjih6HvC1Kaw3vuyvj934gE3LudXYZ8NrWSazse67PNq',
    ma: [ '/dns4/node-02.do-ams3.status.prod.statusim.net/tcp/443/wss' ]
  },
  {
    id: '16Uiu2HAkxJ57V5iVeQfcP2KrBbxUxx5BFUL3XVkmbo1zmxYnGHTg',
    ma: [ '/dns4/node-01.do-ams3.status.prod.statusim.net/tcp/443/wss' ]
  },
  {
    id: '16Uiu2HAmHYpbsVxLgiHoAnCY6ai25ZCPxYesmTBgoN3Bdvdy2sJu',
    ma: [ '/ip4/134.209.139.210/tcp/8000/wss' ]
  },
  {
    id: '16Uiu2HAmG1YMvMKEoRKfj9jyHzGGUPW5DiHpvPveAAujo7VRx8o1',
    ma: [ '/dns4/node-02.do-ams3.status.prod.statusim.net/tcp/443/wss' ]
  },
  {
    id: '16Uiu2HAmTe4ky6Nae9uAysrZESFs61hQrbnWbWxbYy4UXHc5A529',
    ma: [ '/ip4/47.243.128.134/tcp/443/wss' ]
```

Console logs (with `libp2p*`, `waku*` and manual logs in place): https://pastebin.com/nPCbn8yy

### nwaku version/commit hash
0.13.0

### Additional Context
One of the things that I was able to spot for status.prod nodes is that inconsistency with peer IDs

**Comment by alrevuelta** [comment]
Hi! Thanks for reporting.

Mind ellaborating what you mean by "peer IDs are seemingly inconsistent with the ones from https://fleets.status.im"? Do you mean that if a given fleet peer has `peerId_1` and `ip_1` then what you get from peer exhange is `peerId_2` but with the same `ip_1`?

Note that peer exhange reports not only fleet peers (bootstrap) but also `discv5` peers. So px doesnt have to be consistent with the fleets.

> The peers found via peer exchange should be dialable

Not sure if this assumption is right. The px protocol can report peers that are not dialable (eg no longer exists, are behind a nat, not listening in the correct port, etc)

**Comment by danisharora099** [comment]
> Hi! Thanks for reporting.
> 
> Mind ellaborating what you mean by "peer IDs are seemingly inconsistent with the ones from https://fleets.status.im"? Do you mean that if a given fleet peer has `peerId_1` and `ip_1` then what you get from peer exhange is `peerId_2` but with the same `ip_1`?
> 
> Note that peer exhange reports not only fleet peers (bootstrap) but also `discv5` peers. So px doesnt have to be consistent with the fleets.
> 
> > The peers found via peer exchange should be dialable
> 
> Not sure if this assumption is right. The px protocol can report peers that are not dialable (eg no longer exists, are behind a nat, not listening in the correct port, etc)

Ah I see. Thanks for clarifying!
Both points make sense.

I have been unsuccessful with dialing any of the above found PX peers -- guess it is just coincidental? 😅

**Comment by alrevuelta** [comment]
> I have been unsuccessful with dialing any of the above found PX peers -- guess it is just coincidental? 😅

Depending on which network you are connected to, but in `status.prod` there are tons of unreachable peers, would say a double digit %. So yeap :)

This tool can help test if a node is reachable or not:
https://github.com/waku-org/nwaku/tree/master/tools/wakucanary

Or perhaps more user friendly?
https://examples.waku.org/light-js/

And more "higher level" you can check if the node has the port open with this tool. If the port is closed, most likely the node won't be reachable (unless some weird cases)
https://www.yougetsignal.com/tools/open-ports/

So no rule of thumb but just leaving some tools there to debug :)

**Comment by alrevuelta** [comment]
> Do you suggest actioning to ensure there should be a few reachable peers found via discv5/PX at all times?

With `discv5` we can't do much. I mean, we can't control if the peers we get are reachable or not. What we do is assign some backoff to peers that can't be dialed https://github.com/waku-org/nwaku/pull/1462 and eventually we remove them from the peer store. But note that they can be discovered again at some point.

But your suggesstion really makes sense in for px. I think it would make sense to "curate" the peers that are exchanged, so that without any guarantees, we try to share only peers that we know are reachable.

Perhaps @kaiserd has some input here. For context, @danisharora099 is suggesting that the px just shares peers that are dialable, and not just whatever comes from disv5. This is currently an issue because most of the peers are not dialable. I would suggest keeping the px cache (for "security" reasons as discussed) and just sharing dialable peers.

Added this to the Networking MVP https://github.com/waku-org/nwaku/issues/1353 to not forget. But I think indeed its very helpful, a light client can't get 10 peers that are not dialable.

**Comment by danisharora099** [comment]
Closed for now as discussed this is expected behavior for now. Partially superseded by https://github.com/waku-org/nwaku/issues/1353.

Thanks!
