### ISSUE TITLE
bug: wrong metric of inbound/outbound peers

### ISSUE THREAD

**Issue by alrevuelta** [waku-org/nwaku#1503]
### Problem

Metric `waku_connected_peers` indicating number of inbound/outbound peers is incorrect.

### Impact
Just metrics, but can be misleading for node operators. However the metrics we are currencly monitoring are `libp2p_peers` and  `libp2p_pubsub_peers`.

### To reproduce

Run the node for some hours and check `waku_connected_peers` metric.

### Expected behavior

The metric `waku_connected_peers` correctly displays the number of Inbound/Outbound peers.

### Screenshots/logs
![image](https://user-images.githubusercontent.com/8811422/213991755-3ce2740e-9e71-4b67-a1d3-4a541eaf8b44.png)

### nwaku version/commit hash

`v0.14.0` release.

**Comment by alrevuelta** [comment]
Issue is most likely here: https://github.com/waku-org/nwaku/blob/master/waku/v2/node/peer_manager/peer_manager.nim#L137-L157

A more specifically here: https://github.com/waku-org/nwaku/blob/master/waku/v2/node/peer_manager/peer_manager.nim#L151

**Comment by LNSD** [comment]
This can be ignored ☝🏼 I wanted to refer the issue number 1502, and I wrote 1503 instead.
