### ISSUE TITLE
feat: config wakucanary to support websockets

### ISSUE THREAD

**Issue by felicio** [waku-org/nwaku#1528]
### Problem

The [waku canary tool](https://github.com/waku-org/nwaku/tree/1f79375679be9a3f2f73672e597665fe2e585c9b/tools/wakucanary) is a monitoring tool that can be used to dial a running Waku node and assert that it supports a given set of protocols. However, it can currently only dial listening ports on the Waku node using (plain) TCP transport.

Many Waku nodes, however, expose a plain or secure websocket port, often to allow connections to web/browser-based nodes. Status fleet nodes, for example, support websockets to allow connections from Status Web peers. These listening ports cannot be monitored by the canary tool, as it does not yet support WebSockets transport.

### Suggested solution

Add WebSockets support to the wakucanary tool. It can use [the `wakunode2` app](https://github.com/waku-org/nwaku/blob/1f79375679be9a3f2f73672e597665fe2e585c9b/apps/wakunode2/wakunode2.nim#L297-L299), which already supports WebSockets, as inspiration.
To keep the configuration simple, I'd suggest using the supplied target `--address` config to decide whether to enable websockets or not.
If the supplied target address is a `ws` address, plain (unsecured) websockets should be enabled. If `wss`, secure websockets should be enabled, which would also require configuring a TLS security key and certificate, similar to the [wakunode2 app](https://github.com/waku-org/nwaku/blob/1f79375679be9a3f2f73672e597665fe2e585c9b/apps/wakunode2/config.nim#L437-L445).

Existing deployed node addresses can be viewed [here](https://fleets.status.im/), which features both pure TCP and secure websockets listening addresses.

### Acceptance criteria

- [x] wakucanary service can accept WebSockets target addresses
- [x] wakucanary can be configured with TLS security key and certificate, which is used when the target address is `wss`
- [ ] wakucanary documentation is updated accordingly

---

> NOTE: Everything below can be ignored and relates to previous discussions and a since fixed bug.

~~### Additional context~~ 

~~Latest deploy stopped the nodes from operating due to `error="failed to create waku node instance: Max number of connections can't be greater than PeerManager capacity"` and went unnoticed (see https://kibana.infra.status.im/goto/90932700-a2fa-11ed-aaa4-85391103106b and https://grafana.infra.status.im/goto/vWaZ9KA4k?orgId=1).~~

~~If extended, this tool could be later used to set up infrastructure checks like https://canary.infra.status.im/result/6046835/.~~

~~Relates to https://github.com/waku-org/nwaku/pull/1525~~

**Comment by alrevuelta** [comment]
Indeed, adding ws support to the wakucanary tool would be useful.

On the other hand, can you elaborate more on how the latest issue in the fleets went unnoticed? I mean fleets are using also tcp as transport, and wakucanary should be checking that. So regardless of suppporting ws or not, the tcp check should have failed.
