### ISSUE TITLE
chore: improve test coverage on NetConfig generation

### ISSUE THREAD

**Issue by rymnc** [waku-org/nwaku#1540]
### Background
In #1512, the waku node network config was abstracted out.
Test coverage on address generation is low at the moment.

### Details
Tests for the network config generation to improve coverage to detect regressions.

### Acceptance criteria
- [ ] Identify common network configs
- [ ] Tests for the same

cc: @jm-clius

**Comment by gabrielmer** [comment]
**Weekly Update**

- _achieved_: developed the new NetConfig test suite, raised PR and received initial feedback
- _next_: address potential new feedback and merge when approved
