### ISSUE TITLE
chore: improve relayConnectivityLoop to make sure in/out conns are relay conns

### ISSUE THREAD

**Issue by alrevuelta** [waku-org/nwaku#1566]
### Background
Right now we have a `relayConnectivityLoop` that is meant to ensure the node is connected to a target amount of relay nodes. For example, we want nwaku to have always eg 10 relay node connections, and this loop tries to keep them.

In order to count this, we currently use `switch.connectedPeers()` (both inbound and outbound) to count the number of connections, but this is not accurate, since this will return "connections in general" not just using the relay protocol.

This means that the current estimation of "how many relay nodes are we connected to" is not accurate. With the current exposed variables and methods in nim-libp2p there is not clear easy way of accesing this information.

### Acceptance criteria
* `relayConnectivityLoop` truly tracks the amount of relay connections (not connections in general)

**Comment by alrevuelta** [comment]
This should allow us to track relay connections.
https://github.com/status-im/nim-libp2p/issues/866

**Comment by Menduist** [comment]
Also see nimbus code for scoring
https://github.com/status-im/nimbus-eth2/blob/6b9381ef41bdbb359c7fca013aef945f477134a5/beacon_chain/networking/eth2_network.nim#L1439

Which computes the number of peers in a mesh & numbers of peers subbed to a topic

And useful libp2p metrics
https://github.com/status-im/nim-libp2p/blob/ddeb7b3bd4610f27ee0ebb6bad9ab6c22e7c416d/libp2p/protocols/pubsub/gossipsub/behavior.nim#L30

**Comment by alrevuelta** [comment]
Perhaps this can work as a temporal solution but its not just limited to `relay` peers. In the future we may want to track also `store` connections or other protocols, [example](https://github.com/waku-org/nwaku/issues/1549#issuecomment-1425887249). Also with the current exposed variables, afaik we can't get the direction of the connection.

**Comment by jm-clius** [comment]
Note: May require some underlying changes in submodule. Iceboxed for now.
