### ISSUE TITLE
chore: update resolved enr ip when using `dns4-domain-name` flag

### ISSUE THREAD

**Issue by alrevuelta** [waku-org/nwaku#1576]
### Background

When using `dns4-domain-name` eg

```
./build/wakunode2 --dns4-domain-name=google.com --discv5-discovery=true
```

The node creates an ENR with ip `0.0.0.0` and the multi is constructed using that ip `/ip4/0.0.0.0/tcp/60000/p2p/16Uiu2HAmFj9mVkzj81XBFTVK1475iKoPPiakdgZtoPTtPaTYqqRy`.

Example of the generated ENR with the above command (decode it [here](https://enr-viewer.com/))
```
enr:-Ki4QAnkkUPeFFRuIxB9KkPQqO9lKIgFxc84egqGM7mBj7bdPGlUxsnqERtpD1Z2i0-nVxyyDquUlPAq7-u9KcQxbNkBgmlkgnY0gmlwhAAAAACKbXVsdGlhZGRyc5EADzYKZ29vZ2xlLmNvbQbqYIlzZWNwMjU2azGhAy2kCEHyIKJ1iAyAzger0hd5kzbxgpYJyOvLFfzElg9Yg3RjcILqYIV3YWt1MgE
```

The thing is that since discv5 doesn't understand our `multiaddrs` field, this node won't be discoverable by disv5, since the address that is being advertised is `0.0.0.0`.

In other protocols using libp2p and discv5 (eg Ethereum) the address that is advertised in the enr is the ip that results of resolving `dns4-domain-name`.

Example. In prysm using the following, will lead to an ENR that contains the IP that resolved from google.com. See logs:

```
docker run prysmaticlabs/prysm-beacon-chain:latest --p2p-host-dns=google.com --accept-terms-of-use
```

### Acceptance criteria
* When running `./build/wakunode2 --dns4-domain-name=some_domain` the constructed ENR `ip` field contains the resolved IP instead of just `0.0.0.0`.

**Comment by gabrielmer** [comment]
**Weekly Update**

- _next_: analyze and fix issue

**Comment by gabrielmer** [comment]
**Weekly Update**

- _achieved_: implemented solution that does DNS IP resolution during node bringup when no external IP is found but a DNS address is provided.
Validated and tested "happy paths" of the solution, raised draft PR and got feedback about the solution
-_next_: discuss and define the system's behavior on errors, implement error handling and adding tests for this feature.

**Comment by gabrielmer** [comment]
**Weekly Update**

- _achieved_: added error handling and tests, received new feedback and started addressing them
-_next_: get the version with the changes requested reviewed and merge if approved

**Comment by gabrielmer** [comment]
**Weekly Update**

 - _achieved_: addressed feedback and merged
