### ISSUE TITLE
feat: implement new Waku Filter protocol

### ISSUE THREAD

**Issue by jm-clius** [waku-org/nwaku#1579]
### Problem

This issue tracks the implementation in Waku of the improved Filter protocol tracked in https://github.com/waku-org/pm/issues/5.

### Suggested solution

The proposed RFC changes is tracked in https://github.com/vacp2p/rfc/pull/562.

A parallel implementation in go-waku has already commenced.

**Comment by jm-clius** [comment]
Closing as basic implementation has been completed.

**Comment by vpavlin** [comment]
@jm-clius Did you forget to *actually* close the issue?

**Comment by jm-clius** [comment]
😶 Seems like I did. Thanks!
