### ISSUE TITLE
bug: `post_waku_v2_relay_v1_message` expect hex string instead of base64

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/nwaku#1616]
### Problem

the `post_waku_v2_relay_v1_message` API on `master` branch commit 94459b48866b4ba4697ff13f89ac52709caa3c7e expect a hex string as payload instead of base64 w/ padding as per RFC

### Impact

Can't use some command of the JSON RPC API without code change.

### To reproduce

Try to submit the following data:

```
  waku:nwaku RPC Query:  post_waku_v2_relay_v1_message [
  '/waku/2/default-waku/proto',
  {
    payload: 'SGVyZSBpcyBhbm90aGVyIG1lc3NhZ2Uu',
    contentTopic: '/test/1/waku-relay/utf8',
    timestamp: 1679371679104000000n
  }
]
```

The payload is:
- as utf8: `Here is another message.`
- as hex: `4865726520697320616e6f74686572206d6573736167652e`

Note that the API **does** accept the payload as hex, which is **not** expected.

```
  waku:nwaku RPC Query:  post_waku_v2_relay_v1_message [
  '/waku/2/default-waku/proto',
  {
    payload: '4865726520697320616e6f74686572206d6573736167652e',
    contentTopic: '/test/1/waku-relay/utf8',
    timestamp: 1679372123758000000n
  }
] +1s
  waku:relay validating message from 16Uiu2HAmAzqVWqQ3zGj6bboQiy5Gm4xF8kQ3iqaxXQwpCkV6Atye received on /waku/2/default-waku/proto +0ms
```

### Expected behavior

`payload` as base64 should be accepted.

### Screenshots/logs

[base64_payload_nwaku.log](https://github.com/waku-org/nwaku/files/11024960/base64_payload_nwaku.log)
[hex_payload_nwaku.log](https://github.com/waku-org/nwaku/files/11024961/hex_payload_nwaku.log)

### nwaku version/commit hash
94459b48866b4ba4697ff13f89ac52709caa3c7e

### Additional context

It seems to work fine with v0.16.0

Cc @LNSD

**Comment by jm-clius** [comment]
Without having tried to reproduce yet, I guess it's possible that the hex string may (incorrectly) be decodeable as a valid `base64` string, but that would not explain why valid base64 encoded strings would fail.

**Comment by jm-clius** [comment]
@fryorcraken, perhaps I'm misinterpreting the issue: did the API call also _fail_ to publish `SGVyZSBpcyBhbm90aGVyIG1lc3NhZ2Uu` or is the issue simply that it did _not fail_ for the hex string?
When reproducing locally it succeeds for me with `SGVyZSBpcyBhbm90aGVyIG1lc3NhZ2Uu`. It also succeeds with the "hex" string, but I think this may simply be because the string may be decodeable as base64 (tried some other online base64 decoders and they could also decode the hex string).

**Comment by fryorcraken** [comment]
User error
