### ISSUE TITLE
test(rln-relay): rln-relay testnet 3

### ISSUE THREAD

**Issue by rymnc** [waku-org/nwaku#1624]
### Problem
rln-relay has changed quite a bit since testnet 2, including - 
- circuit changes
- contract changes
- keystore changes
- nwaku changes.

Support for rln-relay in the `wakuv2.test` fleet was dropped some time back, hence, we cannot see live metrics for it.

### Proposal
We re-enable rln-relay on the `wakuv2.test` fleet for a period of 2-3 weeks, while we iron out any integration bugs, and measure performance.

CC's make use of chat2/js-rln to send a few messages everyday.

### Pre-requisites
- Define set of CC's participating
- Define content topic, documentation on usage with chat2
- Faucet some testnet eth to CC's
- Deploy the updated rln contract

### Details

- Contract Address: `0x9C09146844C1326c2dBC41c451766C7138F88155`
- Network: `Sepolia`
- ChainId: `11155111`
- FromBlock: `3193048`
- ABI, etc located here for easy use: https://raw.githubusercontent.com/vacp2p/rln-contract/2c4ddb03120b61b0eea1129b6cfdcd23ab7ad8cb/deployments/sepolia/RLN.json
- rln-contract head: https://github.com/vacp2p/rln-contract/tree/2c4ddb03120b61b0eea1129b6cfdcd23ab7ad8cb

cc: @waku-org/waku-product

**Comment by fryorcraken** [comment]
in terms of needed work to get this ready, is it just about new contract address and new ABI or is there function code changes to do to?

**Comment by rymnc** [comment]
@fryorcraken, there are minor changes in the event returned. 

s/pubkey/idCommitment/g. everything else, should have the same functionality.

**Comment by fryorcraken** [comment]
tracking here: https://github.com/waku-org/js-rln/issues/53 for js-waku

**Comment by richard-ramos** [comment]
go-waku: https://github.com/waku-org/go-waku/issues/505

**Comment by rymnc** [comment]
Testnet 3 wrapped up and retrospective completed - https://github.com/vacp2p/research/issues/179#issuecomment-1579202451
