### ISSUE TITLE
feat: nwaku static sharding

### ISSUE THREAD

**Issue by LNSD** [waku-org/nwaku#1643]
### Problem
See https://github.com/waku-org/pm/issues/15

### Suggested solution
TBD

### Additional context
- Waku ENR fields.
  + `multiaddr` field is not encoded using "machine friendly" encoding (see [this](https://github.com/multiformats/multiaddr/blob/master/protocols.csv)), we are just converting from utf-8 to bytes and back. The space occupied by the multiaddr could be optimized by using the machine format of the multiaddress spec.
    
### Acceptance criteria
- [x] Rework the pub-sub topic namespacing types and validation.
- [x] Extensible ENR types (builder + TypedRecord accessors)
- [x] Adapt the ENR capabilities (`waku2`) and `multiaddr` entries.
- [x] Support topic validation of the command-line arguments.
- [x] Add ENR support for the topic sharding field.
- [x] TBD: Add logic to discovery mechanisms to act upon discovering a node that supports certain topic shards.

**Comment by vpavlin** [comment]
Seems like there is still work to be done, so moving to next release

**Comment by jm-clius** [comment]
Closed and tracked in https://github.com/waku-org/nwaku/issues/1776
