### ISSUE TITLE
bug: inconsistent usage of topic flags

### ISSUE THREAD

**Issue by jakubgs** [waku-org/nwaku#1726]
### Problem
There's two ways to use topics flags:

* `--topics` - Takes a list of comma separated topics, CANNOT be repeated.
* `--protected-topic` - Does NOT take a list, CAN be repeate.

Makes no sense.

### Impact
Almost made me vomit.

### Expected behavior
Not inducing nauseousness. Probably just make `--topics` into `--topic` and allow it to be repeated.

### Additional context
https://github.com/waku-org/nwaku/blob/b277ce1013563b4e76a3f8694f0eefb1f3528a4d/apps/wakunode2/config.nim#L210-L213
https://github.com/waku-org/nwaku/blob/b277ce1013563b4e76a3f8694f0eefb1f3528a4d/apps/wakunode2/config.nim#L40-L43

**Comment by jm-clius** [comment]
Hahaha. Yeah, this is bad. The `--topics` config item is old and was never used until recently, so no-one scrutinised how ugly it is against the rest of the config items. I think `--topic` should be repeated argument (similar to almost all other repeated config items).
