### ISSUE TITLE
[Milestone] Move Waku v1 and Waku-Bridge to new repos

### ISSUE THREAD

**Issue by alrevuelta** [waku-org/nwaku#1767]
**Planned start date:** 1 Aug 2023
**Due date:** 11 Aug 2023

# Summary

@jm-clius suggestion: split into three repos: waku-legacy for the (barely changing) v1  and whisper code, nwaku for v2 and waku-bridge for the bridge with both nwaku and legacy as submodules.

adding: remove `v2` references, so nwaku is nwaku not `nwaku/v2`. perhaps both bridge and v1/whisper part of waku-legacy repo, but no strong opinion.

**Comment by jm-clius** [comment]
Thanks for creating tracking issue. Agree re removing "v2" references.

>  perhaps both bridge and v1/whisper part of waku-legacy repo, but no strong opinion.

No strong opinion either, but note that this will have the weird-ish effect of "v2" with all its own complicated submodules being a submodule for the legacy repo.

**Comment by alrevuelta** [comment]
> No strong opinion either, but note that this will have the weird-ish effect of "v2" with all its own complicated submodules being a submodule for the legacy repo.

mm i see. then whatever is easier.

**Comment by vpavlin** [comment]
I would vote for 3 repos as originally suggested to make things less tangled

**Comment by jm-clius** [comment]
**Weekly Update**

_achieved_: Removed v1 and wakubridge code from nwaku repo
_next_: Remove references to `v2` from nwaku directory structure and documents
