### ISSUE TITLE
chore: test_rln_group_manager_static.nim fails randomly

### ISSUE THREAD

**Issue by Ivansete-status** [waku-org/nwaku#1796]
### Background
Tests fail randomly in PR's.

### Details
When a PR is submitted, the `experimental` workflow failed on MacOS but after re-running the job, it worked.

The issue happened in:
https://github.com/waku-org/nwaku/blob/940206b439f58494887abc0f25b48b9e514980f8/tests/v2/waku_rln_relay/test_rln_group_manager_static.nim#L38

Maybe we could have sth like the next to get a better idea about the error when it happens:

```code
assert rlnInstanceRes.isOk(), rlnInstanceRes.error
```

This is a screenshot showing the test that failed:
![image](https://github.com/waku-org/nwaku/assets/128452529/a9e48b2c-172d-4467-bb3d-ee59ef77e337)

**Comment by rymnc** [comment]
Re-opening since the same fix has to be applied to other test files.
