### ISSUE TITLE
feat: set limit on store responses

### ISSUE THREAD

**Issue by alrevuelta** [waku-org/nwaku#1809]
### Problem
Store nodes have no limits on the amount of requests they process (in terms of req/s or served bytes/s per peer)

### Suggested solution
Set limits on how many requests/second and/or bytes/second a store node can serve to each peer

**Comment by jm-clius** [comment]
Idea from offsite: use token bucket in chronos to rate limit. Should be simple to do and provide basic request rate limiting. May need more sophisticated solution to also limit e.g. response size allocation per client.

**Comment by chair28980** [comment]
Duplicated in node bandwidth management issue (need issue number to link).

**Comment by NagyZoltanPeter** [comment]
@chair28980 : It can be closed as solved by: https://github.com/waku-org/nwaku/pull/2390
