### ISSUE TITLE
Update fleets according to the new -topic parameter

### ISSUE THREAD

**Issue by Ivansete-status** [waku-org/nwaku#1814]
The `-topics` param had been deprecated in favor of the `-topic` one. For that reason, we need to properly coordinate with @jakubgs the infra change that needs to be done beforehand in the wakuv2.prod fleet.

This coordination should be made right before the deployment to prod is made.

More details in https://github.com/waku-org/nwaku/pull/1806

**Comment by jakubgs** [comment]
According to notes I see this is available in `0.18.0`: https://github.com/waku-org/nwaku/releases/tag/v0.18.0

**Comment by Ivansete-status** [comment]
@jakubgs - Yes correct, the `-topic` parameter (repeatable parameter) is available in `0.18.0`.
For `0.19.0` we've completely deprecated the `-topics` parameter (spare-separated string of topics.)

**Comment by jakubgs** [comment]
Done:
```
 > a all -a 'grep topic /docker/nim-waku-v2/docker-compose.yml'  
node-01.do-ams3.wakuv2.prod | CHANGED | rc=0 >>
      --topic='/waku/2/default-waku/proto'
      --topic='/waku/2/dev-waku/proto'
node-01.gc-us-central1-a.wakuv2.prod | CHANGED | rc=0 >>
      --topic='/waku/2/default-waku/proto'
      --topic='/waku/2/dev-waku/proto'
node-01.ac-cn-hongkong-c.wakuv2.prod | CHANGED | rc=0 >>
      --topic='/waku/2/default-waku/proto'
      --topic='/waku/2/dev-waku/proto'
```
Is this issue only for `wakuv2.prod` or also for `status.prod`?

**Comment by jakubgs** [comment]
I'm assuming the former. Reopen if not.
