### ISSUE TITLE
chore: find a name for this implementation

### ISSUE THREAD

**Issue by SionoiS** [waku-org/nwaku#1819]
### Background
Calling things ```node``` and ```app``` can be confusing. I suggest we choose a name. (and other waku impl. too!)

### Details
Replaced every mention of nwaku by the name chosen. Could coincide with MVP release? It's also good for branding!

### Acceptance criteria
- [ ] In the code, the word app should ONLY be used when taking about applications in general.
- [ ] In the code, the chosen name be used when referring to the application that impl. Waku protocols in Nim lang.
- [ ] Change all Docs.
- [ ] Change Github repo name.
- [ ] Announce the change far and wide on all comm channels.

Leave your suggestions below!

**Comment by Ivansete-status** [comment]
I think it is pretty consolidated the `nwaku` or `wakunode` names.
Nevertheless, if we get to a point where a renaming is considered:
- squid
- Unicorn
- opencom 
- xarxa (network in Catalan)
- fluid
- spreadcom
- naive

**Comment by Ivansete-status** [comment]
This issue might be related to https://github.com/waku-org/nwaku/issues/1002

**Comment by SionoiS** [comment]
Closing as, let's be honest, not gonna happen.
