### ISSUE TITLE
feat(rln-relay): Implement peer scoring in rln-relay

### ISSUE THREAD

**Issue by rymnc** [waku-org/nwaku#1836]
### Problem
When a peer sends a node an invalid proof, we do not reduce their score, and still allow them to send messages to the node.

### Suggested solution

~we must reduce their peer-score so that they can be pruned~
we should just drop the messages so that meshes can form better between peers

### Alternatives considered
-

### Additional context
- Part of the Waku Public network roadmap for rlnp2p

### Acceptance criteria
- [ ] Peer-score is reduced when a peer sends an invalid proof.

**Comment by rymnc** [comment]
This would not be required since peer-scoring is already done under the hood for dropped messages, right @jm-clius ?

**Comment by rymnc** [comment]
bump: @jm-clius

**Comment by jm-clius** [comment]
Let's wait for @alrevuelta to confirm that this is integrated end-to-end, but I think when any gossipsub validator returns `Reject` the sender will be punished (probably here: https://github.com/status-im/nim-libp2p/blob/d6263bf751f5552eadb236c51f053f35d59e376f/libp2p/protocols/pubsub/gossipsub/scoring.nim#L263-L272)

**Comment by alrevuelta** [comment]
I can confirm that gossipsub scoring is integrated in nwaku, so whenever a validator returns `Reject`, then the scoring will be decreased and at some point we will disconnect from that peer (if it send enough invalid messages)
