### ISSUE TITLE
chore(postgres): Create a docker file to bring nwaku + PostgreSQL simultaneously.

### ISSUE THREAD

**Issue by Ivansete-status** [waku-org/nwaku#1840]
### Background
Create a Docker Compose file that allows starting a Docker container with `nwaku` and the "store" protocol mounted plus another Docker container Postgres container.

### Details
To create the `nwaku` container, the next can be used as a reference:
```
version: '3.7'
services:
  node:
    container_name: 'nim-waku-v2'
    image: 'statusteam/nim-waku:deploy-wakuv2-test'
    labels:
      # auto-updating of docker image
      com.centurylinklabs.watchtower.enable: 'true'
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: '1383M'
        reservations:
          memory: '395M'
      restart_policy:
        condition: 'any'
    ports:
      - '127.0.0.1:8545:8545/tcp'
      - '30303:30303/tcp'
      - '30303:30303/udp'
      - '8008:8008/tcp'
      - '8000:8000/tcp'
      - '9000:9000/udp'
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:8008/health"]
      interval: 30s
      retries: 3
    command: |
      --relay=true
      --store=true
      --filter=true
      --lightpush=true
      --rln-relay=true
      --peer-exchange=true
      --rpc-admin=true
      --peer-persistence=false
      --keep-alive=true
      --max-connections=300
      --topic='/waku/2/default-waku/proto'
      --topic='/waku/2/dev-waku/proto'
      --store-message-db-url='postgres://postgres:test123@localhost:5432/postgres'
      --store-message-retention-policy=time:2592000
      --discv5-discovery=true
      --discv5-udp-port=9000
      --discv5-enr-auto-update=False
      --nodekey=d4735222265e16eee03f59718b9b5d03019c07d8b6c51f90da3a666eec13ab35
      --log-level=DEBUG
      --rpc-port=8545
      --rpc-address=0.0.0.0
      --tcp-port=30303
      --metrics-server=True
      --metrics-server-port=8008
      --metrics-server-address=0.0.0.0
```

- Where the `nodekey=d4735222265e16eee03f59718b9b5d03019c07d8b6c51f90da3a666eec13ab35` should ideally be a random value each time the `docker compose -f ... up` is called.

- I'm not sure if some tweaks will be required re `localhost` in `--store-message-db-url='postgres://postgres:test123@localhost:5432/postgres'`

To create the Postgres container, the next `docker compose` can be used as a reference:
```
version: "3.8"

services:
  db:
    image: postgres:9.6-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: test123
    ports:
      - "5432:5432"
```

### Acceptance Criteria
The `nwaku` node should be able to act as a "store" node and be able to store/retrieve messages from the Postgres database.

### Post actions
- [ ] Ping @LordGhostX when completed so that we have it documented
- [ ] Ping @fryorcraken about its completeness.

### Related issue
https://github.com/waku-org/nwaku/issues/1604

**Comment by alrevuelta** [comment]
plan to migrate this https://github.com/alrevuelta/nwaku-compose to waku-org
Can we have as part of that repo?

**Comment by Ivansete-status** [comment]
> plan to migrate this https://github.com/alrevuelta/nwaku-compose to waku-org Can we have as part of that repo?

Morning Álvaro! I think that's a great idea :)

**Comment by fryorcraken** [comment]
Grafana as part of the docker compose like I have seen previously would be good.
I wonder if Grafana can also provide some insights to Posgres? Thing like Watermark for example.

**Comment by Ivansete-status** [comment]
> Grafana as part of the docker compose like I have seen previously would be good. I wonder if Grafana can also provide some insights to Posgres? Thing like Watermark, db sidze for example (I'm not a DB Expert)

I don't know but I will explore it if is feasible :)

**Comment by vpavlin** [comment]
You'll probably need to use postgres-exporter (https://github.com/prometheus-community/postgres_exporter) for Prometheus as it does not seem Postgres itself can expose the metrics directly, but it should be relatively straightforward to add it to the compose

https://grafana.com/oss/prometheus/exporters/postgres-exporter/?tab=installation

**Comment by Ivansete-status** [comment]
I submitted this PR but I cannot assign reviewers.

https://github.com/alrevuelta/nwaku-compose/pull/3

@alrevuelta - I wonder if we could move this repo to the `waku-org` to enhance that.

If not possible, I'd like to add you, @vpavlin, and @LordGhostX as reviewers :)

Thanks in advance!

**Comment by Ivansete-status** [comment]
Morning @LordGhostX !

We've completed the creation of a docker compose file that runs both `nwaku` and a `postgres` instance. This might need to be updated in the  https://docs.waku.org/ portal.

Cheers!

**Comment by vpavlin** [comment]
This has been finished as part of https://github.com/waku-org/nwaku-compose
