### ISSUE TITLE
feat: update ENR based on RPC topic subscribe

### ISSUE THREAD

**Issue by SionoiS** [waku-org/nwaku#1843]
### Problem
Subscribing to a new topics via RPC does not update the ENR when using shards.

### Suggested solution
discv5 has a way to update the record. Create the same in waku discv5.

### Alternatives considered
Restarting the node with new topics always works but is annoying.

### Additional context
https://github.com/status-im/nim-eth/blob/285da12bf318a2e21182dc2453a4a30c58f73067/eth/p2p/discoveryv5/protocol.nim#L247

### Acceptance criteria
- [ ] Subbing to a shard topic like ```/waku/2/rs/16/0``` via RPC should update the ENR in waku discv5.

**Comment by SionoiS** [comment]
A bit of a conundrum here. Discv5 is no longer in ```waku_node``` but rpc handlers call ```node.subscribe()```

It seams like ALL protocol must be in ```waku_node``` otherwise we can't access them.

Architecturally, sending information from rpc handlers to whichever protocol needs it in an abstract way (channels!) would be best.

**Comment by alrevuelta** [comment]
good catch. random idea. perhaps some kind of action can be triggered after subs/unsubs to new topics. like this we can avoid this depencancy.

**Comment by SionoiS** [comment]
For topic subscriptions we are now using an event system.
