### ISSUE TITLE
chore: investigate latency of >500ms when using wakuv2.test fleet

### ISSUE THREAD

**Issue by jm-clius** [waku-org/nwaku#1868]
### Problem

One of the projects integrating Waku experienced 500ms delay between 2 nodes using light client protocols (using js-waku default bootstrap which is DNS Discovery with `wakuv2.prod` enrtree).

Note that this may have been a result of fleet nodes being temporarily overloaded, but it's important to investigate what the expected end-to-end latency (cumulative processing and transmission delays) of using light protocols are under normal and load conditions.

### Impact

Although we design end-to-end latency to be under 1 second in total, we wouldn't expect light protocols to have a delay over two hops of more than ~300 ms.

### To reproduce

Couldn't reproduce at 16:30 UTC on 08-01-2023. Previously reproduced using the following steps:

1. Create two clients with https://examples.waku.org/light-js/. Ensure these clients are connected to two different fleet nodes.
2. Subscribe both clients using filter protocol
3. Send messages between clients using lightpush and measure latency.

Previous result:

```
13:03:18.901 sent via /dns4/node-01.ac-cn-hongkong-c.wakuv2.test.statusim.net/tcp/8000/wss/p2p/16Uiu2HAkvWiyFsgRhuJEb9JfjYxEkoHLgnUQmr1N5mKWnYjxYRVm
13:03:19.425 received via /dns4/node-01.do-ams3.wakuv2.test.statusim.net/tcp/8000/wss/p2p/16Uiu2HAmPLe7Mzm8TsYUubgCAW1aJoeFScxrLj8ppHFivPo97bUZ
```

One measurement at 3:06 AM UTC on 24-07-2023: 524ms

### Expected behavior

End-to-end latency of ~300ms

### Additional context

To get an idea of the order of expected latency for relay (gossipsub) only on different network sizes, see the following simulation results done by @Menduist:

![image](https://github.com/waku-org/nwaku/assets/68783915/195928d4-1fe8-4b69-827c-0c6035b4b632)

**Comment by jm-clius** [comment]
Indeed.

Ping time used was 200ms. Simulation done with shadow. @Menduist may have some input but my guess is `D=6` was used. Not sure if part of a formal simulation or just an ad-hoc test to get a ball-park number.

**Comment by Menduist** [comment]
Parameters of the sim: https://github.com/status-im/nim-libp2p/blob/5f5217d49c29c2b5af847f1764debecce31bf367/shadow/main.nim#L55-L60

100ms RTT is more realistic (avg is 114ms in eth), but I messed up the config and put 200ms instead (:sweat_smile:)

**Comment by jm-clius** [comment]
@danisharora099 @fryorcraken afaik this has been "resolved" from nwaku's side as being not related to protocol-specific latency. I think we are now investigating on js-waku side and in terms of initial ping to service node? Closing this issue, but happy to reopen if there's more to investigate.

**Comment by fryorcraken** [comment]
tracked here: https://github.com/waku-org/js-waku/issues/1465
