### ISSUE TITLE
chore(rln-relay): remove registration capabilities

### ISSUE THREAD

**Issue by rymnc** [waku-org/nwaku#1887]
### Background
Currently, rln-relay has 2 functions -
1. Perform rate limiting on rln-relay protected topics
2. Allow a user to register into the membership set

### Details
As discussed in the offsite with @alrevuelta, it does not make sense to retain the "registration" capabilities in the rln-relay module, rather, we would expect users to obtain their membership out of band, via the application-specific registration criteria.

We should just accept keystore OR cli args with their membership details, and not provide registrations to our users.

### Acceptance criteria
- [ ] Remove registration from the `OnChainGroupManager`
- [ ] Remove the private key cli arg to wakunode2/chat2
- [ ] Write a tool (goes in apps/ ) that converts membership details into a keystore(`waku_keystore`)

Need thumbs from @jm-clius here!

**Comment by vpavlin** [comment]
I'd agree, maybe remove from CLI, keep in code?

**Comment by rymnc** [comment]
Not sure if we want to keep it altogether, if we're trying to cut scope as much as possible.
The current requirement for waku-rln-relay is that we permission a set of users into the membership set. 
cc: @alrevuelta

**Comment by rymnc** [comment]
also, `nim-web3` doesn't support arrays as arguments afaik, need to look into it a bit more
