### ISSUE TITLE
chore (postgres):  Make nwaku to reconnect to the Postgres database if it restarts

### ISSUE THREAD

**Issue by Ivansete-status** [waku-org/nwaku#1893]
### Background
Postgres is one of the data sources used when a `nwaku` node has the `store` protocol mounted. The connection between `nwaku` & `postgres` should be established if both processes are running.

### Details
During manual testing, I realized that if the Postgres database is restarted manually, then the `nwaku` doesn't try to establish a connection again. Therefore, `nwaku` should retry to connect in case the connection is interrupted.

### Acceptance criteria
The `nwaku` can properly establish a connection if the Postgres database is restarted many times and no leak happens after thousand of Postgres restarts.

**Comment by vpavlin** [comment]
This has other implications - what if `nwaku` tries to reconnect, but it can?

I can see 2 outcomes - it either "unmounts" `store` protocol (as it is unusable at that point), but that is kinds counter intuitive for the operator as the node seems completely healthy, it "just" degraded it's services

Or we "kill" the node if it cannot reconnect - then it is obvious for the operator that there is something to fix
