### ISSUE TITLE
chore: json-rpc and rest-api handlers are doubling the caches for messages.

### ISSUE THREAD

**Issue by NagyZoltanPeter** [waku-org/nwaku#1910]
### Background
Not pretty sure if it's by design and due to by decision. I found that currently relay rest-api and json-rpc maintain different message caches and doubles to handlers to be called to cache the messages.
It is the same currently for legacy filter as well.
I think it is waste of resources and can be refactored for an optimal solution.

### Details
When installing handlers on App side we are providing different cache instances for rest and rpc handlers.
Also current design does not support using same cache.

**Comment by chair28980** [comment]
Closing per discussion at nwaku pm 2024-01-02.

Issue no longer relevant after removal of json-rpc.
