### ISSUE TITLE
bug(rln-relay): RLN DB should be aware of chain and contract address

### ISSUE THREAD

**Issue by richard-ramos** [waku-org/nwaku#1921]
### Problem
Currently the RLN metadata only saves the last processed block. If we change the RPC endpoint to point to a different chainID, or change the contract address, the information stored in RLN SledDB then the information stored in the database is not useful anymore, as the event logs that populate the database are associated to an specific chainID and contract address. However, rln-relay in its current version does not verify the chainID, so it will reuse the same database information even tho it is incorrect.

### Impact
Merkle tree with incorrect data is generated. RLN validation will be done incorrectly.

### Expected behavior
- [ ] SetMetadata should store the last processed block, the chainID, and contract address
- [ ] When mounting rln-relay, it should compare the value from `--rln-relay-eth-contract-address` flag against the contract address stored in the metadata, AND the result from calling `eth_chainId` RPC method with the chainID stored in the metadata. If there is no match, drop the information of the DB
- [ ] Consider having different databases per chainID and contract address (?)  (perhaps it's possible by specifying a different tree path, and instead of dropping the database information, to log a FATAL error indicating a wrong database path is being used?)

**Comment by rymnc** [comment]
I think instead of dropping the database, we should just raise an exception from the mounting of rln-relay

**Comment by rymnc** [comment]
We should error out during mount, similar to how geth handles it - we should not even start the wakunode if there's a db mismatch
