### ISSUE TITLE
bug(rln-relay): non deterministic sorting applied to credentials, and contract 

### ISSUE THREAD

**Issue by richard-ramos** [waku-org/nwaku#1922]
### Problem
In https://github.com/waku-org/nwaku/blob/master/waku/waku_keystore/utils.nim#L17-L18, nwaku is sorting the credentials only by the membership group's contract address, so theoretically, depending on the membership groups being stored, the sorting could be non-deterministic.

### Impact
It is possible that the user specifies a keystore Index with the `--rln-relay-membership-index` that does not match the credentials they expect.

### Expected behavior
Sorting the credentials should be deterministic, so it probably should take into account not only the contract address, but also the chainID and the merkle tree index.

**Comment by rymnc** [comment]
beginning work on this - @richard-ramos would you like me to suggest the modification to the keystore in a spec, or should we discuss this out of band first?

**Comment by richard-ramos** [comment]
That structure would be perfect! the previous structure did complicate calculating the keystore index when a member was registered while with this, it's just fine, and we get rid of extra parameters in functions and flags!
:+1:

**Comment by rymnc** [comment]
Awesome, i'll start work on this tomorrow

**Comment by richard-ramos** [comment]
Since we're introducing that SHA, does it make sense to update the `MembershipCredentials` definition?
```nim
type MembershipCredentials* = object
   identityCredential*: IdentityCredential
   membershipGroups*: seq[MembershipGroup]
```
to
```nim
type MembershipCredentials* = object
   identityCredential*: IdentityCredential
   membershipGroup*: MembershipGroup <----------
```

**Comment by rymnc** [comment]
yes, my refactor will include that!
