### ISSUE TITLE
feat: Autosharding API for req-resp protocols

### ISSUE THREAD

**Issue by chair28980** [waku-org/nwaku#1935]
This tracks the work necessary in each client to provide API(s) to applications using req-resp protocols (store, lightpush, filter, etc.) with optional pubsub topic arguments. Each client should then use autosharding to determine the associated shards on behalf of applications. Note that underlying protocols should not be affected and each client implementation should locally populate pubsub topic fields with the shards hashed from content topics received via the API.

**Priority**: Critical for launch

**Comment by chair28980** [comment]
@SionoiS we think this might already be complete, can you close if this is the case. Thank you!

**Comment by SionoiS** [comment]
This has been completed. See #1846
