### ISSUE TITLE
feat: Proper bandwidth metrics per shard

### ISSUE THREAD

**Issue by chair28980** [waku-org/nwaku#1945]
This tracks work to ensure we have proper metrics and network-wide dashboard available to monitor bandwidth usage per shard. This should also consider other types of metrics (e.g. number of applications/content topics per shard, node distribution, etc.)

**Comment by Ivansete-status** [comment]
Closing as completed
The metrics can be seen in Grafana: https://grafana.infra.status.im/d/qrp_ZCTGz/nim-waku-v2?orgId=1&refresh=30s

e.g.:
![image](https://github.com/user-attachments/assets/4adbeeae-0406-44d7-820d-fa187f10f5ae)
