### ISSUE TITLE
feat: Failsafe mechanism (guide) for BW limiting

### ISSUE THREAD

**Issue by chair28980** [waku-org/nwaku#1946]
This tracks work to guide node operators on how to configure third party tools on various platforms to set a hard limit on Waku bandwidth usage as a failsafe mechanism.

**Comment by chair28980** [comment]
cc @richard-ramos, should this issue be opened in `gowaku` as well?

**Comment by Ivansete-status** [comment]
Morning @chair28980 , sorry but I don't fully understand what we should do in the following task.

@NagyZoltanPeter commented to me the following:
> As part of the DOS protection deliverable anyone can track relay traffic over each supported shard and the traffic on each non-relay supported protocols. That would represent the guide for the node operators. By looking at those metrics, the node operators can properly decide the limits and protocols they are willing to support.

e.g.1:
![image](https://github.com/user-attachments/assets/ca83ed24-b1d8-483a-8e75-d0dbf267443d)

e.g.2:
![image](https://github.com/user-attachments/assets/9caec1c5-3807-4ed2-8157-e1bad1b1c51a)

There are panels for all protocols. That can serve as a guidance for node operators.

**Comment by chair28980** [comment]
> By looking at those metrics, the node operators can properly decide the limits and protocols they are willing to support.

@Ivansete-status does it feel like the work that has been shipped cover the requirements? Sorry I have lost a bit of context since the issue was originally written. Are there instructions available for operators to follow if they find the need to set a hard limit on bandwidth usage?

**Comment by Ivansete-status** [comment]
> @Ivansete-status does it feel like the work that has been shipped cover the requirements? Sorry I have lost a bit of context since the issue was originally written. Are there instructions available for operators to follow if they find the need to set a hard limit on bandwidth usage?

Thanks for the comments on that!
I think it would cover it if the node operators could see those metrics. Then, I believe the only outstanding task is to add those panels to the `nwaku-compose` repo. @NagyZoltanPeter - may you kindly do that when you have some time plz :)? Once this is done, we could close that one because node operators will have the tools to learn the normal values.

**Comment by Ivansete-status** [comment]
@NagyZoltanPeter - Thank you so much for that !
@chair28980 - I think we can close that point then

**Comment by chair28980** [comment]
@Ivansete-status sounds good!
