### ISSUE TITLE
feat: Migrate deployments to PostgreSQL

### ISSUE THREAD

**Issue by chair28980** [waku-org/nwaku#1948]
Ensure that new and existing Waku fleets use PostgreSQL by default.

Priority: Critical for launch

**Comment by Ivansete-status** [comment]
Hi @chair28980 !
May kindly elaborate a bit more on this point? I can't quite remember why we need that and I was assuming that the _PostgreSQL_ was specifically interesting from the _Status_ point of view.
( cc @jm-clius to shed some light on this .)

**Comment by jm-clius** [comment]
> was specifically interesting from the Status point of view

This is true, so as long as the Status fleets are working as expected with PostgreSQL, migrating other deployments are not critical. I would say though that the new fleets (for the Waku Network, for example) should use postgresql to simplify what we maintain and support, but I think this is already the case.

**Comment by fryorcraken** [comment]
> > was specifically interesting from the Status point of view
> 
> This is true, so as long as the Status fleets are working as expected with PostgreSQL, migrating other deployments is not critical. I would say though that the new fleets (for the Waku Network, for example) should use postgresql to simplify what we maintain and support, but I think this is already the case.

Is this comment still valid considering the complete from infra regarding SQLite database sizes? @jm-clius @Ivansete-status

**Comment by Ivansete-status** [comment]
**Weekly Update**

- _achieved_: Preparing environment to stress one single database with multiple _Postgres_ clients writing and reading simultaneously.
- _next_: Extend _Postgres_ benchmarking report from previous results and start analyzing the performance of `status.test` fleet where three nodes will use one single database.

**Comment by Ivansete-status** [comment]
> Is this comment still valid considering the complete from infra regarding SQLite database sizes? @jm-clius @Ivansete-status

I think it is still valid. We have the "size" retention policy for _SQLite_ database which can be helpful to simplify the maintenance on fleets != `status.*`

**Comment by fryorcraken** [comment]
> I think it is still valid. We have the "size" retention policy for SQLite database which can be helpful to simplify the maintenance on fleets != status.*

As long as infra is happy.

**Comment by Ivansete-status** [comment]
I will close this because I don't see a clear need to change the current `wakuv2.*` archive system, for instance.
On the other hand, Jakub doesn't consider this migration (_SQLite_ -> _Postgres_) very interesting. Instead, he considers we need to reduce the number of fleets ( @jakubgs - correct me if I said something inaccurate .)

( cc @chair28980 )

**Comment by chair28980** [comment]
Closing in favor of work covered in 2024 Milestone scope.
