### ISSUE TITLE
feat(rest): Add /health endpoint to rest api

### ISSUE THREAD

**Issue by alrevuelta** [waku-org/nwaku#1988]
### Problem
nwaku has a bunch of things happening under the hood that are required for the node to work properly. Some of them are:
* healthy amount of peers
* rln in sync to the latest head
* all services mounted and running

However we don't have a `/health` endpoint that returns such information. We need some kind of readyness probe.

### Suggested solution

- [ ] Add new `/health` endpoint in the rest api that returns `true` if the node is ready and `false` if not. By now its ok to just check if rln is in sync with the latest head. Similar to [this](https://ethereum.github.io/beacon-APIs/?urls.primaryName=v2.3.0#/Node/getHealth)

**Comment by NagyZoltanPeter** [comment]
**Weekly Update**

- _achieved_: Feature /health endpoint added. PR merged: https://github.com/waku-org/nwaku/pull/2011
