### ISSUE TITLE
feat(relay): bandwidth constrained validator 

### ISSUE THREAD

**Issue by rymnc** [waku-org/nwaku#1992]
### Problem
The bandwidth constrained validator was removed from rln-relay in https://github.com/waku-org/nwaku/pull/1966

In an effort to make mounting and execution of validators sequentially, the dependency tree would be better off with a directory called `waku_validators`, as @Ivansete-status mentioned in https://github.com/waku-org/nwaku/pull/1966#pullrequestreview-1605063474  

### Suggested solution
Create a `waku_validators` directory, and import all the validators from different parts of waku_node into it.

### Alternatives considered
Tried upstreaming the ordered validators to nim-libp2p - https://github.com/status-im/nim-libp2p/pull/945

### Additional context
- none

### Acceptance criteria
- [ ] bandwidth constrained validator added to the waku_validators directory
- [ ] new waku_validators directory that imports all validators and inserts them sequentially

**Comment by chair28980** [comment]
Closing as duplicate #1938
