### ISSUE TITLE
chore: Extend node isReady with more mature checks and result returned.

### ISSUE THREAD

**Issue by NagyZoltanPeter** [waku-org/nwaku#2019]
### Background
Current waku_node.isReady is just checking RLN readiness if mounted. Also it is an issue it can just return a yes/no state but does not capable to tell a more detailed information about node state.

### Details
Suggestion is, that isReady shall check readiness of each configured protocol and features and return back with a processable list of result about state of each separate configured
- protocol
  - initializing
  - healthy
  - malfunction

### Acceptance criteria
Detailed health info can be retrieved from the node.

**Comment by jm-clius** [comment]
Roughly makes sense as an idea to me. Would this give a similar result as to someone using the waku canary externally might obtain?

**Comment by NagyZoltanPeter** [comment]
I think this issue is quite the duplicate of #2020. It is better close this and carry on with the other issue.
cc: @chair28980
