### ISSUE TITLE
chore: detailed json report on /health endpoint

### ISSUE THREAD

**Issue by NagyZoltanPeter** [waku-org/nwaku#2020]
### Background
Currently /health endpoint relies on waku_node.isReady status retrieve, thus can only return a healty/not healty/error response.

### Details
In sync with https://github.com/waku-org/nwaku/issues/2019 it is necessary to extend /health endpoint with a more detailed json response that corresponds isReady result.

### Acceptance criteria
All protocols/features configured are returning exact state upon get request on /health endpoint.

**Comment by NagyZoltanPeter** [comment]
@alrevuelta, @jm-clius, @vpavlin or basically anyone give your thoughts!
This is a follow up task based upon rln /health work discussed during PR review.

**Comment by SionoiS** [comment]
A lot of the components/sub-systems have a `started` bool maybe return that for each?

**Comment by NagyZoltanPeter** [comment]
> A lot of the components/sub-systems have a `started` bool maybe return that for each?

My problem is that according to what a node can state it is healthy or not.

My initial suggestion is, that we should examine the startup configuration of the node and being able to check if all necessary part of the system were able to set up. 
Also we might maintain futures on completeness of setting up.

But there are a bit more to think of like:
Is a relay protocol is healthy is there is no connected peers yet?
Should we check if storage limit exceed of store protocol?
What about subscription register limit exceeded?

What granularity do we need and what is the minimum features present we can say in general the node is healthy/operating?

@SionoiS, @jm-clius, @alrevuelta, @vpavlin, @chaitanyaprem, @Ivansete-status, @fryorcraken  WDYT?

**Comment by Ivansete-status** [comment]
> My initial suggestion is, that we should examine the startup configuration of the node and being able to check if all necessary part of the system were able to set up.

Isn't it enough to just stop the node if anything that was configured to set, didn't setup properly? For example, if the user configures `Store` + `Postgres` but there is no connectivity with the database, then the `wakunode2` stops immediately.

> Is a relay protocol is healthy is there is no connected peers yet?
Should we check if storage limit exceed of store protocol?
What about subscription register limit exceeded?

These are super interesting questions but we can delegate their responses later. I mean, I suggest first of all implementing the "health" template API and later each protocol implementation will take care of its own "nim-API-health-request".

Aside from that, I suggest a possible response skeleton:

"healthy" response:
```
{
  "global_health": {
    "is_healthy": true,
    "unhealthy_protocols": []
  }
}
```

"unhealthy" response:
```
{
  "global_health": {
    "is_healthy": false,
    "unhealthy_protocols": [
      {
        "protocol_name": "store",
        "reason": "not enough space"
      },
      {
        "protocol_name": "relay",
        "reason": "no peers connected"
      },
      {
        "protocol_name": "peer_exchange",
        "reason": "no peers connected"
      }
    ]
  }
}
```

**Comment by vpavlin** [comment]
I like this

> Isn't it enough to just stop the node if anything that was configured to set, didn't setup properly?

Yes please! Let's review current setup process and make sure this is the case - then really /health can be only exist in 4 states

1. unreacheable (node is not up)
1. starting
1. healthy
1. unhealthy because of protocol X

In case of hitting any unrecoverable error, the node should stop anyway, so the 4. is questionable there, but if it is just intermittent issue, then it would be useful

**Comment by Ivansete-status** [comment]
related issue: https://github.com/waku-org/nwaku/issues/2270

@chair28980 - we can prioritize this task to start tackling it after [migrate node initialization logic from app](https://github.com/waku-org/nwaku/issues/2441) is made.

( commented in a meeting with @NagyZoltanPeter )
