### ISSUE TITLE
bug: DB user_version  is not set on database init

### ISSUE THREAD

**Issue by vpavlin** [waku-org/nwaku#2036]
### Problem

We are currently not setting `user_version` (AKA schema version) on DB initialization. This results in migration issues, which we are currently working around using the code in #2031 

### Impact

After the temporary fix applied in #2031, we should not get in trouble for now, but we need to revisit this and fix it properly - i.e. initialize the `user_version` to the correct schema version

### To reproduce
If you can reproduce the behavior, steps to reproduce:
1. Run a fresh `wakunode2`
2. Check the `user_version` in DB

### Expected behavior

`user_version` in DB matches the value in code

### nwaku version/commit hash
State the version of `nwaku` where you've encountered the bug or, if built off a specific commit, the relevant commit hash. You can check the version by running `./wakunode2 --version`.
- all versions up to v0.20.0 (included)

**Comment by chair28980** [comment]
Per discussion during nwaku pm 2024-01-02, closing issue as we will likely store the schema version within a separate table, per @richard-ramos suggestion.
