### ISSUE TITLE
feat: RLN support for Nwaku-Compose

### ISSUE THREAD

**Issue by chair28980** [waku-org/nwaku#2051]
Requirements:

Add rln metrics in grafana
Mount database volume
Add new flags for rln

migrated from https://github.com/waku-org/nwaku-compose/issues/5

**Comment by alrevuelta** [comment]
flags:

      --rln-relay=true \
      --rln-relay-dynamic=true \
      --rln-relay-cred-password=password \
      --rln-relay-cred-path=/xxxx.json \
      --rln-relay-tree-path=/data/rln_tree.db \
      --rln-relay-eth-contract-address=0xxxxx  \
      --rln-relay-eth-client-address=ws://xxxxx:9558


optional by now. without them the node will be able to just rely messages, not publish.
* rln-relay-cred-password
* rln-relay-cred-path

**Comment by Ivansete-status** [comment]
Notice that this feature is in the end being tackled by @gabrielmer :fire: I re-assing that to him.

**Comment by vpavlin** [comment]
Maybe this has been discussed, but just my 2c:

* make the whole set of parameters optional by wrapping it in a condition dependent on an env var being set (like certs setup with `DOMAIN`)
* Allow passing in `password`, `cred-path`, and `client-address`
* I am not sure about contract - that should not change often and if you are developing against different contract, you can always override it in `EXTRA_ARGS`

WDYT @alrevuelta ?

**Comment by gabrielmer** [comment]
**Weekly Update**

- _achieved_: finished addressing feedback
- _next_: task is blocked until there's an easier method for users to register RLN credentials

**Comment by chair28980** [comment]
Blocked: Need better/easier way to create RLN credentials.
