### ISSUE TITLE
bug: nwaku connects to nodes in other cluster when using dns-disc

### ISSUE THREAD

**Issue by alrevuelta** [waku-org/nwaku#2054]
When using

```
./build/wakunode2 --relay=true --dns-discovery=true --dns-discovery-url=enrtree://AOGECG2SPND25EEFMAJ5WF3KSGJNSGV356DSTL2YVLLZWIV6SAYBM@prod.nodes.status.im --discv5-discovery=true --log-level=INFO --pubsub-topic=/waku/2/rs/10/5
```

nwaku connects to all 6 discovered nodes via dns-disc. But as per `pubsub-topic=/waku/2/rs/10/5`, these peers shouldn't be compatible since they use another cluster.

**Comment by SionoiS** [comment]
Whatever we decide to do here. We'll need good error messages. When a user specify some options and the code reject it, better be explicit about why.
