### ISSUE TITLE
bug: light push response is empty when meta field is too large

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/nwaku#2059]
### Problem

When js-waku client tries to use light push with a waku message that has large `meta`, nwaku sends an empty response back.

Expected: an error in the light push response to point towards the payload size issue.

### To reproduce
If you can reproduce the behavior, steps to reproduce:
1. Start nwaku with light push
2. Send a light push rpc request that contains a large `meta`
3. get an empty rpc light push response

### Expected behavior

rpc light push response contains:
```
is_success = false
info = "<error message about meta or field>"
```

### Screenshots/logs
[wakunode_Waku_Light_Push_[node_only]_Fails_to_push_message_with_large_meta.log](https://github.com/waku-org/nwaku/files/12679418/wakunode_Waku_Light_Push_.node_only._Fails_to_push_message_with_large_meta.log)

```
ERR 2023-09-21 02:20:22.908+00:00 failed to decode rpc                       topics="waku lightpush" tid=1 file=protocol.nim:43
```

### nwaku version/commit hash
v0.19.0

**Comment by jm-clius** [comment]
Almost certainly closed by any fix for https://github.com/waku-org/nwaku/issues/1641

**Comment by fryorcraken** [comment]
Yes confirmed
