### ISSUE TITLE
chore: distinguish between content topic and pubsub topic throughout the codebase

### ISSUE THREAD

**Issue by s-tikhomirov** [waku-org/nwaku#2084]
### Background
There are two similar but distinct types of entities called "topic": pubsub topics and content topics. It has been confusing for me to make sense of the codebase if a variable is simply names `topic`, and it's not immediately clear whether it's a content topic or a pubsub topic.

For instance, while working on #1641, I was confused as to what kind of topic `topic` is here:

https://github.com/waku-org/nwaku/blob/3264a4f5877203ba085f1a4e8e02e4ffc6ce9249/tests/test_waku_lightpush.nim#L60

(It becomes obvious if you look a few lines earlier at the definition of `topic`, but ideally such minutiae shouldn't occupy anyone's brain cycles.)

### Details
Rename most or all variables named `topic` to signify whether it's a content topic or a pubsub topic.

### Acceptance criteria
All `topic` variables where confusion is possible are named explicitly. It's up for discussion in which cases conciseness is more important than explicitness, but I would err on the side of the latter.

**Comment by alrevuelta** [comment]
Agree, thanks for bringing this up.

**Comment by chair28980** [comment]
Duplicate exists for this issue per @SionoiS, can you link the issue here :)

**Comment by s-tikhomirov** [comment]
Oh. My bad, didn't check for duplicates! Indeed, distinguishing via the type system would be even better. Closing this in favor of #2021.
