### ISSUE TITLE
chore: project wide consistent sharding terminology

### ISSUE THREAD

**Issue by SionoiS** [waku-org/nwaku#2102]
### Background
With the recent changes from autosharding to the new metadata protocol. We should ensure that the terminology used throughout the code base is consistent. Specifically regarding the new term `cluster id`

### Details
- Rename shard cluster indices or similar terms to cluster Id
- Rename shard index/number or similar to shard id

### Acceptance criteria
- [ ] Rename all the things!

**Comment by alrevuelta** [comment]
related to this change https://github.com/vacp2p/rfc/pull/623
