### ISSUE TITLE
bug: empty LOG_LEVEL in Jenkins doesn't result in TRACE level

### ISSUE THREAD

**Issue by yakimant** [waku-org/nwaku#2107]
### Problem
If LOG_LEVEL is empty in Jeknins, it doesn't result in TRACE level as in description:

```
15:35:14  + docker build -t wakuorg/nwaku:deploy-shards-test --label=commit=c74abe13 --build-arg=MAKE_TARGET=wakunode2 --build-arg=NIMFLAGS=-d:disableMarchNative -d:chronicles_colors:none -d:insecure -d:postgres --build-arg=LOG_LEVEL= --target=prod .
...
15:40:47  #13 [nim-build 7/7] RUN make -j$(nproc) ${NIM_COMMIT} wakunode2 LOG_LEVEL= NIMFLAGS="-d:disableMarchNative -d:chronicles_colors:none -d:insecure -d:postgres"
...
15:41:48  #13 75.10 [NimScript] exec: nim c --out:build/wakunode2  -d:disableMarchNative -d:chronicles_colors:none -d:insecure -d:postgres --verbosity:0 --hints:off -d:git_version="v0.20.0-rc.0-50-gc74abe" -d:release --passL:librln_v0.3.4.a --passL:-lm apps/wakunode2/wakunode2.nim
```

See
- https://github.com/waku-org/nwaku/blob/master/ci/Jenkinsfile.release
- https://github.com/waku-org/nwaku/blob/master/Dockerfile
- https://github.com/waku-org/nwaku/blob/master/Makefile
- https://github.com/waku-org/nwaku/blob/master/waku.nimble

**Comment by chair28980** [comment]
@yakimant can you elaborate a bit more on what the expected behavior vs the actual outcome? Is this a Jenkins issue, or Docker issue?

**Comment by yakimant** [comment]
This is a Jenkins issue. TRACE should be a default, when not specified, but it's not the case.

I need to investigate though, what is the default current log level.

**Comment by Ivansete-status** [comment]
I think we need to prioritize that one @chair28980 because that will help us debug possible issues. For example, investigating an certificate issue ([link](https://discord.com/channels/1110799176264056863/1169592437770035230)) it was not straightforward to get it.

**Comment by jakubgs** [comment]
Okay, i see, this flag actually makes log levels available at runtime. So the description for the option should be:
```
Defined log levels to be made available at build time.
```
No need to list the default.

**Comment by yakimant** [comment]
@chair28980, @Ivansete-status, do you want this `chronicles_log_level` to be `TRACE` by default for all our fleets - prod/test, status/shards/wakuv2/waku?

**Comment by yakimant** [comment]
https://github.com/waku-org/nwaku/pull/1748

**Comment by jakubgs** [comment]
The `LOG_LEVEL` variable name is terrible. It should be something like `LOWEST_LOG_LEVEL`, `ALLOWED_LOG_LEVEL` or `ENABLED_LOG_LEVEL` or similar.

**Comment by Ivansete-status** [comment]
> prod/test, status/shards/wakuv2/waku?

Thanks so much for looking into this issue :heart: !
`TRACE` is too much.

For all our fleets I vote:
prod -> `INFO`
test -> `DEBUG`

( wdyt @jm-clius @alrevuelta ? )

**Comment by jm-clius** [comment]
> TRACE is too much.
Note that this is about the level of logs that gets compiled into the binary (i.e. that will be available to log at), not the level which actually gets logged (which is a runtime config using `--log-level` parameter).
The default here for all deployments should indeed be `TRACE`.

Runtime log setting (`--log-level`) should preferably be `DEBUG` for both `prod` and `test` (I think it is) - I think we lose too much traceability if using only `INFO`.

**Comment by jakubgs** [comment]
It already is `debug`:
https://github.com/status-im/infra-status/blob/ae91342f44ac981e9130d2c468c5dcba18cd8886/ansible/group_vars/status.yml#L7

**Comment by yakimant** [comment]
Works great:
![Screenshot 2023-11-08 at 17 22 30](https://github.com/waku-org/nwaku/assets/1529006/37a1ae49-9ae6-48a3-a792-ff8d432c54ad)
