### ISSUE TITLE
bug: refreshing a waku relay subscription crashes

### ISSUE THREAD

**Issue by AlejandroCabeza** [waku-org/nwaku#2114]
### Problem
When using Waku Relay, if, after subscribing to a topic, you subscribe to the same topic without unsubscribing first, it errors out with a segmentation fault.
It doesn't matter whether the handler passed to the `subscribe` method is the same as the previous one, or different.

### Impact
Minor

### To reproduce
1. Subscribe to any topic.
2. Subscribe again to the same topic as before, without unsubscribing.

The error happens, specifically on `libp2p/protocols/pubsub/pubsub.nim:316`, line `let fut = handler(topic, data)` in `handleData`.

### Expected behavior
In my opinion, handle it appropriately: Either allowing a resubscription, or gracefully denying it.

### Logs
Output when running:
```
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Segmentation fault
Error: execution of an external program failed
```

### nwaku version/commit hash
- Nwaku Version Output: `version / git commit hash: v0.19.0-rc.1-48-gea31b`
- Commit Hash: One branch off of `d864db3fb546c3eb7a1cf76e42c5fd33751f8622`

**Comment by alrevuelta** [comment]
Can confirm that when refreshing a subscription, eg:

```
...
node.subscribe(pubsubTopic, hander1)
...
node.subscribe(pubsubTopic, handler2)
```

There is a segfault.

Reason is here: https://github.com/status-im/nim-libp2p/blob/master/libp2p/protocols/pubsub/pubsub.nim#L467-L469. Since we wrap/merge all validators into a single a single one, in that code we can see that if its already subscribed, then the new validator is added to the existing ones. In our case this doesn't make sense, since we would be adding twice the wrapped validator. nim-libp2p `subscribe(pubsubTopic, handler)` is not idempotent, so we should "reset" it.

As a solution, i would suggest "cleaning the subscription" before. In other words, just adding `procCall GossipSub(w).unsubscribeAll(pubsubTopic)` before we attempt to subscribe.

@rymnc mind having a look since its related to the "merge validators"?

**Comment by AlejandroCabeza** [comment]
I gotta point out, though, that by running `unsubscribeAll` we would also be removing all registered handlers. 
Ideally, at least the way I understand this, is that you could register however many handlers you want for one pubsub topic. By running `unsubscribeAll` before all `subscribe` we would be limiting it to one.
Would we consider this intentional?

**Comment by rymnc** [comment]
> Can confirm that when refreshing a subscription, eg:
> 
> ```
> ...
> node.subscribe(pubsubTopic, hander1)
> ...
> node.subscribe(pubsubTopic, handler2)
> ```
> 
> There is a segfault.
> 
> Reason is here: https://github.com/status-im/nim-libp2p/blob/master/libp2p/protocols/pubsub/pubsub.nim#L467-L469. Since we wrap/merge all validators into a single a single one, in that code we can see that if its already subscribed, then the new validator is added to the existing ones. In our case this doesn't make sense, since we would be adding twice the wrapped validator. nim-libp2p `subscribe(pubsubTopic, handler)` is not idempotent, so we should "reset" it.
> 
> As a solution, i would suggest "cleaning the subscription" before. In other words, just adding `procCall GossipSub(w).unsubscribeAll(pubsubTopic)` before we attempt to subscribe.
> 
> @rymnc mind having a look since its related to the "merge validators"?

I think the issue lies with the handlers and not the validators, I'm debugging it right now. https://github.com/waku-org/nwaku/blob/c70a300f26ef3c38ccc35893cea2ef6f2b4694bd/waku/waku_relay/protocol.nim#L234-L236 ensures that the ordered validator is added only once per pubsub topic.

**Comment by rymnc** [comment]
Looked at nim-libp2p a little more, 
https://github.com/status-im/nim-libp2p/blob/66f9dc9167f5ba8e5b6867be54f3e63052b93797/libp2p/protocols/pubsub/pubsub.nim#L314-L318
checks if the handler is nil, before calling it, so it *shouldn't* segfault here 🤔

**Comment by AlejandroCabeza** [comment]
After talking with@rymnc, I reinvestigated the test case and I found out it was an issue caused by me not handling correctly the future in the handler: There was an instance where the future was calling `complete` when it was already complete.
