### ISSUE TITLE
chore: reorganize rest-api types

### ISSUE THREAD

**Issue by NagyZoltanPeter** [waku-org/nwaku#2121]
### Background
While rest api nwaku implementation is segregated by endpoints they implements their own types one-by-one.
This can be misleading adds complexity by code duplication and does not reflects one rest-api for Waku node as common.

### Details
Ongoing task https://github.com/waku-org/nwaku/issues/2120 track normalize of openapi specifications and documentation.
This task tries to address and follow up that changes.

[ ] Reorganize types into common place
[ ] Remove type duplications
[ ] Enforce common naming scheme
[ ] Easy marshalling/de-marshalling code for api types, remove duplications of code/copy-pastes

### Acceptance criteria

[ ] No change in functionality
[ ] All tests are passed
[ ] Alignment with go-waku and js-waku done in case of naming changes on api level.

**Comment by chair28980** [comment]
@NagyZoltanPeter I assigned this issue to you please update if thats incorrect, thank you!

**Comment by NagyZoltanPeter** [comment]
**Weekly Update**

- _achieved_: Enhancements on Rest request error handling.
- _next_: Finalize api spec and doc after PR review. Work in progress: rest api type reorganization. RFC changes to enhance light-push failure response.
- _blocking_: Fixing found issues during release.

**Comment by NagyZoltanPeter** [comment]
Block while come to decision on rest api spec changes.
Also it is low prio compared to gen0 tasks.

**Comment by NagyZoltanPeter** [comment]
Downprio!
Rest api specification is moved to https://github.com/waku-org/waku-rest-api
Original PR of spec effort: https://github.com/waku-org/nwaku/pull/2124 had several comments that effects rest-api types and interfaces. Until those are not agreed and applied to the specification this issue can be postponed.

**Comment by NagyZoltanPeter** [comment]
- Time gone by:
 - rest api spec is moved and has its own reference UI.
 - API types had been evolved and necessary reorg had been done meanwhile.

This is not applicable for current code base.
