### ISSUE TITLE
feat: add rln to waku simulator instance

### ISSUE THREAD

**Issue by alrevuelta** [waku-org/nwaku#2143]
We have simulator.waku.org with latest master running, however it runs with just relay.

Task:
- [ ] Enable RLN in simulator.waku.org. See https://github.com/waku-org/waku-simulator#infrastructure

Since using onchain rln migt be too heavy, we can start by just using static rln. As simple as follows, and doesn't require an external eth node.
```
            --rln-relay=true
            --rln-relay-dynamic=false
            --rln-relay-membership-index=0
```

Note that traffic injection would need to be modified, since the current tool doesn't allow to publish rln messages.

**Comment by gabrielmer** [comment]
**Weekly Update**

- _achieved_: learnt about waku-simulator's inner workings and got the background required to integrate RLN to it. Added service that generates traffic to the nodes via their REST APIs. Investigated and tested different ways of approaching the RLN integration.
- _next_: get RLN to work and add Grafana dashboards with RLN data

**Comment by gabrielmer** [comment]
**Weekly Update**

- _achieved_: integrated RLN, added Grafana dashboards, tested, merged and deployed
