### ISSUE TITLE
bug: Can't reconnect relay client after restart

### ISSUE THREAD

**Issue by AlejandroCabeza** [waku-org/nwaku#2145]
### Problem
After restarting the Relay client, it can't connect to a previously connected client, and thus not able to receive/send messages from/to it.
Connecting to a relay client it wasn't connected to (before restarting) does work.

### Impact
...

### To reproduce
1. Instantiate two relay clients.
2. Subscribe them to the same pubsub topic.
3. Connect the two of them with `peerManager.connectRelay`.
4. Run `stop` and `start` in one (or both) the nodes and their respective switches.
5. Running `connectRelay` and publish a message in their subscribed pubsub topic. Running `connectRelay` leads to `peer_manager.nim:connectRelay:179`, a timeout error.
6. Message won't arrive to the other relay client.

You can also check the test case named `"Relay can receive messages after reboot and reconnect"` in `waku_relay/test_protocol.nim`. Remember to rename it from `xasyncTest` to `asyncTest` before running, otherwise it'll be skipped.

### Expected behavior
After restarting the client, I can successfully run `connectRelay` and then send/receive messages with the connected client.

### nwaku version/commit hash
- Wakunode: `v0.20.0-rc.0-90-ga6d31c`
- Git: `00aa01b65c28aa16ca06efefba9b08ae7184eb35`
- PR: https://github.com/waku-org/nwaku/pull/2101

**Comment by chair28980** [comment]
- Might be expected behavior when disconnecting/reconnecting

**Comment by keshzombie** [comment]
Is there a guide or instruction to delete the public.messages_backup table?

**Comment by Ivansete-status** [comment]
@AlejandroCabeza thanks so much for the masterpiece issue. It is very well described and is indeed something we need to enhance. Also, notice that this issue needs the following PR to be merged https://github.com/vacp2p/nim-libp2p/pull/1082
