### ISSUE TITLE
bug: store query cursor misbehaving for specific cursors

### ISSUE THREAD

**Issue by fbarbu15** [waku-org/nwaku#2147]
### Problem
Seems that a small bug was introduced in nwaku master recently related to store protocol cursor.
The issue is that for some specific cursors, the store query returns messages including the one matching the cursor index.
For example if there are 35 messages and the cursor is set at the index 19

### To reproduce
If you can reproduce the behavior, steps to reproduce:

1. Have 35 messages in nwaku (I used post_waku_v2_relay_v1_message)
2. Create the cursor at posibion 19 (I used https://github.com/waku-org/js-waku/blob/master/packages/core/src/lib/store/index.ts#L408-L430 )
3. Send a history query with cursor set a position 19 (for this I used js-waku)
4. The query returns 16 messages
5. The first message is at index 19

### Expected behavior
The query should return 15 messages
The first message is at index 20

### nwaku version/commit hash
This only happens for nwaku master: wakuorg/nwaku:deploy-wakuv2-test 
It doesn't reproduce with lastest release: wakuorg/nwaku:v0.21.0

### Additional context
This happens for specific cursors. For example in the above scenario if the cursor is set at 20 instead of 19 the bug disappears

Issue was introduce on 19 Oct

at 12:27 it was passing: https://github.com/waku-org/js-waku/actions/runs/6572525428/job/17853800283#step:7:21116
at 14:33 is was failing: https://github.com/waku-org/js-waku/actions/runs/6573900428/job/17857850223#step:7:51123

**Comment by ABresting** [comment]
Most likely the new PR #2159 will resolve it since the issue seems to be with `proc messageDigest()` /`messageHash` computation.

**Comment by fbarbu15** [comment]
I've tested right now with quay.io/wakuorg/nwaku-pr:2159 (the image build from mentioned PR) and bug still reproduces unfortunately

**Comment by ABresting** [comment]
The PR in jsWaku https://github.com/waku-org/js-waku/pull/1691 closes this bug.
This was an issue of misaligned digest/hash computation. Now with the jsWaku PR, it is aligned with nWaku and goWaku.

**Comment by ABresting** [comment]
closing this PR since with the change in direction regarding the database attributes it has been decided that we do not make change in current `computeDigest` function in nWaku. More on this [here](https://github.com/waku-org/research/issues/46)
