### ISSUE TITLE
feat: add pubsub topic to msgID function

### ISSUE THREAD

**Issue by richard-ramos** [waku-org/nwaku#2184]
### Problem
Currently the msgID function only takes into account the pubsub message payload. Ideally it should take into account the pubsub topic as well.
https://github.com/waku-org/nwaku/blob/52759faa0341e5463afe6fb8cf51027216cc5d3b/waku/waku_relay/message_id.nim#L31-L33
See discussion in https://github.com/waku-org/go-waku/pull/854#discussion_r1378168774 .

**Comment by Ivansete-status** [comment]
Hey @richard-ramos !
We had a DM chat about this issue. I wanted to confirm whether we still need it or not. From our conversation, I got the impression that this was a temporary proposal. Correct me if I'm wrong.

On the other hand, I see that the pubsub topic isn't being considered from the `go-waku` point of view (also, correct me if I'm wrong.)

![image](https://github.com/waku-org/nwaku/assets/128452529/388e9f5e-9db4-4619-b3fb-66aad9e8c313)
( https://github.com/waku-org/go-waku/blob/master/waku/v2/protocol/relay/config.go#L39-L41 )

**Comment by Ivansete-status** [comment]
Closing as per @richard-ramos on Discord:

> Regarding #2184, at least from go-waku / status PoV, i think we can close it. This issue was opened because back then, there was this idea of implementing a bridge for pubsub topics so the default pubsub topic would send messages to the default shard 16/32 and viceversa, but in the end it was no longer necessary.
