### ISSUE TITLE
bug: lack of error checking in publish

### ISSUE THREAD

**Issue by alrevuelta** [waku-org/nwaku#2190]
If I post a message using autosharding but with a wrong `contentTopic` like the one below.

```
 curl -X POST "http://127.0.0.1:8645/relay/v1/auto/messages" \
 -H "content-type: application/json" \
 -d '{"payload":"ZXhhbXBsZQ==","contentTopic":"bbbbb"}'
```

It errors silently:
```
2023-11-07 13:53:57 ERR 2023-11-07 12:53:57.141+00:00 Autosharding error                         topics="waku node" tid=1 file=waku_node.nim:322 error="invalid format: topic must start with slash"
```

But the API call still returns OK, which is obviously wrong, since the message wasn't published.

Mainly due to this: https://github.com/waku-org/nwaku/blob/6da1aeec5370bb1c116509e770178cca2662b69c/waku/node/waku_node.nim#L320-L323

Solution:

- [ ] Return an error in the REST API if the message was not published due to an autosharding error.

**Comment by gabrielmer** [comment]
**Weekly Update**

- _achieved_: reproduced, investigated and started improving error handling
- _next_: continue with the implementation

**Comment by gabrielmer** [comment]
**Weekly Update**

- _achieved_: fixed compilation errors, got it to work and tested it
- _next_: add test cases to the codebase and open PR

**Comment by gabrielmer** [comment]
**Weekly Update**

- _achieved_: added test, fixed bug, started fixing non-compiling tests in dependent areas of the code
- _next_: finish adapting dependent tests to the new behavior and proc signatures
