### ISSUE TITLE
chore: add tests vectors for autosharding

### ISSUE THREAD

**Issue by SionoiS** [waku-org/nwaku#2197]
### Background
For language agnostic testing of the autosharding process. It would be good to add tests vectors.

### Details
List of content topic parts, the content topic, the resulting hash and the shard #

### Acceptance criteria
- [ ] .md files with many tests

@fryorcraken do test vectors belong in this repo or elsewhere?

**Comment by fryorcraken** [comment]
> @fryorcraken do test vectors belong in this repo or elsewhere?

Test Vectors should be part of the RFC

**Comment by chair28980** [comment]
Should be implemented once https://github.com/waku-org/nwaku/issues/2258 is shipped.
