### ISSUE TITLE
chore: improve logging terminology

### ISSUE THREAD

**Issue by SionoiS** [waku-org/nwaku#2213]
### Background
Remove the word topic from logging as it can be confusing. Look for any other confusing terminology too!

### Details
Instead of `topics="part of the code base"` it should be maybe `context="some part of the code base"`?

### Acceptance criteria
- [ ] logging pharsing updated

**Comment by chair28980** [comment]
Iceboxing per nwaku pm meeting 2023-11-21, language is dictated by nim-chronicles.

**Comment by SionoiS** [comment]
Closing as it can;t be done
