### ISSUE TITLE
bug: nwaku crashes in getAndHandleEvents() at group_manager.nim:308

### ISSUE THREAD

**Issue by Ivansete-status** [waku-org/nwaku#2217]
### Problem
A node with RLN enabled crashes. It is being asked to continuously publish messages throughout REST API.

I attach the last logs for further details:
[nwaku_crash_rln.txt](https://github.com/waku-org/nwaku/files/13357066/nwaku_crash_rln.txt)

### To reproduce
1. ssh to metal-01.he-eu-hel1.wakudev.misc.statusim.net  (sandbox machine)
2. follow the points 1. and 2. from https://github.com/waku-org/nwaku-compose/blob/e5d5ceba224a7a169d218d14db94c8034447132e/README.md
3. open another terminal in the sandbox machine and do `bash publich_msg.txt` (see attached script 
[publish_msgs.txt](https://github.com/waku-org/nwaku/files/13357132/publish_msgs.txt)
.)

It crashes after a few hours/minutes.

note: I used the `screen` CLI utility to preserve the Linux-terminal sessions in the sandbox machine so that I can go out and resume the session a few hours later from the place I left it.

**Comment by rymnc** [comment]
Hi, what commands did you use to run the nwaku node?
