### ISSUE TITLE
feat: HTTP REST API: Private API

### ISSUE THREAD

**Issue by NagyZoltanPeter** [waku-org/nwaku#2227]
### Problem
Formerly as being part of cover issue: https://github.com/waku-org/nwaku/issues/1076
That has been closed with implemented achievements while missing Private Rest API implemented. 

This issue is to continue tracking implementation of nim waku /private api.

**Comment by alrevuelta** [comment]
@NagyZoltanPeter Mind elaborating on whats missing here? And what is expected to be in `private`? You mean like "relay private API"?

**Comment by NagyZoltanPeter** [comment]
> @NagyZoltanPeter Mind elaborating on whats missing here? And what is expected to be in `private`? You mean like "relay private API"? cc @Ivansete-status

I remember it was not clearly specified, more a placeholder like. 
@jm-clius : Can you clearify?

**Comment by jm-clius** [comment]
Yes, this would have been the REST equivalent of the Relay Private API. The sole purpose of that API was to private encryption/decryption of Waku v1 payloads (and to relay such encrypted messages). We've deprioritised Waku v1 <> v2 compatibility and this functionality is not used in JSON RPC. In future something like this API could be used for Noise payloads, but this is not priority. I'd suggest closing this issue for now.

**Comment by NagyZoltanPeter** [comment]
> Yes, this would have been the REST equivalent of the Relay Private API. The sole purpose of that API was to private encryption/decryption of Waku v1 payloads (and to relay such encrypted messages). We've deprioritised Waku v1 <> v2 compatibility and this functionality is not used in JSON RPC. In future something like this API could be used for Noise payloads, but this is not priority. I'd suggest closing this issue for now.

I agree to close it!
cc: @chair28980
