### ISSUE TITLE
bug: SqliteDriver WakuMessage attribute saving

### ISSUE THREAD

**Issue by AlejandroCabeza** [waku-org/nwaku#2241]
### Problem
The `SqliteDriver` doesn't store the `ephemeral` attribute for `WakuMessage`.

### To reproduce
If you can reproduce the behavior, steps to reproduce:
1. Create a `WakuMessage` with `ephemeral: false`.
2. Store the `WakuMessage` using an `SqliteDriver`.
3. Retrieve the `WakuMessage` with the `SqliteDriver`.
4. The `WakuMessage`'s `ephemeral` attribute will be `true` because that's what it defaults to, as that attribute wasn't stored.

You can also check the test cases named `"Mixed messages"` and `"Only ephemeral Messages"` under the suite `"Ephemeral"` in the file `node/test_wakunode_store.nim`. Both tests are marked as `xasyncTest`, remember to rename them to `asyncTest` for them to not be ignored.

### Expected behavior
The `SqliteDriver` properly stores and retrieves the `ephemeral` attribute. Because there's no `ephemeral` attribute storage, it always retrieves any `WakuMessage` with `ephemeral: true`.

### nwaku version/commit hash
- Wakunode: v0.22.0-rc.0-26-g3dcfbf
- Git: 3dcfbf8e4c51aa71dfd90239b9747180b2399de4
- PR: https://github.com/waku-org/nwaku/pull/2240

### Additional Context
If you check the `put` method in `waku_archive/driver/sqlite_driver/sqlite_driver.nim:60` you can see there's no reference to the `ephemeral` attribute when executing the statement.

**Comment by Ivansete-status** [comment]
Thanks for this @AlejandroCabeza !

All the messages that are stored have `emphemeral=false` implicitly. Therefore, we should make sure that when retrieving `WakuMessage`s from any sort of storage, the `emphemeral` flag should be properly set to `false`.

I didn't check it in detail but this might be a quick fix.

**Comment by AlejandroCabeza** [comment]
After some talk between @Ivansete-status and I, and extra info from @jm-clius, this can be considered as working as expected.

There were two possible issues arising from this, which are now confirmed to work as expcted:
1. `SqliteDriver` doesn't store `ephemeral`
- Any stored message is implicitly `ephemeral=false`, and hence there's no need to store that attribute.
2. `SqliteDriver` stores `WakuMessage`s even if they have `ephemeral=true`
- The responsibility of filtering `WakuMessage`s with `ephemeral=true` does not lie with `SqliteDriver` but with `WakuArchive` (as can be seen [here](https://github.com/waku-org/nwaku/blob/b0c780528b5610f8b6c5e3784dc9faadcb7b6917/waku/waku_archive/archive.nim#L95)). Thus, any message passed to `SqlitDriver.put` will always be saved (as can be seen [here](https://github.com/waku-org/nwaku/blob/b0c780528b5610f8b6c5e3784dc9faadcb7b6917/waku/waku_archive/driver/sqlite_driver/sqlite_driver.nim#L61)), even if it's `ephemeral=true`.

Thus, we deem this issue as closed.
