### ISSUE TITLE
bug: failed to mount waku archive protocol when using postgres

### ISSUE THREAD

**Issue by jakubgs** [waku-org/nwaku#2242]
### Problem
Current `master` as well as `v0.22.0` release are stuck in a restart loop when using PostgreSQL database:
```
ERR 2023-11-23 12:37:19.449+00:00 4/7 Mounting protocols failed
    topics="wakunode main" tid=1 file=wakunode2.nim:89
    error="failed to mount waku archive protocol: error in mountArchive: failed execution of retention policy: failed to get Page size:"
```

### Impact
Can't use current codebase on `status.test` fleet being switched to PostgreSQL.

### To reproduce
Use Nim-Waku node with PostgreSQL.

### Expected behavior
It works.

### Screenshots/logs
If applicable, add screenshots or logs to help explain your problem.

### nwaku version/commit hash
Both `v0.22.0` and current `master`.

### Additional context
* https://github.com/status-im/infra-status/issues/37

**Comment by jakubgs** [comment]
I just checked and this issue appears in `v0.21.0` as well.

**Comment by jakubgs** [comment]
The `shards.test` fleet is running `aeb77a3e` which is current master but doesn't have this problem:
```
admin@store-01.do-ams3.shards.test:~ % d
CONTAINER ID   NAMES            IMAGE                              CREATED        STATUS
920badb37699   nim-waku-store   wakuorg/nwaku:deploy-shards-test   20 hours ago   Up 20 hours (healthy)

admin@store-01.do-ams3.shards.test:~ % d inspect wakuorg/nwaku:deploy-shards-test | grep commit
                "commit": "aeb77a3e",
```

**Comment by Ivansete-status** [comment]
Thanks for the detailed info!
We have a bug related to the "size" retention policy that doesn't work if the database doesn't exist.
```
method execute*(p: SizeRetentionPolicy,
                driver: ArchiveDriver):
                Future[RetentionPolicyResult[void]] {.async.} =
  ## when db size overshoots the database limit, shread 20% of outdated messages 

  # get page size of database
  let pageSizeRes = await driver.getPagesSize()
  let pageSize: int64 = int64(pageSizeRes.valueOr(0) div 1024)

  if pageSize == 0:
    return err("failed to get Page size: " & pageSizeRes.error)
 ```
Is something that we need to fix.

In order to allow the node to start, let's change to either the "time" or "capacity" retention policies:
e.g.
```
capacity:20000000
```

**Comment by jakubgs** [comment]
Good catch, thanks, will try this in a bit.

**Comment by jakubgs** [comment]
Indeed, I can confirm setting the retention not based on `size` does fix the issue at startup:
```
admin@node-01.do-ams3.status.test:~ % d
CONTAINER ID   NAMES      IMAGE                              CREATED         STATUS
3d6868ff0701   nim-waku   wakuorg/nwaku:deploy-status-test   2 minutes ago   Up 2 minutes (healthy)
```

**Comment by jakubgs** [comment]
Notes from call we had today with John, Hanno, Andrea, and Ivan:

* App devs and QA have issues with historical messages appearing very later, even days later.
  - This is most probably due to split-brain between SQLite DBs between nodes and connecting to different nodes.
* We need to solve this problem in 3 steps:
  1. Use one DB across multiple DCs to see if it works, since it's the simplest.
  2. Switch to some kind of multi-master or sync or master-slave with LB as a middle ground.
  3. Wait for waku to implement actual syncing between nodes on protocol level
* All of this is necessary since we have Status app dogfooding coming soon.
* Jakub is testing single DB in `status.test` and if it works we'll do the same for `status.prod`.
* Hanno believes the `shards.test` fleet setup with more than one waku node per DB in DC solves this problem.
  - This is actually not confirmed and is kinda speculation.
* Andrea wants a single DC `shards.dogfood` fleet to eliminate variables, as a stable reference point.
  - Jakub mostly agrees with this, as a good way to establish what works.
* Jakub would prefer if Hannos version was correct, and we could have separate DBs in different DCs.
  - If this doesn't work we'll need some kind of multi-master or syncing between DCs until waku implements it.
