### ISSUE TITLE
feat: migration script for PostgresSQL

### ISSUE THREAD

**Issue by ABresting** [waku-org/nwaku#2249]
### Problem

Currently, nWaku upgrades are easily done with SQLite due to smooth migration scripts. With Postgres the same feature is required, Postgres also falls on our future roadmap, so will be good to have it in due course of time. Currently, there are no migration scripts, hence upon node upgrade the new changes such as inclusion of `messageHash` attribute halt the node.

### Suggested solution

Since Postgres does not user PRAGMA type user-specific values. A simpler solution ca be using table/database comments, for eg. on top of `messages` database table in Postgres we can specify the version in the following way:

`postgres=# COMMENT ON TABLE messages IS 'Version 1';`

In the migration script, we can first check if there are migration schemas in Postgres directory, if yes then query for the version set in the table/database and run the schemas accordingly. Upon successful run update the version number comment to the target version.

### Alternatives considered

May be creating a version tracking table accompanied by stored procedures, but it is advisable in complex projects. 

WDYT @Ivansete-status @alrevuelta @richard-ramos @jm-clius 

### Acceptance criteria

- [ ] Migration is successful over the database schema. 
- [ ] Old table rows are populated correctly

**Comment by Ivansete-status** [comment]
Thanks for that @ABresting !

For the case of _Postgres_ we might also need to consider the infra team opinion (@jakubgs) because we might need to perform manual updates in the `status.*` fleets' database schema.

Note: Manual upgrades can be allowed by setting `--store-message-db-migration=false`

**Comment by jakubgs** [comment]
Honestly, migration tracking table sounds better to me. A comment is singular, so it only saves the current state, but a migrations history would be useful for debugging.

**Comment by ABresting** [comment]
Well, I hope that we design the tracking table such that the tracking table itself doesn't need migration!

**Comment by richard-ramos** [comment]
In go-waku we use http://github.com/golang-migrate/migrate which creates a table with the following structure: 
```
CREATE TABLE gowaku_schema_migrations (version uint64,dirty bool);
CREATE UNIQUE INDEX version_unique ON gowaku_schema_migrations (version);
```
And this table only has a single row indicating the current migration version of the database, and the `dirty` indicates whether the migrations failed to execute or not. Migrations look like this: https://github.com/waku-org/go-waku/tree/master/waku/persistence/postgres/migrations/sql

**Comment by richard-ramos** [comment]
I wonder if we could have a table like the one I shared! would certainly help in allowing go-waku to consume a nwaku db
