### ISSUE TITLE
chore: bring clarity for running a node on a `cluster-id` `shard`

### ISSUE THREAD

**Issue by danisharora099** [waku-org/nwaku#2259]
### Background
There is some ambiguity in the current progress of starting an nwaku node regarding the use of `cluster-id` and `shards`, especially when considering the `pubsub-topic` flag. This has led to some confusion about the correct configuration while starting an nwaku node for a particular `cluster-id` and `shard`

### Details
It currently looks like `cluster-id` is required to enable some of the peer manager logic for the metadata protocol, while `pubsub-topic` is where the `shards` are retrieved from.
if we make a metadata request without specifying `pubsub-topic` and only pass the `cluster-id`, and response is sent that only contains the `cluster-id` but no `shards`

This is confusing as `pubsub-topic` inherently contains both `cluster-id` and `shards` thus the additional `cluster-id` flag is redundant.

### Acceptance Criteria
Eliminate redundancy and bring clarity in terms of starting a node for a particular `cluster-id` and `shard`

cc @alrevuelta

**Comment by alrevuelta** [comment]
Agree, most likely what we need is to remove the `pubsub-topic` flag in favor of `shards`. But unsure if this is compatible with other features such as static sharding.

**Comment by SionoiS** [comment]
Yes I agree. I feel like there's a refactor needed. This also ties in with the need to allow autosharding with cluster-id != 1.

config:
 - shards
 - cluster-id
 - deprecate pubsub topics

autosharding
- https://github.com/waku-org/nwaku/issues/2258

**Comment by danisharora099** [comment]
bumping this up. can we get an ETA for this, or better error handling in the interim?

it's easy to pass sharded pubsub topics in `pubsubTopic` but if `clusterId` isn't passed, metadata returns `clusterId` as 0

**Comment by SionoiS** [comment]
> bumping this up. can we get an ETA for this, or better error handling in the interim?
> 
> it's easy to pass sharded pubsub topics in `pubsubTopic` but if `clusterId` isn't passed, metadata returns `clusterId` as 0

It's a bit convoluted ATM. I'll try to improve error handling.

**Comment by danisharora099** [comment]
> > bumping this up. can we get an ETA for this, or better error handling in the interim?
> > it's easy to pass sharded pubsub topics in `pubsubTopic` but if `clusterId` isn't passed, metadata returns `clusterId` as 0
> 
> It's a bit convoluted ATM. I'll try to improve error handling.

Thanks SP! Appreciate it
