### ISSUE TITLE
bug: lightpush publish segfault

### ISSUE THREAD

**Issue by AlejandroCabeza** [waku-org/nwaku#2271]
### Problem
Lightpush's `publish` triggers a `SEGFAULT` when sending messages over a specific size.

### Impact
...

### To reproduce
1. Instantiate two `Switch`, one will act as `serverSwitch` and the other as `clientSwitch`.
2. Instantiate a `WakuLightPush` and a `WakuLightPushClient`, using the respective switches.
3. Send a `publish` request using a `WakuMessage` that contains a payload with size equal or higher than `1114000B`.
4. This will trigger a `SEGFAULT`.

Also, you can check out the test case named `Valid Paylod Sizes` found in `waku_lightpush/test_client:198`. Remember to update the keyword from `xasyncTest` to `asyncTest`, else it will be ignored.

Alternatively, you this [PR comment](https://github.com/waku-org/nwaku/pull/2269/files#r1414427976) already points to the test.

### Expected behavior
Max size is standardised, and max size is gracefully handled.

### nwaku version/commit hash
- wakunode: v0.22.0-rc.0-25-gc301e8
- git: ab134afbb705d38c6910515db340154886aef5ac
- PR: https://github.com/waku-org/nwaku/pull/2269

**Comment by Ivansete-status** [comment]
**Weekly Update**

- _achieved_: nim-unittest2 enhancement to prevent segfault when an exception is thrown within the test body and the teardown needs to wait for a libp2p Switch to stop asynchronously.
