### ISSUE TITLE
feat: get message hashes based on criteria/timestamp instead of Full Waku message.

### ISSUE THREAD

**Issue by ABresting** [waku-org/nwaku#2300]
### Problem
Since the introduction of `messageHash` attribute in the DB. A node should be able to get the message hashes between certain timestamp intervals and related critera, just like shown in this code 
https://github.com/waku-org/nwaku/blob/5847f49d3dd7da483bc3e12a51685f22376e9461/waku/waku_archive/driver.nim#L36-L44

This will help nodes filter out the hashes they have already and ask full Waku message of the hashes they do not have. 

### Suggested solution
Add a function in Waku Store that is similar to the above-mentioned one, but returns the `messageHash`es and not the full Waku message.

### Additional context
This will help the nodes in the Waku Network to save network bandwidth and only get messages they do not have.

### Acceptance criteria

- [ ] Function to return a list of message Hashes between timestamp interval and certain criteria such as `contentTopic`, `pubSubTopic` etc.
- [ ] test case that checks if the message hashes between a certain timestamp and criteria are returned.

WDYT @Ivansete-status

**Comment by Ivansete-status** [comment]
Yes, I like this idea :100: , thanks !

**Comment by gabrielmer** [comment]
Closing as this is now supported in Store v3 :)
cc @SionoiS
