### ISSUE TITLE
feat: check messages table before inserting

### ISSUE THREAD

**Issue by jakubgs** [waku-org/nwaku#2324]
### Problem
PostgreSQL logs are spammed with `duplicate key value` errors due to multiple nodes using the same DB:
```
[1006408] ERROR:  duplicate key value violates unique constraint "messageindex"
[1006408] DETAIL:  Key (messagehash)=(0da6c0e74e9193f537f154d5a62331c3a561c4313486bd300c5020410a4583cb) already exists.
[1006408] STATEMENT:  INSERT INTO messages (id, messageHash, storedAt, contentTopic, payload, pubsubTopic, version, timestamp) VALUES ($1, $2, $3, $4, $5, $6, $7, $8);
```
* https://github.com/status-im/infra-shards/issues/26

### Suggested solution
Query the database before inserting the record: https://stackoverflow.com/a/12388511

### Alternatives considered
Reducing verbosity of PostgreSQL DB logs, but that would cause us to miss other issues.

### Additional context
These logs have been filtered out on Logstash level already:

- [`infra-hq#153d0726`](https://github.com/status-im/infra-hq/commit/153d0726) - logstash; filter out waku duplicate key value logs

### Acceptance criteria
This is not an important requirement, and if it would impact performance negatively then it should be closed without implementing.

**Comment by Ivansete-status** [comment]
Thanks for submitting this issue @jakubgs.

fyi - We've already enhanced that "spamming" issue in the following PR: https://github.com/waku-org/nwaku/pull/2283

**Comment by jakubgs** [comment]
Yes, but that's in the node logs, no the database logs.

**Comment by Ivansete-status** [comment]
This can be closed as per the suggestion implemented in the following PR:
https://github.com/waku-org/nwaku/pull/2535
