### ISSUE TITLE
chore: use yamux instead of mplex 

### ISSUE THREAD

**Issue by SionoiS** [waku-org/nwaku#2331]
### Background
The default muxer in go-libp2p is yamux, we should use the same. As seen in https://github.com/waku-org/go-waku/pull/851

### Details
replace this with yamux
https://github.com/waku-org/nwaku/blob/b0c780528b5610f8b6c5e3784dc9faadcb7b6917/waku/node/waku_switch.nim#L93

**Comment by alrevuelta** [comment]
As reported by nim-libp2p team, yamux is ready on their side. But fyi dynamic window size is not supported.
