### ISSUE TITLE
feat: Increase number of contentTopics in a Filter subscription from 30 to 100

### ISSUE THREAD

**Issue by chaitanyaprem** [waku-org/nwaku#2338]
### Problem

In scenarios like Status communities where a contentTopic is used for each channel of a community, the number of filter subscriptions would grow into a huge number if a user is part of many communities (considering each community will have atleast 20+ channels taking discord as an example). 
Considering that a lightClient like status-mobile would maintain atleast 2 filter-peers(which is recommended), the number of ping requests and subscriptions maintained would grow in number pretty quickly causing increased Filter ping traffic. 

Ref discussion thread: https://discord.com/channels/1110799176264056863/1193815573499498626

### Suggested solution
AFAIU: For maintaining a subscription by a FilterNode, i don't see this as causing an impact i.e more contentFilters per subscription shouldn't impact performance.
Let us increase the default limit to 100 in order to address such scenarios.

### Alternatives considered
Make number of contentFilters per subscription a configurable limit that fleet operators/node operators can specify.
Avoiding this to reduce number of configurable options as they can lead to confusion and issues of misconfiguration etc.

### Additional context
cc @waku-org/go-waku-developers @waku-org/js-waku-developers , Clients to be updated to enhance this limit to 100 to match with nwaku.

### Acceptance criteria
- [ ] Single Filter subscription should accept 100 contentFilters

**Comment by chair28980** [comment]
fixed in #2293

**Comment by NagyZoltanPeter** [comment]
Done within https://github.com/waku-org/nwaku/pull/2341
