### ISSUE TITLE
Allow for multiple TCP/UDP ports to be mapped and unmapped

### ISSUE THREAD

**Issue by kdeme** [waku-org/nwaku#239]
When a process needs to listen on multiple TCP or UDP ports and wants to create a mapping for all of those some problems arise when shutting down the process.

Sometimes it deletes the mapping for 1 of the ports, sometimes it hangs, and sometimes this error occurs:
```
DBG 2020-10-20 15:47:17.944+02:00 UPnP: deleted port mapping                 topics="nat" tid=1754707 externalPort=9000 internalPort=9000 protocol=TCP
DBG 2020-10-20 15:47:18.019+02:00 UPnP: deleted port mapping                 topics="nat" tid=1754707 externalPort=9000 internalPort=9000 protocol=UDP
Traceback (most recent call last, using override)
/home/deme/repos/nim-waku/vendor/nim-eth/eth/net/nat.nim(186) stopNatThread
/home/deme/repos/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/channels.nim(369) send
/home/deme/repos/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/channels.nim(350) sendImpl
/home/deme/repos/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/fatal.nim(50) sysFatal
/home/deme/repos/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/excpt.nim(407) reportUnhandledError
/home/deme/repos/nim-waku/vendor/nimbus-build-system/vendor/Nim/lib/system/excpt.nim(358) reportUnhandledErrorAux
Error: unhandled exception: cannot send message; thread died [DeadThreadError]
```

Easiest fix is probably to adapt the code (in nim-eth probably so I might move this issue later) to accept multiple ports instead of doing those calls twice.

**Comment by oskarth** [comment]
cc @jm-clius I'll go ahead and put this in icebox for now

**Comment by kdeme** [comment]
I'll add this functionality while reworking nat options in nim-eth

**Comment by oskarth** [comment]
@kdeme how important would you say this is? When it comes to running on mobile etc

**Comment by kdeme** [comment]
@oskarth This is only important for the Waku v1-v2 bridge **and** when using uPnP, as it required mapping for the devp2p tcp port and for the libp2p tcp port.

**Comment by jm-clius** [comment]
@kdeme is this still relevant? Afaict, this issue does not currently arise when shutting down the `wakubridge`.

**Comment by kdeme** [comment]
From a quick look at the code, I see the `setupNat` call is still done twice in the `wakubridge`. So I think this issue can still occur. Of course if uPnP is not turned on (either in config or on the router), you will not notice it.

**Comment by jm-clius** [comment]
`wakubridge` has been deprioritised and there is open issue to move this tool to its own repo: https://github.com/waku-org/nwaku/issues/1767. Closing as not relevant.
