### ISSUE TITLE
feat: Support message verification using multiple public keys in same pubsubTopic

### ISSUE THREAD

**Issue by Ivansete-status** [waku-org/nwaku#2393]
# Problem

As of now, in status, a public key is used to verify all messages received on a topic in order to determine if they are valid or not. 

But if a single shard/pubsubTopic has to be shared by multiple communities, we need to support registering multiple keys which would be used sequentially to verify or validate messages and consider them as valid even if one of the keys work.

# Acceptance Criteria

Have tests to verify multiple keys being used for validation.

# Notes

Need to analyze performance impact for using multiple keys.
Notice that this issue is cloned from https://github.com/waku-org/go-waku/issues/1022

**Comment by chaitanyaprem** [comment]
Closing this issue as this is something not required to be supported at Waku. Refer to discussions at https://github.com/waku-org/go-waku/issues/1022 for more info.
