### ISSUE TITLE
feat: reference implementation for Store v3 protocol

### ISSUE THREAD

**Issue by jm-clius** [waku-org/nwaku#2425]
### Problem

This feature forms the reference implementation part of Waku Research's new Store protocol proposal.
The overall research task is tracked in https://github.com/waku-org/research/issues/81
The parallel RFC proposal is documented in https://github.com/vacp2p/rfc/pull/665

### Acceptance criteria

- [x] functioning reference implementation of https://github.com/vacp2p/rfc/pull/665
- [x] the current Store protocol (`/vac/waku/store/2.0.0-beta4`) must be mounted in parallel to allow backwards compatibility

cc @SionoiS

**Comment by SionoiS** [comment]
PR https://github.com/waku-org/nwaku/pull/2431
