### ISSUE TITLE
chore: libwaku node can be configured as a store client

### ISSUE THREAD

**Issue by Ivansete-status** [waku-org/nwaku#2457]
### Background
Epic: https://github.com/waku-org/nwaku/issues/2420

### Pre-condition
#2440 should be completed beforehand.

### Details
A libwaku node should be able to act as a store client in the same way `wakunode2` does. We should implement a C example (or extend the existing `cwaku_example.c`) with that feature.

**Comment by gabrielmer** [comment]
Isn't this possible? Thought that with our last work with the bindings that we can configure a store client @Ivansete-status

**Comment by Ivansete-status** [comment]
> Isn't this possible? Thought that with our last work with the bindings that we can configure a store client @Ivansete-status

I think you are right and is likely to be quite fast to achieve :partying_face:

**Comment by Ivansete-status** [comment]
That was completed by https://github.com/waku-org/nwaku/pull/3003
