### ISSUE TITLE
chore: avoid execution error: metadata does not exist from ./register_rln.sh

### ISSUE THREAD

**Issue by Ivansete-status** [waku-org/nwaku#2471]
### Background
nwaku-compose starting a node always shows a confusing error.

### Details
Every time the `./regiser_rln.sh` script is executed, the following error appears and we should avoid that because it causes confusion:
`execution error: metadata does not exist`

This can be tested from: https://github.com/waku-org/nwaku-compose

**Comment by rymnc** [comment]
This is a zerokit (non)issue, can disable it for new trees.
