### ISSUE TITLE
Bump vendor dependencies for release 0.26.0

### ISSUE THREAD

**Issue by NagyZoltanPeter** [waku-org/nwaku#2472]
Update `nwaku` "vendor" dependencies.

### Items to bump
- [ ] dnsclient.nim ( update to the latest tag version )
- [x] nim-bearssl
- [ ] nimbus-build-system
- [ ] nim-chronicles
- [x] nim-chronos
- [x] nim-confutils
- [x] nimcrypto
- [ ] nim-dnsdisc
- [x] nim-eth
- [x] nim-faststreams
- [x] nim-http-utils
- [ ] nim-json-rpc
- [x] nim-json-serialization
- [x] nim-libbacktrace
- [x] nim-libp2p ( update to the unstable branch )
- [x] nim-metrics
- [x] nim-nat-traversal
- [x] nim-presto
- [x] nim-regex ( update to the latest tag version )
- [x] nim-secp256k1
- [x] nim-serialization
- [x] nim-sqlite3-abi ( update to the latest tag version )
- [x] nim-stew
- [x] nim-stint
- [x] nim-taskpools
- [x] nim-testutils
- [x] nim-toml-serialization
- [ ] nim-unicodedb
- [x] nim-unittest2
- [ ] nim-web3
- [x] nim-websock
- [x] nim-zlib
- [ ] zerokit ( this should be kept in version `v0.3.4` )

**Comment by NagyZoltanPeter** [comment]
nim-web3 and  nim-json-rpc libs are kept. (nim-json-rpc latest changes does not coop with older web3).
Latest web3 said to be not enough stable for nwaku.

**Comment by NagyZoltanPeter** [comment]
nim-chronicles also kept in its r0.25.0 version due it introduced a strange compilation issue with its slightly changed code generation magic.
It happens that make testwaku does not compiles for test_rest_store.nim while compiles fine separately as 
tests/wakunode_rest/test_all.nim

`/home/nzp/dev/status/nwaku/vendor/nimbus-build-system/vendor/Nim/compiler/sempass2.nim(325, 16) compiler msg initiated here [MsgOrigin]
/home/nzp/dev/status/nwaku/tests/all_tests_waku.nim(70, 1) template/generic instantiation from here
/home/nzp/dev/status/nwaku/tests/wakunode_rest/test_rest_store.nim(11, 1) template/generic instantiation from here
/home/nzp/dev/status/nwaku/waku/waku_api/rest/store/client.nim(51, 1) template/generic instantiation from here
/home/nzp/dev/status/nwaku/waku/waku_api/rest/store/client.nim(70, 17) template/generic instantiation of `rest` from here
/home/nzp/dev/status/nwaku/vendor/nim-presto/presto/client.nim(512, 17) template/generic instantiation of `async` from here
/home/nzp/dev/status/nwaku/vendor/nim-presto/presto/client.nim(1161, 20) template/generic instantiation of `setResult` from here
/home/nzp/dev/status/nwaku/vendor/nim-presto/presto/client.nim(1170, 44) template/generic instantiation of `error` from here
/home/nzp/dev/status/nwaku/vendor/nim-results/results.nim(890, 24) template/generic instantiation of `raiseResultDefect` from here
/home/nzp/dev/status/nwaku/vendor/nim-results/results.nim(372, 63) template/generic instantiation of `$` from here
/home/nzp/dev/status/nwaku/vendor/nimbus-build-system/vendor/Nim/lib/system/dollars.nim(101, 5) template/generic instantiation from here
/home/nzp/dev/status/nwaku/vendor/nimbus-build-system/vendor/Nim/lib/system/dollars.nim(111, 15) template/generic instantiation of `addQuoted` from here
/home/nzp/dev/status/nwaku/vendor/nimbus-build-system/vendor/Nim/lib/system/dollars.nim(153, 21) template/generic instantiation of `collectionToString` from here
/home/nzp/dev/status/nwaku/vendor/nimbus-build-system/vendor/Nim/lib/system/dollars.nim(136, 13) template/generic instantiation of `addQuoted` from here
/home/nzp/dev/status/nwaku/vendor/nimbus-build-system/vendor/Nim/lib/system/dollars.nim(101, 5) template/generic instantiation from here
/home/nzp/dev/status/nwaku/vendor/nimbus-build-system/vendor/Nim/lib/system/dollars.nim(111, 15) template/generic instantiation of `addQuoted` from here
/home/nzp/dev/status/nwaku/vendor/nimbus-build-system/vendor/Nim/lib/pure/options.nim(361, 11) template/generic instantiation of `addQuoted` from here
/home/nzp/dev/status/nwaku/vendor/nimbus-build-system/vendor/Nim/lib/system.nim(2929, 11) Error: type mismatch: got <Base64String>
but expected one of:
func `$`(a: Duration): string
  first type mismatch at position: 1
  required type for a: Duration
  but expression 'x' is of type: Base64String`

**Comment by Ivansete-status** [comment]
I'm closing because we delivered the `0.26.0`.
@NagyZoltanPeter - feel free to reopen it in case I missed something :)

**Comment by NagyZoltanPeter** [comment]
> I'm closing because we delivered the `0.26.0`.
> @NagyZoltanPeter - feel free to reopen it in case I missed something :)

Thanks for it, I forgot...
