### ISSUE TITLE
bug: Lightpush.send() failure and node disconnection beyond 32 content topics on nwaku v0.25.0

### ISSUE THREAD

**Issue by danisharora099** [waku-org/nwaku#2478]
### Problem
When testing with `js-waku` against `nwaku` version 0.25.0, a discrepancy in handling lightpush requests beyond 30 content topics was observed, despite recent support extension to 100 content topics. Specifically, `lightpush.send()` fails starting from the 33rd execution, resulting in a disconnection from the `nwaku` node. This behavior is unexpected and persists across different `nwaku` images tested.

### Impact
Significant 

### To reproduce
1. Set up a `nwaku` node using the `harbor.status.im/wakuorg/nwaku:latest` image or version 0.25.0.
2. Using `js-waku`, subscribe to more than 30 content topics.
3. Attempt to send lightpush messages beyond the 32nd message.
4. Observe the failure in `lightpush.send()` and eventual disconnection from the `nwaku` node.

PR can be used to repro: https://github.com/waku-org/js-waku/pull/1857: `npm i && npm run build && cd packages/tests && npm run test:node`

### Expected behavior
The expected behavior was for `js-waku` to successfully send lightpush messages for up to 100 content topics without encountering disconnections or failures, as per the recent extension of support in `nwaku`.

### Screenshots/logs
Logs indicate that after the 32nd lightpush message, `lightpush.send()` fails with "Remote peer fault: No response in PushRPC", followed by disconnection errors and warnings related to peer availability.

### nwaku version/commit hash
The issue was observed in `nwaku` version 0.25.0. 

### Additional context
The problem was initially discussed in a chat thread with nwaku engineers, where it was suggested that the issue could be related to ws stream reset after 32 messages or a potential issue with the mplex configuration. No RLN is used, and the setup was over the default pubsub topic. 
Original Discord thread: https://discord.com/channels/1110799176264056863/1201820015284723753

**Comment by NagyZoltanPeter** [comment]
@danisharora099 Can you attach logs in greater context of the issue? I mean from the last few successful lightpush send.

**Comment by weboko** [comment]
@NagyZoltanPeter can you check logs [here](https://github.com/waku-org/js-waku/issues/1790#issue-2082008869), they should be sufficient enough

**Comment by gabrielmer** [comment]
Fixed by https://github.com/waku-org/js-waku/pull/2021
