### ISSUE TITLE
bug: nwaku-compose not starting properly

### ISSUE THREAD

**Issue by gabrielmer** [waku-org/nwaku#2510]
### Problem
Users have mentioned lately that when starting nwaku-compose, the node would get stuck at the following state:

![image](https://github.com/waku-org/nwaku/assets/101006718/a54dfd13-4c4a-46aa-bfb2-d2dddb428744)

I could reproduce it and happens to me also.

The behavior is not consistent, sometimes it works and sometimes it doesn't.

**Comment by Ivansete-status** [comment]
It works correctly on sandbox
![image](https://github.com/waku-org/nwaku/assets/128452529/e55bee80-bdee-4b3f-bd8d-9e0a3532fb9d)

And works correctly when running a node in my local PC:
![image](https://github.com/waku-org/nwaku/assets/128452529/349a46cb-cab9-459e-bb71-0e37b64fc997)

**Comment by gabrielmer** [comment]
> Perhaps this will happen when there are no messages being sent in the network?

I also thought at one point that traffic was the issue. But at the same time that this is happening to some users, for others (including myself) everything appears normal and with traffic.

One user that had this issue for days mentioned that he solved it by deleting his VPS instance and spinning up a new one.
Restarting docker-compose didn't help them.

It's definitely an issue related to bootstraping/node discovery.

I've been trying to reproduce it in a VPS (I ask users in which VPS this happened to them so I can try myself over there) but everything has worked fine in all of my attempts.

Currently still seeking reports from users so I can reproduce it in a VPS

**Comment by gabrielmer** [comment]
Haven't seen this happening recently. Seemed to happen especially to Contabo VPS insances.

Closing, and will reopen in case we start seeing this again
