### ISSUE TITLE
chore: Remove JSON-RPC documentation references

### ISSUE THREAD

**Issue by NagyZoltanPeter** [waku-org/nwaku#2540]
### Background
As https://github.com/waku-org/nwaku/issues/2053 is done we shall remove any reference to JSON-RPC api.

### Details
- [x] https://github.com/waku-org/docs.waku.org/issues/183
- [x] Remove refrence from connect.md
- [x] Retire RFC: https://rfc.vac.dev/spec/16/ 
- Wherever it needs we must point to REST API reference: https://waku-org.github.io/waku-rest-api/

This is part of https://github.com/orgs/waku-org/projects/8

**Comment by chair28980** [comment]
@jm-clius per the third item listed above, `Retire RFC: https://rfc.vac.dev/spec/16/`, what is the standard operating procedure to handle this?

cc @LordGhostX

**Comment by NagyZoltanPeter** [comment]
necessary change in nwaku's connect.md is done in https://github.com/waku-org/nwaku/pull/2597

**Comment by chair28980** [comment]
Closing issue as completed.
