### ISSUE TITLE
chore: only receive messages if someone subscribes explicitly via REST API to a pubsubTopic

### ISSUE THREAD

**Issue by fbarbu15** [waku-org/nwaku#2546]
### Background
On nwaku side if we pass --pubsub-topic as an argument to then node creation it will automatically subscribe to that topic and receive messages on it.
Based on this [comment](https://github.com/waku-org/go-waku/issues/1064) we should explicitly subscribe via REST API to that pubsubTopic for this to happen.

**Comment by chair28980** [comment]
Closing per discussion during nwaku pm 2024-03-26, this is expected behavior.
