### ISSUE TITLE
refactor(c-bindings): reuse config defaults 

### ISSUE THREAD

**Issue by richard-ramos** [waku-org/nwaku#2557]
Instead of duplicating the defaults from the config in https://github.com/waku-org/nwaku/blob/0f30ea73fe717f3bddd59295951ddc1223b53dca/library/waku_thread/inter_thread_communication/requests/node_lifecycle_request.nim#L65 read the values from the pragma of each field. (`confutils` might provide already a way to do it)

**Comment by gabrielmer** [comment]
Closed by https://github.com/waku-org/nwaku/pull/2685 :)
