### ISSUE TITLE
bug: contentTopic naming not consistent in the store response where is's content_topic

### ISSUE THREAD

**Issue by fbarbu15** [waku-org/nwaku#2582]
Relay/filter/lightPush uses contentTopic
While store returns content_topic

**Comment by SionoiS** [comment]
:| sorry

**Comment by Ivansete-status** [comment]
> I think there is a confusion here. Relay returns `contentTopic` and store returned `content_topic` until it got fixed by #2584 to return also `contentTopic` Now we are back to how it was at the beginning with relay returning `contentTopic` and store returning `content_topic` Ex:
> 
> ```
> curl -v -X GET "http://127.0.0.1:51443/store/v1/messages?pubsubTopic=%2Fwaku%2F2%2Frs%2F0%2F0&pageSize=5&ascending=true" -H "Content-Type: application/json" -d 'None'
> {"messages":[{"payload":"U3RvcmUgd29ya3MhIQ==","content_topic":"/myapp/1/latest/proto","version":0,"timestamp":1714466247670932480,"ephemeral":false}]}
> 
> 
> curl -v -X GET "http://127.0.0.1:51443/relay/v1/messages/%2Fwaku%2F2%2Frs%2F0%2F0" -H "Content-Type: application/json" -d 'None'
> [{"payload":"U3RvcmUgd29ya3MhIQ==","contentTopic":"/myapp/1/latest/proto","version":0,"timestamp":1714466247670932480,"ephemeral":false}]
> ```

Morning @fbarbu15 !
Sorry for the confusion! How do you need it to be returned in all cases? Snake case or CamelCase?
Cheers

**Comment by Ivansete-status** [comment]
Hey @fbarbu15 !
Thanks for submitting this issue. We've standardized all fields to CamelCase and is now available in `nwaku`-`master`
