### ISSUE TITLE
bug: PeerInfo instance affects listed protocols

### ISSUE THREAD

**Issue by AlejandroCabeza** [waku-org/nwaku#2590]
### Problem
The order in which protocols are mounted, nodes are started, and peerInfo is retrieved; matters for peerInfo.protocols consistency

### Impact
Low

### To reproduce
The simplest way to reproduce is to checkout the `test-peer-connection-management` branch. Open `tests/node/test_wakunode_peer_manager.nim` and check out the `Mount Order` suite. In there there's a test case for each of the order possibilities. In the last two (`info-start-protocol`, `info-protocol-start`) the `peerInfo` is not updated with the correct protocols.

### Expected behavior
Not sure if this is expected or not.

### nwaku version/commit hash
- wakunode2: v0.24.0-rc.0-126-g4117fe
- branch: test-peer-connection-management
- commit: bbebbac5fb1edd230eaaa2043e4a78caf3794884 (might change in the future)

**Comment by gabrielmer** [comment]
This is expected, as in both cases, for example https://github.com/waku-org/nwaku/blob/31c632e427da48c4287d4e4270a54d56b454dd26/tests/node/test_wakunode_peer_manager.nim#L913-L934

The `RemotePeerInfo` is retrieved before mounting the protocol (Relay in this case).

We add the information to the PeerStore based on the information that we provide in the `RemotePeerInfo`. So if we provide the variable without the protocol yet mounted, then the PeerStore won't be aware of it.

Closing the issue as it's expected :) please lmk and reopen in case I'm missing something
