### ISSUE TITLE
bug: cannot reach my node running in my shard

### ISSUE THREAD

**Issue by plopezlpz** [waku-org/nwaku#2618]
### Problem

I run a `nwaku` node in the following shards: 32, 64, 128, 256 and **101**.

This node connects to the fleet nodes fine. Shard 101 is not known by any other node in the fleet.

I run status-desktop with no changes, it connects fine to nodes in the fleet. I create a community to be in shard 101 and I don't see any connection to the `nwaku` node on 101. 

My assumption is that my status-desktop would discover that nwaku node in shard 101 indirectly through other nodes connected to to that node.

### Expected behavior

My assumption is that my status-desktop would discover that nwaku node in shard 101 indirectly through other nodes connected to to that node. Maybe this assumption is wrong.
I can make this work just updating the bootstrapt node to my status-desktop app

**Comment by gabrielmer** [comment]
I think it's fine but let's see what @chaitanyaprem says just to make sure :)
