### ISSUE TITLE
chore: msg_hash logs only under certain compilation flag

### ISSUE THREAD

**Issue by Ivansete-status** [waku-org/nwaku#2678]
### Background
The DST team needs to keep track of the messages and this is done through log analysis and `msg_hash` track.
Given that DST spawns thousands of nodes we need to bring them docker images that print the minimum required logs so that the analysis process is faster.

### Details
A new compilation flag is required: `msg-track`.
If that compilation is defined, the `wakunode2` would ideally only print the `msg_hash`-related logs

( cc: @AlbertoSoutullo )

**Comment by jm-clius** [comment]
Why not use a more descriptive compilation flag - simply `logMessageHashes`. That means the code will have something like:

```
when defined(logMessageHashes):
  info "waku.relay received",
```

which should be pretty intuitive to understand :)

**Comment by Ivansete-status** [comment]
> Why not use a more descriptive compilation flag - simply `logMessageHashes`. That means the code will have something like:
> 
> ```
> when defined(logMessageHashes):
>   info "waku.relay received",
> ```
> 
> which should be pretty intuitive to understand :)

Beautiful! Much better indeed. We will do that
Thanks :partying_face:

**Comment by SionoiS** [comment]
Would it not much simpler to use https://github.com/status-im/nim-chronicles?tab=readme-ov-file#chronicles_enabled_topics ?

```
proc mylog() =
  logScope:
    topics = "my scope"

  info "important text"
```

`nim c -r -d:chronicles_enabled_topics="my scope".......`

**Comment by Ivansete-status** [comment]
> Would it not much simpler to use https://github.com/status-im/nim-chronicles?tab=readme-ov-file#chronicles_enabled_topics ?
> 
> ```
> proc mylog() =
>   logScope:
>     topics = "my scope"
> 
>   info "important text"
> ```
> 
> `nim c -r -d:chronicles_enabled_topics="my scope".......`

Thanks for the suggestion!
From my dumb PoV, it sounds simpler the compilation flag :)

**Comment by jm-clius** [comment]
@SionoiS this is more or less what we have now - we compile a binary with only the scope where message hashes are logged included. The problem with this approach is that you will now _only_ get this scope logged. The desired behaviour is more: log as per normal at the log level I desire and, optionally, add these high-rate logs. Afaik there's no straightforward way to do this with log scopes.

**Comment by SionoiS** [comment]
> @SionoiS this is more or less what we have now - we compile a binary with only the scope where message hashes are logged included. The problem with this approach is that you will now _only_ get this scope logged. The desired behaviour is more: log as per normal at the log level I desire and, optionally, add these high-rate logs. Afaik there's no straightforward way to do this with log scopes.

`-d:chronicles_enabled_topics:"MyTopic":DEBUG,"AnotherTopic":INFO` no? I'm just reading the readme and it seams possible.
