### ISSUE TITLE
feat: light protocol tester application

### ISSUE THREAD

**Issue by NagyZoltanPeter** [waku-org/nwaku#2700]
### Problem
In order to get a good picture of reliability of lightpush and filter protocols/services in the network we need a tool, an application that can measure message latencies and loss rate in different condition and in various scale.

### Suggested solution
Write an application that can either publish messages via lightpush or consume messages via filter from the network.
Each such clients shall use client side of the protocols and shall connect to a service peers in the network.
Messages shall be indexed an timestamped with information of duration from test start in order to measure latency and message losses and report them.

###Workbreakdown
####Phase1
Shall contain:
- [X] light_push publisher
- [X] filter_subscriber consumer
- [X] boundle into a docker compose with a full node of nwaku:latest image + monitoring and store.

####Phsase2
- [X] Shall utilize this tool to run against a waku-simulator without RLN.
- [X] Configurable message frequency and size

####Phase3
- [x] Run a stress test on waku-simulator with proper logging for message flow analysis
- [x] Run test on shards.staging - utilitzin different entry point to the network

**Comment by Ivansete-status** [comment]
This is now blocked because we need to prepare an image that brings proper tracking logs where the `sender_peer_id` is printed.
We will create that docker image based on the v0.29.0
@NagyZoltanPeter mentioned that there are messages being lost when using it with WakuSimulator and we need to debug that better once the above image is created.

**Comment by NagyZoltanPeter** [comment]
LiteProtocolTester is implemented and capable to run either in simulation or directly on any fleet.
It can be configured to various stress test for the network (multi sender, multi receiver, message frequency and size variation).
It is capable to detect message loss, misorder delivery, duplications. It calculates latencies.
