### ISSUE TITLE
bug: store v3 response format issues

### ISSUE THREAD

**Issue by fbarbu15** [waku-org/nwaku#2719]
### Problem
When comparing nwaku and go-waku store v3 responses with included data I noticed that nwaku has some issues:

Nwaku:
`{"requestId":"","statusCode":200,"statusDesc":"OK","messages":[{"messageHash":{"data":"wQQIz0pW5AREd07lamf0neqZFZ7KLa+5avxwAiKX+tw="},"message":{"payload":"SGVsbG8gV29ybGQh","contentTopic":"/myapp/1/latest/proto","version":0,"timestamp":1716368075453098240,"ephemeral":false}}]}`

Go-Waku:
`{"request_id":"59090b192cbf73da643554cc6eb706091dde799e95d6426b8192de88cae5de3a","status_code":200,"status_desc":"OK","messages":[{"message_hash":"wQQIz0pW5AREd07lamf0neqZFZ7KLa+5avxwAiKX+tw=","message":{"payload":"SGVsbG8gV29ybGQh","contentTopic":"/myapp/1/latest/proto","version":0,"timestamp":"1716368075453098240","meta":"","ephemeral":false,"rateLimitProof":""},"pubsub_topic":"/waku/2/rs/0/0"}]}`

Issues:
1. `requestId` is missing
2. `messageHash` has an extra `data` key. Is that really needed?
3. pubsubTopic is missing

For go-waku keys not being camelCase I will raise a issue on their side

**Comment by SionoiS** [comment]
1. yes it is removed for testing purpose. I don't remember why exactly.
2. should be removed yeah
3. should be easy fix.

Thanks!

**Comment by SionoiS** [comment]
fixed by https://github.com/waku-org/nwaku/pull/2718
