### ISSUE TITLE
chore: extract select to a const

### ISSUE THREAD

**Issue by richard-ramos** [waku-org/nwaku#2744]
In https://github.com/waku-org/nwaku/blob/01577f69a571bcbf207179b78d837a59a8d86d32/waku/waku_archive/driver/postgres_driver/postgres_driver.nim the following SELECT is reused in the queries: 
```sql
SELECT storedAt, contentTopic, payload, pubsubTopic, version, timestamp, id, messageHash, meta FROM messages
```
We ran into an issue on which one of the columns (`meta`) was not added by mistake to some of the queries, causing a failure while attempting to retrieve messages. 

To avoid this issue happening in the future, I suggest extracting this part of the queries to a constant and reuse it in all the queries.

**Comment by SionoiS** [comment]
Should be addressed by my driver refactor I think.
