### ISSUE TITLE
bug(storev3): can't advance cursor

### ISSUE THREAD

**Issue by richard-ramos** [waku-org/nwaku#2745]
### Problem
For this criteria in `/dns4/store-01.do-ams3.shards.test.status.im/tcp/30303/p2p/16Uiu2HAmAUdrQ3uwzuE4Gy4D56hX6uLKEeerJAnhKEHZ3DxF1EfT`, there should be around ~510 messages
```json
{
 "request_id": "test1"
 "include_data":true,
 "pubsub_topic":"/waku/2/rs/16/32",
 "time_start":1717038870472334766,
 "time_end":1717038999574854537,
 "pagination_limit":100
}
```
If I execute the query, I get the first 100 results succesfully, and the cursor (represented here in std base64): `Mlnwx3p1TukFi+UnxSc++5XjVLUBjBxMByRDjc+jgV8=` 

If i proceed to ask for the next page of results:
```json
{
 "request_id": "test2",
 "include_data":true,
 "pubsub_topic":"/waku/2/rs/16/32",
 "time_start":1717038870472334766,
 "time_end":1717038999574854537,
 "pagination_cursor":"Mlnwx3p1TukFi+UnxSc++5XjVLUBjBxMByRDjc+jgV8=",
 "pagination_limit":100
}
```
I get the following response:
```json
 {"request_id":"test2","status_code":200,"status_desc":"OK"}
```

which is not okay because there are more messages (i verified with legacy store) 

Interestingly enough, if I change the pagination limit to 10, i still see the same behavior: 10 results on first page, and no messages on second page.

This problem is likely fixed with @SionoiS archive refactor.

**Comment by Ivansete-status** [comment]
Closing as per https://github.com/waku-org/nwaku/pull/2761
