### ISSUE TITLE
bug: RateLimitProof.proof wrong size

### ISSUE THREAD

**Issue by AlejandroCabeza** [waku-org/nwaku#2757]
### Problem
The `RateLimitProof.proof` is a byte array of length 128, but it should be 256.

### To reproduce
Check the attribute declared at `waku/waku_rln_relay/protocol_types.nim:39`, and the type in the same file at line `23`.
Also, the test case `tests/waku_rln_relay/rln/test_wrappers.nim:137` by the name of `Valid zk proof`. The test fails as it expects the attribute to be of length 256, as seen in line `169`.

### Expected behavior
For the code to follow the specs at https://github.com/vacp2p/rfc-index/blob/69f28534075d1486ebff0f292cd4e2fa80f6fd1b/waku/standards/core/17/rln-relay.md?plain=1#L193.

### nwaku version/commit hash
- wakunode: v0.28.0-29-g5c645c
- Git: 8e9f983ad955e4ad68720b52b53cbfd6cf0a52a6
- PR: https://github.com/waku-org/nwaku/pull/2639

**Comment by rymnc** [comment]
The implementation is correct.
There is ambiguity about compressiom in the spec.
the implementation uses point compression which halves the size of the proof from 256 bytes to 128 bytes. At the time of writing the spec, there was no point compression available. 

created issue in the rfc-index to fix, thanks!
https://github.com/vacp2p/rfc-index/issues/43

**Comment by rymnc** [comment]
assigning to myself to see to it that this issue is closed :)
