### ISSUE TITLE
chore: update lightpush protocol to handle unsupported pubsub topics with clear error codes

### ISSUE THREAD

**Issue by gabrielmer** [waku-org/nwaku#2773]
### Background
The lightpush protocol itself should never be aware of the sharded format of pubsub topics. It is an extension of libp2p's gossipsub.
On a protocol level, the lightpush service node needs to handle requests on unsupported pubsub topics by returning a clear error code.

### Acceptance criteria
- [ ] Update lightpush protocol to handle unsupported pubsub topics with clear error codes.

**Comment by NagyZoltanPeter** [comment]
@gabrielmer : I think its clearly part of #2722 WDYT?

**Comment by gabrielmer** [comment]
> @gabrielmer : I think its clearly part of #2722 WDYT?

Oh 100%! Will close it as duplicate! Thank you!
