### ISSUE TITLE
feat: effectively deprecate store v2

### ISSUE THREAD

**Issue by Ivansete-status** [waku-org/nwaku#2833]
### Description
With the aim of keeping a concise code base and only the needed, we need to clean the store-v2 (aka store_legacy) code.

### More context
https://discord.com/channels/1110799176264056863/1253380615231766539

**Comment by SionoiS** [comment]
duplicate of https://github.com/waku-org/nwaku/issues/2790?

**Comment by Ivansete-status** [comment]
Closing as duplicated. Thanks for the headsup @SionoiS !
In the 2790 I just added a reference to the Discord chat
