### ISSUE TITLE
bug: could not register RLN

### ISSUE THREAD

**Issue by romanzac** [waku-org/nwaku#2837]
### Problem
During interop tests run nominal test case "test_valid_payloads_at_slow_rate" has failed at RLN registration step.

### Impact
Blocking RLN testing with docker

### To reproduce
1. git clone https://github.com/waku-org/waku-interop-tests.git
2. cd waku-interop-tests
3. python -m venv .venv
4. source .venv/bin/activate
5. pip install -r requirements.txt
6. pre-commit install
7. pytest tests/relay/test_rln.py -k 'test_valid_payloads_at_slow_rate'

### Expected behavior
RLN registration working

### Screenshots/logs
[Allure report](https://waku-org.github.io/waku-interop-tests/nim/243/#categories/bdbf199525818fae7a8651db9eafe741)

Docker image log:
```
docker run -i -t -p 38461:38461 -p 38462:38462 -p 38463:38463 -p 38464:38464 -p 38465:38465 harbor.status.im/wakuorg/nwaku:latest generateRlnKeystore --execute --rln-relay-cred-path=/keystore/keystore.json --rln-relay-cred-password=REDACTED --rln-relay-eth-client-address=https://sepolia.infura.io/v3/REDACTED --rln-relay-eth-contract-address=0xF471d71E9b1455bBF4b85d475afb9BB0954A29c4 --rln-relay-eth-private-key=REDACTED
Time to deserialize proving key: 362.360276ms
Time to deserialize matrices: 5.378326ms
Traceback (most recent call last, using override)
/app/vendor/nimbus-build-system/vendor/Nim/lib/system/excpt.nim(631) signalHandler
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

### nwaku version/commit hash
Docker image harbor.status.im/wakuorg/nwaku:latest 95cd68a9a2b0  
commit: 94947a8504fd1c07a1a873321354198325688826
v0.29.0-13-g94947a85

**Comment by rymnc** [comment]
from the 
```
Time to deserialize proving key: 362.360276ms
Time to deserialize matrices: 5.378326ms
```
it seems like rlnv2 is being used. you need to use the appropriate contract address for this, which is TBD. please use a release before release v0.30.0

**Comment by romanzac** [comment]
> from the
> 
> ```
> Time to deserialize proving key: 362.360276ms
> Time to deserialize matrices: 5.378326ms
> ```
> 
> it seems like rlnv2 is being used. you need to use the appropriate contract address for this, which is TBD. please use a release before release v0.30.0

Thanks a lot. Let me pause RLN tests for now. Interop tests always pull latest. Better to not rush.

**Comment by romanzac** [comment]
I can confirm registration work both in on-chain and off-chain mode.

**Comment by rymnc** [comment]
can we close this issue? :)
