### ISSUE TITLE
chore: dynamically increase ConnectivityLoopInterval value

### ISSUE THREAD

**Issue by gabrielmer** [waku-org/nwaku#2877]
### Background
We try to connect to peers every fixed amount of time, which is defined by the following const
https://github.com/waku-org/nwaku/blob/49f03f124349250fb29e3b642a0d3f84e4045fc6/waku/node/peer_manager/peer_manager.nim#L62

The more peers we have, the less we need to run this loop. The inverse is also true - the less peers we have, the more we need to run this.

We should dynamically modify this waiting time depending on how many peers we have

### Acceptance criteria
- [ ] the connectivity loop wait time is dynamic based on current amount of peers

**Comment by Ivansete-status** [comment]
Good one! What are the different num of peer levels that we should consider and the wait time on each case?
Cheers

**Comment by gabrielmer** [comment]
> Good one! What are the different num of peer levels that we should consider and the wait time on each case? Cheers

We should align with research time for this, but I would personally say something like:

 15 seconds for 0<= `num peers` < 10
 30 seconds for 10<= `num peers` < 20
 1 minute for 20 <= `num peers`

does it makes sense?
CC @SionoiS @alrevuelta

**Comment by SionoiS** [comment]
Hard to say which value to use. :shrug: seams fine.

I have an idea, if the code connect to all peers it can at interval could we not also check the number of new peers we found before triggering a connectivity check?

If node have many peers already and only 1 peers is new, do nothing
If node have many peers already and many peers are new, trigger
If node have few peers already and only 1 peers is new, trigger
If node have few peers already and many peers are new, trigger

WDYT?

**Comment by gabrielmer** [comment]
> Hard to say which value to use. 🤷 seams fine.
> 
> I have an idea, if the code connect to all peers it can at interval could we not also check the number of new peers we found before triggering a connectivity check?
> 
> If node have many peers already and only 1 peers is new, do nothing If node have many peers already and many peers are new, trigger If node have few peers already and only 1 peers is new, trigger If node have few peers already and many peers are new, trigger
> 
> WDYT?

Yes! We can trigger a new connectivity loop iteration if we just added many new peers, I like the idea :)
