### ISSUE TITLE
chore: filter peers stored in cache by cluster-id in peer-exchange

### ISSUE THREAD

**Issue by Ivansete-status** [waku-org/nwaku#2910]
### Background
This is inspired by https://github.com/waku-org/go-waku/pull/1139

If the `cluster-id` is specified, then the waku peer exchange protocol should only consider peers with that given `cluster-id`.

**Comment by fryorcraken** [comment]
Regarding cluster-id not specified, then I guess filtering should not be applied. However, it may make more sense to make it impossible for the `cluster-id` to not be specified.
