### ISSUE TITLE
chore: review max-relay-peers config attribute in wakunode2

### ISSUE THREAD

**Issue by Ivansete-status** [waku-org/nwaku#2929]
### Background
We have the `max-relay-peers` parameter which is expected to limit the max number of relay peers that a wakunode2 should support.

This is very interesting from the `waku.sandbox` fleet, f.e., because we usually have there 300 libp2p connections that are only used for relay and therefore, there is no room for other protocol such as store, filter, or lightpush.

```nim
waku_connected_peers{direction="In",protocol="/vac/waku/filter-push/2.0.0-beta1"} 0.0
waku_connected_peers{direction="Out",protocol="/vac/waku/store/2.0.0-beta4"} 0.0
waku_connected_peers{direction="In",protocol="/vac/waku/relay/2.0.0"} 277.0
waku_connected_peers{direction="In",protocol="/vac/waku/filter/2.0.0-beta1"} 0.0
waku_connected_peers{direction="Out",protocol="/vac/waku/filter/2.0.0-beta1"} 0.0
waku_connected_peers{direction="Out",protocol="/vac/waku/filter-subscribe/2.0.0-beta1"} 0.0
waku_connected_peers{direction="Out",protocol="/vac/waku/lightpush/2.0.0-beta1"} 0.0
waku_connected_peers{direction="In",protocol="/vac/waku/filter-subscribe/2.0.0-beta1"} 0.0
waku_connected_peers{direction="In",protocol="/vac/waku/store/2.0.0-beta4"} 0.0
waku_connected_peers{direction="Out",protocol="/vac/waku/peer-exchange/2.0.0-alpha1"} 0.0
waku_connected_peers{direction="In",protocol="/vac/waku/peer-exchange/2.0.0-alpha1"} 0.0
waku_connected_peers{direction="In",protocol="/vac/waku/lightpush/2.0.0-beta1"} 0.0
waku_connected_peers{direction="In",protocol="/vac/waku/store-query/3.0.0"} 0.0
waku_connected_peers{direction="In",protocol="/vac/waku/metadata/1.0.0"} 0.0
waku_connected_peers{direction="Out",protocol="/vac/waku/filter-push/2.0.0-beta1"} 0.0
waku_connected_peers{direction="Out",protocol="/vac/waku/metadata/1.0.0"} 0.0
waku_connected_peers{direction="Out",protocol="/vac/waku/store-query/3.0.0"} 0.0
waku_connected_peers{direction="Out",protocol="/vac/waku/relay/2.0.0"} 22.0
```

Once this is available and works well, we must establish that `max-relay-peers` to 200 in `waku.*` fleets, and then leave ~100 for other protocols.

( cc thanks @alrevuelta for the idea! )

**Comment by gabrielmer** [comment]
Went over the code and tested. When we set `max-relay-peers`, we target for 1/3 of those peers to be `outPeers` and 2/3 to be `inPeers`

https://github.com/waku-org/nwaku/blob/4d47aa655feaba695246751c3c37c08395cf7ef6/waku/node/peer_manager/peer_manager.nim#L497-L512

We do respect the amount of `outPeers` but I see that the line that is supposed to maintain the `inPeers` target is commented

https://github.com/waku-org/nwaku/blob/4d47aa655feaba695246751c3c37c08395cf7ef6/waku/node/peer_manager/peer_manager.nim#L737-L739

But for Sharded Peer Management it is being enforced

https://github.com/waku-org/nwaku/blob/4d47aa655feaba695246751c3c37c08395cf7ef6/waku/node/peer_manager/peer_manager.nim#L829

I think we can uncomment that line, if there's an actual issue with it fix it. And also plan to finally enable Sharded Peer Management as default soon.

WDYT? @Ivansete-status @SionoiS

**Comment by gabrielmer** [comment]
> I though sharded peer management was already enabled. :| Any reason why not?

I think that we were waiting for named sharding to be removed, which happened last release. And now that we have that blocker gone, we have to thoroughly test it, as it's a big change. So pretty sure the only thing left for it before enabling it is validating it.

Am I missing something? I would target to merge it right after releasing v0.32.0 to have time to find and fix potential bugs. WDYT @Ivansete-status?
