### ISSUE TITLE
chore: high memory usage when dealing with postgres

### ISSUE THREAD

**Issue by Ivansete-status** [waku-org/nwaku#2967]
### Background
We are seeing nodes that has a high memory and swapping usage. It is pretty likely that this is due to the use of _Postgres_ as this issue is more evident in `status.prod`, where _Postgres_ is used more intensively.

### Details
We need to understand why so big memory is used when dealing with _Postgres_.

The problem has been reported by @yakimant after noticing that a particular node became unavailable for some period.

Anton's comment:
> store-db-01.gc-us-central1-a.status.prod became unreachable on Friday, I did reboot, but the issues looks consistent.
> It was out of MEM, swapping and out of SWAP.

![image](https://github.com/user-attachments/assets/74d2d681-87d9-4c10-bfc0-fa25adf9b304)

**Comment by Ivansete-status** [comment]
Sorry for the confusion. I'm closing this because the inaccessibility issue happened in the database due to autovacuum being run:

```
ivan@store-db-01.gc-us-central1-a.status.prod:/var/log/docker/nim-waku-store-db$ zgrep vacuum *
docker.20240810_0000.log.gz:2024-08-09T09:10:55.977203+00:00 docker/nim-waku-store-db[1907]: 2024-08-09 09:09:59.078 UTC [26748] WARNING:  autovacuum worker took too long to start; canceled
docker.20240810_0000.log.gz:2024-08-09T13:13:43.842434+00:00 docker/nim-waku-store-db[1907]: 2024-08-09 13:12:25.954 UTC [29334] WARNING:  autovacuum worker took too long to start; canceled
docker.20240810_0000.log.gz:2024-08-09T18:55:15.009147+00:00 docker/nim-waku-store-db[1941]: 2024-08-09 18:54:21.010 UTC [27] WARNING:  autovacuum worker took too long to start; canceled
docker.20240811_0000.log.gz:2024-08-10T02:55:24.078005+00:00 docker/nim-waku-store-db[1941]: 2024-08-10 02:54:30.514 UTC [7876] WARNING:  autovacuum worker took too long to start; canceled

```

**Comment by yakimant** [comment]
Problem on postgres nodes are still there.
