### ISSUE TITLE
chore: create grafana panel to show max, min, mean, median stats of query times

### ISSUE THREAD

**Issue by Ivansete-status** [waku-org/nwaku#2995]
### Background
Aiming to understand better the progress on query performance, we need to have a clear way to measure it.

### Details
Originally requested by @fryorcraken 

Ideally, we should be able to see different graphs containing the following information per each query type

- median query response time
- average query response time
- min query response time
- max query response time

It could be over a single graph or a separate graph.

**Comment by fryorcraken** [comment]
@Ivansete-status is this done as part of teh Store/Arhive section of https://grafana.infra.status.im/d/qrp_ZCTGz/nim-waku-v2?orgId=1&var-host=.*&var-fleet=status.prod&var-dc=All ?

**Comment by Ivansete-status** [comment]
> @Ivansete-status is this done as part of teh Store/Arhive section of https://grafana.infra.status.im/d/qrp_ZCTGz/nim-waku-v2?orgId=1&var-host=.*&var-fleet=status.prod&var-dc=All ?

Yes it is, these are the panels that contain that information:
![image](https://github.com/user-attachments/assets/23f5ced8-2e50-4822-8fa7-2e2a0ca09fe1)
