### ISSUE TITLE
chore: add dashboard for liteprotocoltester runs

### ISSUE THREAD

**Issue by NagyZoltanPeter** [waku-org/nwaku#2999]
### Background
As closing the light protcol tooling we shall add grafana dashboard for liteprotocoltester to be able to monitor the performance of the tests.

### Details
As it is already possible to run liteprotocoltester on waku-simulatior or on any real fleet either on TWN.
Staticsitcs are also collected but only printed into the log.
We need to introduce corresponding metrics and prepare a dashboard for them.

### Acceptance criteria
Run liteprotocoltester on TWN or on simulator, check monitoring dashboard and take screenshots of it.

**Comment by fryorcraken** [comment]
- run the tool on status prod fleet with accompanying dashboard
- attempt to be close to a status light client behaviour:
  - use a couple filter and light push node
  - use a store node
  - do a small number of regular queries (not stress test but monitor)
  - restart node every hour or 30min (as would a mobile or desktop do).

Monitor metrics to get health of the network:
- message reliability stats: confirm number of message sent through
- connectivity: number of connected peers for the various protocols
- peer exchange: report number of nodes returned from peer exchange and their relevant (shard, light push protocol support)

This way, we can have a better idea of the network health:
- is a new client coming in able to make a libp2p connection to a light push, filter and store server?
- if not, why ? (not relevant nodes in peer exchange response, not able to connect?)
- is a new client able to send messages and receive them?
- etc

**Comment by NagyZoltanPeter** [comment]
Currently test runs set up to send and check 300 variable sized message between two endpoint of status.prod network at every 3h.
