### ISSUE TITLE
chore: store sync should support syncs of more than 100 msg hashes

### ISSUE THREAD

**Issue by Ivansete-status** [waku-org/nwaku#3006]
### Description
@SionoiS  noticed the following issue while dogfooding `waku sync` in `status.staging`: 

```
"store client error: BAD_RESPONSE: BAD_RESPONSE: archive error: DIRVER_ERROR: can not attend queries with more than 100 hashes"
```

SP recommended to make the store client to properly handle an arbitrary number of message hashes and then having chunks of 100 msg hashes on each store query.

The offending code is https://github.com/waku-org/nwaku/blob/19feb6bd5874f35ee5a1adc52d05b186d4af3572/waku/waku_sync/protocol.nim#L279C8-L279C51 

Ideally, we should log the current and total number of msg shashes being sync'ed.

**Comment by SionoiS** [comment]
For context I saw queries with 3k hashes being requested.

If a limit of 100 hash per query is needed for Postgres that is fine but using the Store API should not require to know this limit.
