### ISSUE TITLE
chore: make negentropy to give better feedback when failures happen

### ISSUE THREAD

**Issue by Ivansete-status** [waku-org/nwaku#3007]
### Description
While dogdoofing `waku sync` in `status.staging` @SionoiS noticed that there are many negentropy failures but we don't know the actual reason why that happened.

- `failed to insert message`
- `erase failed`

The goal of this is to enhance negentropy's feedback in case a wrong condition happens.

For example, we see the following logs but the detail given by `negentropy` is not verbose enough:

https://github.com/waku-org/nwaku/blob/19feb6bd5874f35ee5a1adc52d05b186d4af3572/waku/waku_sync/protocol.nim#L61
https://github.com/waku-org/nwaku/blob/19feb6bd5874f35ee5a1adc52d05b186d4af3572/waku/waku_sync/protocol.nim#L72
https://github.com/waku-org/nwaku/blob/19feb6bd5874f35ee5a1adc52d05b186d4af3572/waku/waku_sync/protocol.nim#L487

**Comment by SionoiS** [comment]
AFAIK Inserting twice the same element would return an error, it is expected. Same for trying to erase twice the same element.

The problem is we don't know which error it is.
