### ISSUE TITLE
nim_waku_p2p_max_connections limit of 150 makes the canary think that the node is offline

### ISSUE THREAD

**Issue by siddarthkay** [waku-org/nwaku#3021]
## Background

ref -> https://canary.infra.status.im/service/174/

![Screenshot 2024-09-05 at 5 19 51 PM](https://github.com/user-attachments/assets/d97a1e6a-16e5-4193-bdd6-52cb50d44251)

## Details

When I checked `node-01.do-ams3.waku.sandbox` for these alerts.
- [x] Host was up.
- [x] p2p port was open.
- [x] Host had proper disk space.
- [x] docker logs did not show any unusal errors.

The reason why  canary thinks the node is offline was due to 
```
# P2P Connections
nim_waku_p2p_max_connections: 150
```   
cc @jakubgs 

## Acceptance criteria
We need a way for canary to be able to get node status when a node is busy else we may run into false positives during investigations of alerts.

**Comment by jakubgs** [comment]
The max on the fleet is 300:
```yaml
# Limits
nim_waku_p2p_max_connections: 300
```
https://github.com/status-im/infra-waku/blob/6e6849b1bd6b05897a73d1f3706c503ebb80951f/ansible/group_vars/node.yml#L34-L35

And indeed at times the nodes do hit 300:

![image](https://github.com/user-attachments/assets/47f95255-53e1-4591-82af-5639e3a2fe4d)
