### ISSUE TITLE
chore: store in status-go through nwaku

### ISSUE THREAD

**Issue by Ivansete-status** [waku-org/nwaku#3053]
### Description

status-go should support store through nwaku

To validate that, we need the TestBasicWakuV2 to work properly. We will consider this as achieved when the store part of that test works well.

https://github.com/status-im/status-go/blob/94dc345d8ef5fb95fd855a665b1d32f3b0e32008/wakuv2/waku_test.go#L180

**Comment by richard-ramos** [comment]
Requires this: https://github.com/waku-org/go-waku/pull/1239
API code was highly coupled to go-waku. Ended up doing a refactor so I can proceed to properly call store from status-go/nwaku

**Comment by richard-ramos** [comment]
Additional PRs created for this tasK:
- https://github.com/status-im/status-go/pull/6004
- https://github.com/status-im/status-go/pull/5984
- https://github.com/waku-org/go-waku/pull/1251
- https://github.com/waku-org/go-waku/pull/1249
- https://github.com/waku-org/go-waku/pull/1248
- https://github.com/waku-org/nwaku/pull/3154
- https://github.com/waku-org/nwaku/pull/3144
