### ISSUE TITLE
bug: intense execution of storage erase in waku-sync

### ISSUE THREAD

**Issue by Ivansete-status** [waku-org/nwaku#3129]
### Problem
Intense waku-sync operation that makes the node irresponsive

### Impact
Other protocols, such as `store` cannot operate as usual.

### To reproduce
Enable store-sync in `status.staging` fleet and then it appears an important number of logs with "storage erase failed"

### Screenshots/logs
Evidence of the issue in Kibana:
![Image](https://github.com/user-attachments/assets/bd20d0c3-216e-48e9-a472-339bb41ddbed)

https://kibana.infra.status.im/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-10-09T00:19:07.466Z',to:'2024-10-18T08:31:50.066Z'))&_a=(columns:!(logsource,message),filters:!(),hideChart:!f,index:ffcc22b0-0116-11ed-9719-cdd3b483481c,interval:auto,query:(language:kuery,query:'fleet:%20%22status.staging%22%20AND%20message:%20%22storage%20erase%20failed%22'),sort:!(!('@timestamp',desc)))

### nwaku version/commit hash
v0.33.1

**Comment by fryorcraken** [comment]
I thought the issue was that all nodes were connecting to the same node (first in the list) to sync?
