### ISSUE TITLE
Waku v2 JSON-RPC REST API: outstanding tasks

### ISSUE THREAD

**Issue by jm-clius** [waku-org/nwaku#332]
### Background

The JSON-RPC REST API for Waku v2 was [specified](https://github.com/vacp2p/specs/issues/233) and [implemented](https://github.com/status-im/nim-waku/issues/259) to cover basic functionality. This issue serves as a laundry list of possible tasks/improvements for more advanced functionality on the API. These are currently blocked by efforts elsewhere.

### Outstanding tasks

- [ ] All APIs: implement named parameters in JSON-RPC method calls. Blocked by https://github.com/status-im/nim-json-rpc/issues/90
- [x] Admin API: return information about connected `WakuRelay` peers. Blocked by https://github.com/status-im/nim-libp2p/issues/498
- [ ] Relay API: allow clients to receive push notifications on subscribed topics. Blocked until websocket support is added.

**Comment by LNSD** [comment]
Nimbus has deprecated it's JSON-RPC recently, and I think that we should follow their lead since we are investing in a REST API (#727 and  #1076).

**Comment by jm-clius** [comment]
Closing as "won't implement", as the HTTP REST API is replacing the JSON-RPC REST API and we won't be adding features to the latter.
