### ISSUE TITLE
Docs fails due to submodules

### ISSUE THREAD

**Issue by decanus** [waku-org/nwaku#337]
# Problem

We recently introduced a [docs CI](https://github.com/status-im/nim-waku/blob/master/.github/workflows/docs.yml) with the goal of generating user facing docs of nim-waku. The problem however is that the `nim doc` command relies on the dependencies in the `nimble` file, we on the otherhand actually manage our packages using submodules. This means it fails due to the fact that the submodules are at a different HEAD vs the tag  / master release used for the `nimble `file.

# Acceptance Criteria
 
Docs are automatically generate for the codebase whenever master is merged and released to github pages.

**Comment by oskarth** [comment]
cc @zah as you might know more about this

**Comment by jm-clius** [comment]
Moved to icebox for now.

**Comment by jm-clius** [comment]
Closed due to inactivity.
