### ISSUE TITLE
Improve docs re external tools (jq, multitail)

### ISSUE THREAD

**Issue by oskarth** [waku-org/nwaku#341]
# Problem

Currently we require some dependencies, and sometimes:
1) These requirements can be relaxed
2) They aren't documented

# Notes

- [x] PCRE requirement is removed from Nimbus 2, but not Nimbus 1 - can probably be relaxed?
- [ ] jq dev tool useful for querying cluster
- [ ] multitail required for running quicksim

Probably more, if so please mention it here.

**Comment by jm-clius** [comment]
@oskarth, moved to icebox for now

**Comment by jm-clius** [comment]
N.A. as we don't use multitail anymore, have new docs site, etc.
