### ISSUE TITLE
Windows build: fetch-dlls issue

### ISSUE THREAD

**Issue by mratsim** [waku-org/nwaku#379]
From Vacp2p telegram

![image](https://user-images.githubusercontent.com/22738317/108091648-34431800-707c-11eb-88b8-e4172853a6ea.png)

The user confirmed having run `make` and `make update`, I've pointed out what `fetch-dlls` does https://github.com/status-im/nimbus-build-system/blob/9c4c4d3acf8f13e8d973180548837cc738e14aa2/makefiles/targets.mk#L234.

Afaik fixing this should be straightforward.

For now I've invited the user in Nimbus #dev-helpdesk discord.

**Comment by jm-clius** [comment]
Windows build support is currently only experimental in nwaku. See https://github.com/waku-org/nwaku/issues/896.
