### ISSUE TITLE
FT-Store protocol: Handling asynchronous clocks

### ISSUE THREAD

**Issue by staheri14** [waku-org/nwaku#547]
## Problem
In the FT-store protocol, the underlying assumption is that nodes' clocks are synced with a maximum drift of 20sec. We need to figure out a better way to tackle clocks asynchrony. One potential solution is to detect or synchronize with a NTP server as part of waku setup script.

**Comment by jm-clius** [comment]
@LNSD given the last talks re ft-store, do you think keeping track of this problem in a separate issue is necessary?

**Comment by LNSD** [comment]
I don't know if it is still relevant. I need a broader understanding of the _ft-store_ plan to know if we still need the NTP synchronization.

**Comment by jm-clius** [comment]
Closing, as we have since changed store approach and tracking this elsewhere.
