### ISSUE TITLE
Rollback failed migration transactions

### ISSUE THREAD

**Issue by staheri14** [waku-org/nwaku#630]
# Problem

This issue is to improve error handling while executing DB migration scripts, that is (as suggested in https://github.com/status-im/nim-waku/pull/607#discussion_r651234086) to use SQL transactions to rollback data manipulation changes (inserts/updates), and then, after returning the error, attempt to execute the rollback script for the specific migration script that failed.

**Comment by jm-clius** [comment]
New approach to store/archive backends require DB operators to migrate/rollback DB schemes out of band. Nwaku can consider providing utility scripts here, but in general this becomes a different concern. Closing issue.
