### ISSUE TITLE
Atomic execution of SQL migration scripts

### ISSUE THREAD

**Issue by staheri14** [waku-org/nwaku#632]
# Problem

Currently, SQL migration scripts are executed one command at a time, if some failure happens in between, then there might be some commands left unexecuted and the migration would not go through as a whole. Atomic execution makes sure either all the commands of the same script are executed or none.

**Comment by jm-clius** [comment]
New approach to store/archive backends require DB operators to migrate/rollback DB schemes out of band. Nwaku can consider providing utility scripts here, but in general this becomes a different concern. Closing issue.
