### ISSUE TITLE
Breaking time query to a smaller interval in the resume proc

### ISSUE THREAD

**Issue by staheri14** [waku-org/nwaku#720]
# Problem
Currently, in the resume proc, when a node gets back online it attempts to download the history for his entire off period. This potentially results in several issues when the time interval is large:
-  The quired node that has the message history for a portion of that interval but not all of it, yet will return an empty result (the comparison logic is based on all or nothing). As such, the querier may end up querying multiple nodes and get back empty-handed, this is while the history gap could have been filled if the queried nodes would have been asked for smaller time windows.
- ~The size of history can get so large and exceeds the maximum limit of data transmission. In that case,  the connection gets closed.~

# Proposed solution
A better approach is that the node splits the offline time interval into smaller non-overlapping chunks and sends queries for those. 
The querying node must attempt to fill the history gaps sequentially, that is if the time chunks are t1, t2, and t3, then the node first queries all its connections for t1, then t2 and then t3. It should not proceed from t1 to t2 if it could not get any result for t1.  

# Acceptance Criteria
- [ ] The [`resume` API](https://github.com/status-im/nim-waku/blob/d74ef67087769bdbb2ddc2b0dde2e1eca7991e64/waku/v2/node/wakunode2.nim#L349) is updated and works as explained above
- [ ] The expected behavior is properly tested
- [ ] The necessary changes should be made on the [waku node2 API doc](https://github.com/status-im/nim-waku/blob/master/docs/api/v2/node.md)

**Comment by jm-clius** [comment]
Closing, as we're likely to go a different route when ft-store is eventually implemented. cc @LNSD
