### ISSUE TITLE
Publish docker image for wakunode2 and document its usage

### ISSUE THREAD

**Issue by D4nte** [waku-org/nwaku#737]
# Problem

The Prod fleet has limited capacity. Several js-waku users have reported stability [issues](#736) when working on their project.

The outcome of discussions around fleet capacity is that we prefer Waku users to support the network and deploy their own Waku v2 node.

At the moment, the setup also need a deployment of websockify. This is being resolved with #434.

# Acceptance Criteria

- [x] A docker image of the latest version of nim-waku published (there are several repos available: DockerHub, GitHub).
- [x] A tutorial for developer to deploy the docker image.
- [x] A docker compose file to deploy the docker image.

**Comment by jm-clius** [comment]
We do publish to DockerHub already: https://hub.docker.com/r/statusteam/nim-waku and have a public compose file.

Keeping this issue open, as documentation is lacking.

**Comment by jm-clius** [comment]
Closing. We now have a [docker docs](https://github.com/waku-org/nwaku/blob/019f357dc948da11ec2eae7f6403adfb347e4dce/docs/operators/docker-quickstart.md) for nwaku.
