### ISSUE TITLE
Inconsistent naming of flags compared to Go-Waku

### ISSUE THREAD

**Issue by jakubgs** [waku-org/nwaku#743]
While working on the Ansible role for `go-waku` I found a few inconsistencies in flag naming compared to `nim-waku`:

* `--metrics*` instead of `--metrics-server*` (I think the shorter name is better tbh)
* ~~`--store-node` instead of `--storenode` (might be better changed in `nim-waku`)~~
* ~~`--filter-node` instead of `--filternode` (might be better changed in `nim-waku`)~~
* ~~`--lightpush-node` instead of `--lightpushnode` (might be better changed in `nim-waku`)~~

I think we should keep the schema of adding a dash between words consistent.

I've opened a separate issue for `go-waku` and some other flags: https://github.com/status-im/go-waku/issues/80

**Comment by chair28980** [comment]
Follow up with Alvaro

**Comment by Ivansete-status** [comment]
Morning all! 
@chair28980 , @fryorcraken - I suggest closing this for now until we potentially resume the `go-waku` development in the future. Therefore, I'd only keep opened the `go-waku` issue (in the description.)
