### ISSUE TITLE
`nim-waku`: high-level design document for Waku v2

### ISSUE THREAD

**Issue by jm-clius** [waku-org/nwaku#771]
## Background

The `nim-waku` codebase grows more or less organically as reference implementation from the ever-expanding [set of RFCs](https://rfc.vac.dev/) that Vac produces for Waku.  `nim-waku` aims to be a straightforward implementation of the protocol specs, and to adhere to implementation-oriented recommendation specs.
However, without a high-level design document it may not always be evident from existing documentation:
- how the different modules/discrete functions fit together in implementation
- how best to expand the existing codebase with new features
- where the external interfaces are

## Scope

We'll only focus on Waku v2 for now. As a first step we'll document core Waku v2 functionality and leave things like the bridge, chat2, etc. for later additions.

In my mind an HLD needs at least the following:
- [ ] Diagram showing all of the following parts and the interface between them:
  - the core wakunode2 module
  - each different protocol and interaction with core module
  - message and peer stores
  - persistent database(s)
  - external APIs (currently only Nim an JSON-RPC)
- [ ] A short description of each element above

@rshiv, anything specific that you'd add to the list above for a useful HLD document?
cc @oskarth @staheri14

**Comment by rshiv** [comment]
LGTM, seems an excellent start for long term documentation.

**Comment by jm-clius** [comment]
This has since been done. See new [docs site](https://docs.waku.org/) and [client architecture](https://miro.com/app/board/uXjVMD62hMA=/) diagram.
