### ISSUE TITLE
Received a broken close frame containing a reserved status code.

### ISSUE THREAD

**Issue by teacoat** [waku-org/nwaku#807]
Occasionally will get this error:

Got it once on Jan 1, 2022 at 12:55am EST
![image](https://user-images.githubusercontent.com/3913019/147895444-7af5bae6-b759-4ccd-b731-d833ccf49a79.png)

Just got it again Jan 2, 2022 at 9:03pm EST
![image](https://user-images.githubusercontent.com/3913019/147895418-728c4962-8c1d-455a-9de8-e6fcddd7b5de.png)

edit:
Got it again Jan 3, 2:33pm EST
![image](https://user-images.githubusercontent.com/3913019/147972189-69d95f6d-6bc1-46f9-bade-013b1b0a0f53.png)

Using js-waku

**Comment by D4nte** [comment]
Looking at the websockify logs for the same instance, I can see

`code 405, message Method Not Allowed`

https://kibana.infra.status.im/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-01-01T05:30:00.000Z',to:'2022-01-01T06:00:00.000Z'))&_a=(columns:!(message,host,syslogtag),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:d6db7610-60fd-11e9-98fa-2f101d13f938,key:syslogtag,negate:!f,params:(query:docker%2Fwebsockify),type:phrase),query:(match_phrase:(syslogtag:docker%2Fwebsockify)))),index:d6db7610-60fd-11e9-98fa-2f101d13f938,interval:auto,query:(language:kuery,query:''),sort:!(!('@timestamp',desc)))

For the 9:03 I can see:

https://kibana.infra.status.im/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-01-02T04:00:00.000Z',to:'2022-01-02T04:05:00.000Z'))&_a=(columns:!(message,host,syslogtag),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:d6db7610-60fd-11e9-98fa-2f101d13f938,key:syslogtag,negate:!f,params:(query:docker%2Fwebsockify),type:phrase),query:(match_phrase:(syslogtag:docker%2Fwebsockify)))),index:d6db7610-60fd-11e9-98fa-2f101d13f938,interval:auto,query:(language:kuery,query:''),sort:!(!('@timestamp',desc)))

```
Jan 2, 2022 @ 04:00:44.269 - [02/Jan/2022 04:00:44] code 405, message Method Not Allowed
...
Jan 2, 2022 @ 04:00:44.219 - - [02/Jan/2022 04:00:44] code 405, message Method Not Allowed
...
Jan 2, 2022 @ 04:03:47.374185.100.87.136 - - [02/Jan/2022 04:03:47] code 501, message Unsupported method ('POST')
...
Jan 2, 2022 @ 04:03:57.515147.135.62.68 - - [02/Jan/2022 04:03:57] code 501, message Unsupported method ('PUT')
```

@teacoat how exact are the times you provided?

**Comment by teacoat** [comment]
> @teacoat how exact are the times you provided?

may be off by a min or two, i can try to get a more specific time next time it pops up

**Comment by oskarth** [comment]
Considering native WS support is on its way in the next release, we can probably deprioritize this for now.

**Comment by oskarth** [comment]
See if this fixes it https://github.com/status-im/nim-waku/issues/808

**Comment by D4nte** [comment]
> @D4nte, any feedback on native websocket performance after the release? According to me things are stable now and issues related to websockify can probably be closed (once we disable websockify).

I haven't checked yet. I want to finish js-waku upgrade to latest libp2p library first https://github.com/status-im/js-waku/pull/803 as it contains a stream disconnection bug fix https://github.com/libp2p/js-libp2p/pull/1221 which I hope will help with connection stability.

Once done, I can do more thorough testing of nim-websocket integration in nwaku.

**Comment by jm-clius** [comment]
We are now using native websockets. Closing.
