### ISSUE TITLE
Wallet integration into waku-rln-relay

### ISSUE THREAD

**Issue by staheri14** [waku-org/nwaku#819]
# Problem
waku-rln-relay requires interaction with a smart contract in two phases: Registration and Slashing For both, the user needs to sign the transaction to deposit/Withdraw some Ether.  Sending transactions requires access to the user's Ethereum account private key. It would not be secure to ask the user's private key directly to the waku-node. Thus, we need to use an external wallet app to perform the transactions upon request from the waku node. 
This issue is to explore existing options for wallet integration into nim-waku and to identify the most convenient way to do so.

# Potenitial solution
Can look into how this is done in nimbus.

**Comment by staheri14** [comment]
cc: @oskarth

**Comment by oskarth** [comment]
cc @jm-clius as well

**Comment by jm-clius** [comment]
Done and tracked elsewhere.
