### ISSUE TITLE
Increase message size limit

### ISSUE THREAD

**Issue by du82** [waku-org/nwaku#825]
It would be great if we could increase the size of messages to 2MB so we (Status users/devs) can send images that aren't blurry or lacking in detail. If we want to have things like a profile banner (that isn't blurry), blogging, and possibly small file sharing, we would need a larger message size limit.

**Comment by D4nte** [comment]
As discussed in https://github.com/status-im/nim-waku/issues/739 we see risks in increasing the message size limit, especially in relation to the Waku Relay protocol and retaining the "run anywhere" characteristics on devices with limited bandwith.

At this stage I'd recommend to explore a message splitting protocol that would split bigger payloads in a smaller Waku Messages.

**Comment by jm-clius** [comment]
Different approaches suggested for large messages (including chunking) suggested to Status and other protocols. Waku base routing layer should be protected against unreasonably large message sizes. Closing issue as similar efforts tracked elsewhere.
