### ISSUE TITLE
Store: `startTime` and `endTime` set to `0` instead of not being defined

### ISSUE THREAD

**Issue by D4nte** [waku-org/nwaku#885]
When doing a waku store query, I noticed that in the `HistoryResponse` I get from nim-waku, the `query` field always contains the `startTime` and `endTime` and they are set to `0`.

I would expect them to either:
- Be set to the values passed in the initial `HistoryQuery`
- Not be present if no value was passed in the initial `HistoryQuery`

In protobuf terms, `0` is different from not being present. As all proto 3 fields are optional, there is no need for default values.

I haven't witnessed any consequent behavior issue at this stage. However, it is a dangerous practice and could lead to issues in the future if similar behaviour is adopted for other fields.

**Comment by jm-clius** [comment]
@LNSD I think this will be addressed as part of the Store v3 protocol. We could close this issue then, so linking to https://github.com/vacp2p/rfc/issues/552 so that we remember to do this.

**Comment by Ivansete-status** [comment]
I close this as I consider it is not happening in `v0.18.0-36-g4342e9`.
I got the next response:
```
{"jsonrpc":"2.0","id":"id","result":{"messages":[{"payload":"VGhpcyBpcyBhIG1lc3NhZ2UK","contentTopic":"/waku/2/default-content/proto","version":0,"timestamp":1689433088225954193,"ephemeral":false},{"payload":"VGhpcyBpcyBhIG1lc3NhZ2UK","contentTopic":"/waku/2/default-content/proto","version":0,"timestamp":1689433089099905525,"ephemeral":false}],"pagingOptions":null}}
```

@D4nte - reopen it again if you disagree. Thanks!
