### ISSUE TITLE
Language Bindings

### ISSUE THREAD

**Issue by D4nte** [waku-org/nwaku#904]
## Problem

There are a variety of dApps that are native, especially in the game ecosystem. Such dApps use languages such as Swift, Kotlin, C# (Unity). Currently, none of the existing Waku implementations offer a straight manner to integrate Waku in such languages, especially if a single binary requirement applies (iOS).

## Proposed Solution

- [ ] Provide C-bindings
- [ ] Define C-bindings API in spec
- [ ] Provide a hello world example that uses the C-bindings in one of the languages above. Kotlin seems to be a good first choice as it enables native dApps on both Android and iOS.

**Comment by oskarth** [comment]
fyi @jm-clius

**Comment by jm-clius** [comment]
cc @richard-ramos

**Comment by chair28980** [comment]
Closing issue as duplicate.
