### ISSUE TITLE
discv5+DNS: consolidating ENR information

### ISSUE THREAD

**Issue by kaiserd** [waku-org/nwaku#915]
## Background

Currently `nwaku` builds two separate ENRs (in case discv5 is active) holding separate information.
[One](https://github.com/status-im/nim-waku/blob/0131d1437e5f1c729aed0f4d229e4275acecef37/waku/v2/node/wakunode2.nim#L228) when initializing a waku node, and [another one](https://github.com/status-im/nim-waku/blob/0131d1437e5f1c729aed0f4d229e4275acecef37/waku/v2/node/wakunode2.nim#L1133) when initializing the discv5 subsystem.
The former might contain a DNS multiaddress, while the latter contains the UDP port necessary for discv5.

## Goal / Motivation

Both ENR instances should contain the union of their respective current information.

* reduces confusion, because both ENR instances can be used interchangeably
* all information, including dns4 multiaddresses are discoverable via discv5
* sufficient to print a single ENR in the log (see #913)

## non-goals of this issue

For now, the discv5 subsystem holds a separate ENR instance. This issue does not propose consolidating both into a single ENR instance, as that would require more refactoring.
We might address that in the future though.

cc @jm-clius @richard-ramos 

## Acceptance criteria

- [ ] Wakunode2 and discv5 subsystem ENRs contain the same information
- [ ] successfully tested on experimental/local test fleet

**Comment by jm-clius** [comment]
This could be a dependency for https://github.com/waku-org/nwaku/issues/1475

**Comment by rymnc** [comment]
This issue is addressed in #1512

**Comment by rymnc** [comment]
@jm-clius can we close this issue as #1512 has been merged?
