### ISSUE TITLE
`nwaku` API: push notifications on Relay and Filter API

### ISSUE THREAD

**Issue by jm-clius** [waku-org/nwaku#938]
## Background

When the JSON-RPC API was implemented for `nwaku` nodes, one [outstanding task](https://github.com/status-im/nim-waku/issues/332) was push notifications for new messages on subscribed `pubsubTopic`s and `contentTopic`s on the Filter and Relay APIs. This task was awaiting Nim websocket support, which has since been added.

Note, however, that with the introduction of a secure web server in Nim it is now possible to implement an [HTTP REST API](https://github.com/status-im/nim-waku/issues/727), which may be even more useful than the JSON-RPC API.

## Acceptance criteria

- [ ] Ability to receive push notifications for new messages over a websocket connection in either the JSON-RPC API, a new HTTP REST API, or both.

cc @sbc64

**Comment by Ivansete-status** [comment]
I think that this can be closed as we have the REST API for `relay` as it is implemented and Zoltán will implement the `filter` one. @jm-clius , kindly close this if you agree.

**Comment by jm-clius** [comment]
The new APIs do not necessarily remove the polling requirement on client nodes. This issue can remain open to track work to convert from a polling to "push" model based on websockets.

**Comment by chair28980** [comment]
@jm-clius should we keep this issue open, or re-scope this work into 2024 milestones/epics?

**Comment by jm-clius** [comment]
The issue of a push vs polling interface has been open but unactioned for quite a long time. As it stands I think the polling API works well enough for us to descope this work (for now). I'd close this issue and reopen when the need arise
