### ISSUE TITLE
Refactoring the waku-rln-relay module

### ISSUE THREAD

**Issue by staheri14** [waku-org/nwaku#946]
This issue is to address a few refactoring tasks:
1) to replace all the float64 time values in the rln-relay module with int64 type to make it consistent with the rest of the nim-waku codebase. 
2) change the variables and types cases and make them consistent: 2) camalCase for variables 2) PascalCase for types 3) remove all the snake case uses in function names and variables if any 
3) Separate data from logic, move rln-relay static keys and solidity byte codes to separate files, and load them from their files

**Comment by jm-clius** [comment]
@rymnc I'm not sure if this issue is still necessary/relevant. Some of these items may have been addressed or are already captured in other issues?

**Comment by rymnc** [comment]
yes, we can close this issue now
