### ISSUE TITLE
feat: node config generation tool

### ISSUE THREAD

**Issue by kaiserd** [waku-org/nwaku#956]
## Background / Motivation

Currently, it is difficult to setup a `nwaku` node with a fixed ID, which is important for testing.
When starting a `nwaku` node without parameters, a new key pair (and in turn a new ID) is generated.

The problem gets even more complex when trying to setup a test fleet that is connected following a certain topology.

## Solution

The proposed solution is a cli tool that prints node commands for starting a fleet consisting of n nodes that are setup in a full mesh topology.
(Fleet size 1 allows generating a command for starting a single node.)

Note: This tool will not be concerned with safe key generation but rather be limited to testing purposes.

## Acceptance criteria

* [ ] node command generator cli tool implemented
* [ ] set of generated node commands allows starting a fleet using a single network interface (requires appropriate port shifting)
* [ ] optional: support for generating config files ( see #952 )
* [ ] optional: support for other topologies / discv5

**Comment by jm-clius** [comment]
Thanks! Also see https://github.com/status-im/nwaku/pull/957

**Comment by Ivansete-status** [comment]
This can be closed as we can set a fixed key to a node. For example, we can run a node with:
```
./build/wakunode2 --config-file=cfg_node_a.txt
```

[cfg_node_a.txt](https://github.com/waku-org/nwaku/files/12061999/cfg_node_a.txt)

On the other hand, we can set up an arbitrary topology of nodes thanks to the next repo:
https://github.com/waku-org/waku-simulator
