### ISSUE TITLE
fix: graceful shutdown if port is not available

### ISSUE THREAD

**Issue by kaiserd** [waku-org/nwaku#972]
If a port (both specified and/or default) is not available (i.e. a TCP socket cannot be established), `nwaku` crashes with

```
Error: unhandled exception: Failed to start one transport [TransportError]
```

This is also linked to #959 and #971:
If network resources are not freed, the specified port might not be available (yet) when restarting the node and crash with this message.

## acceptance criteria

* [ ] handle the exception
* [ ] show a message saying the port was not available.

(Could suggest to use `--ports-shift`.)

**Comment by Ivansete-status** [comment]
I close this as the `nwaku` node ends its execution in that scenario, giving the next comment:
```
ERR 2023-07-15 17:47:05.486+02:00 5/7 Starting node and protocols failed     topics="wakunode main" tid=179515 file=wakunode2.nim:92 error="failed to start waku node: (98) Address already in use"
```
