### ISSUE TITLE
Using sub-command to group rln-relay config options 

### ISSUE THREAD

**Issue by staheri14** [waku-org/nwaku#999]
This issue is to track the following [comment](https://github.com/status-im/nwaku/pull/992#discussion_r893633559) that is to use [sub-commands](https://github.com/status-im/nim-confutils) to group rln-relay config options together.

**Comment by Ivansete-status** [comment]
@rymnc - can this be closed?

**Comment by rymnc** [comment]
Yes, we don't need this anymore.
